### ISSUE TITLE
Speech translation synthesis sample incomplete

### ISSUE THREAD

**Issue by hramoser** [Azure-Samples/cognitive-services-speech-sdk#100]
**Describe the bug**
The synthesis sample does not call "SetVoiceName". Hence no audio is synthesized. 

**To Reproduce**
Compile Windows C++ console application and check if there is any synthesis result in TranslationContinuousRecognition.
With SetVoiceName everything works ok.

**Expected behavior**
Synthesis output.

**Version of the Cognitive Services Speech SDK**
1.0.1

**Platform, Operationg System, and Programming Language**
 - Linux Ubuntu 16.04

**Additional context**

**Comment by wolfma61** [comment]
there are different samples for translation, some demonstrate translation with voice output, some don't set the voice output, hence no audio result. Not the same set of sample are available in all languages. Since the API calls are easily 'transferable' between different languages, this shouldn't be a problem...

**Comment by hramoser** [comment]
I got this. But the sample "TranslationContinuousRecognition" in translation_samples.cpp
 should output synthesis results but it does not (because the voice is not set).

**Comment by wolfma61** [comment]
although listening for synthesisevents, not sure it was ever intended too ...
focus is on continuous recognition.
You are welcome to add and create a PR
