### ISSUE TITLE
nodeJS Pronunciation assessment errors initial silence timeout.

### ISSUE THREAD

**Issue by Dgg1997** [Azure-Samples/cognitive-services-speech-sdk#1003]
![image](https://user-images.githubusercontent.com/50827510/111950766-b14f2a80-8b1d-11eb-87b5-cecbbc5e8e2e.png)

**Comment by trrwilson** [comment]
Thanks for contacting us!

Can you share a bit more about the audio input and/or code involved? That duration value (11,200,000 hundred-nanosecond units) indicates that the speech service believes it detected a significant amount (1120ms) of initial silence, which is why you see that response. Is this real-time audio from a microphone, from a file, or something else through a stream? What's the audio format? Any additional configuration properties set? Some more information will help us advise on why you're not seeing the response you expect.

**Comment by yulin-li** [comment]
@yinhew Could you help to comment this issue?

**Comment by yinhew** [comment]
@yulin-li I have the same question as what @trrwilson mentioned above.
Waiting for reply from @Dgg1997 .

**Comment by pankopon** [comment]
Closed since no details received. Please open a new issue if more support is needed.
