### ISSUE TITLE
 speech to text on word level instead of repeating the text and appending new text   in c#

### ISSUE THREAD

**Issue by yashugupta786** [Azure-Samples/cognitive-services-speech-sdk#1030]
I am using the Recognizing object of speech to text .It is giving the same text again and again as output and appending the new text in the sentence . How to get speech transcription as in MS TEAMS live captions. 

Recognizing is repeating the text again and again and appending the new text in the same . how to get that as in live captions

for example

RECOGNIZ-ING: Text={"Duration":4300000,"Id":"33661131e4b54d5cb5954ac005c712ee","Offset":79600000,"Text":"What is"}
RECOGNIZ-ING: Text={"Duration":6600000,"Id":"b24420e71a8b4b8a8276414c0a78edd8","Offset":79600000,"Text":"What is the weather"}
RECOGNIZ-ING: Text={"Duration":17400000,"Id":"199cc81c096e4e108451b494f0b99313","Offset":79600000,"Text":"What is the weather of Seattle"}
RECOGNIZ-ING: Text={"Duration":17600000,"Id":"199cc81c096e4e108451b494f0b99313","Offset":79600000,"Text":"What is the weather of Seattle today ?"}
RECOGNIZ-ED: Text={"DisplayText":"What is the weather of Seattle today ?","Duration":17600000,"Id":"7e02086a833542d79d435ac9abf4b7dc","Offset":79600000,"RecognitionStatus":"Success"}

In Recognizing it is appending new text but every time it takes the earlier recognizing text . How we can have the recognizing but not appending the earlier text . I MS Teams live captions it did not repeat the text

**Comment by ralph-msft** [comment]
The recognizing event provides the speech service’s best hypothesis based on the audio it has received so far. Since this is a hypothesis, it is subject to change as more audio is received which provides the service with more context about what is being said. With this in mind, the recognizing event is working as intended.

In your example, the recognizing events seem to always include one or more words in addition to the previous recognizing event. However this is not always the case. It is quite possible that previously hypothesized words would change in the next hypothesis. Consider this as an example:
```
[Recognizing] you're
[Recognizing] your happiness
[Recognizing] your happiness is
[Recognizing] your happiness is guaranteed
[Recognized] Your happiness is guaranteed.
```
Notice how “you’re” gets corrected to “your” in the second hypothesis in addition to the extra “happiness”. This can happen more frequently in other languages due to their different grammar rules.

If your goal is to add captions one word at time, and it doesn’t need to be live (e.g. creating captions for a video for later playback), you can use the Recognized events and take advantage of RecognitionResult [OffsetInTicks](https://docs.microsoft.com/dotnet/api/microsoft.cognitiveservices.speech.recognitionresult.offsetinticks?view=azure-dotnet) (how long from the start of the audio this recognition was found), as well as the [Duration](https://docs.microsoft.com/dotnet/api/microsoft.cognitiveservices.speech.recognitionresult.duration?view=azure-dotnet) property (how long this recognition was) to simulate the word at time captions.

For a live scenario, you will need to use the Recognizing events and do some additional processing to create the word at time captions that takes into account corrections to previous words. For some languages (e.g. English) it may help to ignore the last 1-2 words in the Recognizing events as those are the most likely to be updated.

**Comment by yashugupta786** [comment]
Hi @ralph-msft  I am using unmixed audio buffer from MS TEAMS directly and i am getting audio bytes from there  . When we do the  transcription/ translation with recognize  method . It is very slow and the results also come very late from the recognized methods instead of recognizing

**Comment by ralph-msft** [comment]
If you are trying to add captions live, the recognizing event is the one you'd want to use. In this case you'd need to add your own logic to create the subtitle/caption behaviour you are expecting.

At this point, this does not appear to be a bug report, but rather a feature request for the Cognitive Speech recognition service.

**Comment by ralph-msft** [comment]
We've file a feature request to add this functionality. At this point we don't have ETA to share on _if_ or when this would get implemented.  Please subscribe to the issue to continue to get the latest updates
