### ISSUE TITLE
流式语音识别

### ISSUE THREAD

**Issue by cl-6666** [Azure-Samples/cognitive-services-speech-sdk#1053]
**Is your feature request related to a problem? Please describe.**
I want to record through my own microphone, and go to your Microsoft platform to identify in real time based on the audio stream returned by the microphone. It seems that this is not supported by viewing the document

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by chschrae** [comment]
Hi there,

Thank you for your issue. If I read it correctly, it seems you would like to do Speech Recognition from your microphone or from the audio stream returned from your microphone. This is absolutely possible and one of the main reasons the SDK exists.

There are several quickstarts referenced in the readme of this repository so that may be a good place to start. If you have an audio stream that you need to use instead of letting the SDK read from your microphone, you are looking for the PullAudioInputStream version in this sample https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/cpp/windows/console/samples/speech_recognition_samples.cpp

There is also a separate repository with larger samples in it: https://github.com/Azure-Samples/Cognitive-Services-Voice-Assistant

Feel free to respond if I mistook what you needed and you need further assistance.

**Comment by cl-6666** [comment]
Nín hǎo wǒ kàn nǐ zhè biān fā de shì windows de ànlì, wǒ zhè biān xiǎng yào de shì Android liú shì shìbié, chǎngjǐng shì gēnjù wǒmen nèibù de màikèfēng, ná yīnpín liú shíshí qù nǐmen wēiruǎn píngtái shìbié

volume_up
69 / 5000
翻译结果
Hello, I think what you posted here is a Windows case. What I want here is Android streaming recognition. The scene is based on our internal microphone, and the audio stream is sent to your Microsoft platform in real time for recognition.
