### ISSUE TITLE
JS SDK vs REST API for Speaker Verification

### ISSUE THREAD

**Issue by ajay960singh** [Azure-Samples/cognitive-services-speech-sdk#1091]
The model scores for JS SDK and REST API in Text-independent Speaker verification are different. Is this the right behaviour? Because we would assume that internally Microsoft would be using the same model for Speaker verification. What is the reason for this discrepancy?

<img width="734" alt="image" src="https://user-images.githubusercontent.com/34549910/118652968-b8847300-b804-11eb-9512-8ec73921b84d.png">
<img width="454" alt="image" src="https://user-images.githubusercontent.com/34549910/118653017-c20ddb00-b804-11eb-86b2-d67ba70f0dae.png">

**Comment by glharper** [comment]
@ajay960singh From testing this with JS SDK, using the same four files to enroll and then verify, I'm getting different scores each time. Because JS SDK doesn't generate those scores, I can't provide you with the insight you're asking for. I will ping the backend service team and ask them to provide an explanation here.

**Comment by glharper** [comment]
@ajay960singh A few follow-up questions, in addition to files vs microphone. Which version of JS speech SDK are you using, and is this a custom version of JS SDK? Also, can you provide the JS code you're using to produce the verification result?

**Comment by jhakulin** [comment]
@ajay960singh Please provide the information so that we can help you further.

**Comment by pankopon** [comment]
Closed since no further updates since May. Please open a new issue if more support is needed.
