### ISSUE TITLE
Mock continuous speech recognition response with pytest

### ISSUE THREAD

**Issue by achen353** [Azure-Samples/cognitive-services-speech-sdk#1100]
Hello everyone,

I'm trying to create a test and mock the response of the continuous speech recognition (from file) with `pytest` runner. I read the [documentation](https://github.com/Azure/azure-sdk-for-python/blob/master/doc/dev/mgmt/tests.md). However, I'm still not sure how exactly I should implement the test. I'd really appreciate some help.

<pre><code>
def transcribe_azure_speech_file(speech_file):
    speech_config = speechsdk.SpeechConfig(subscription=SUBSCRIPTION_KEY, region=REGION)
    audio_input = speechsdk.AudioConfig(filename=speech_file)
    auto_source_lang_config = speechsdk.AutoDetectSourceLanguageConfig(languages=["en-US"])
    speech_recognizer = speechsdk.SpeechRecognizer(
        speech_config=speech_config,
        audio_config=audio_input,
        auto_detect_source_language_config=auto_source_lang_config
    )

    transcripts = []
    done = False

    def _stop_cb(evt):
        """callback that signals to stop continuous recognition upon receiving an event `evt`"""
        print('CLOSING on {}'.format(evt))
        nonlocal done
        done = True

    def _recognized_event(evt):
        result = evt.result
        start_time = result.offset / 10e6
        end_time = start_time + result.duration / 10e6

        transcripts.append(
            {
                "transcript": result.text,
                "start_time": start_time,
                "end_time": end_time,
            }
        )

    # connect callbacks to the events fired by the speech recognizer
    speech_recognizer.recognized.connect(_recognized_event)
    # stop continuous recognition on either session stopped or canceled events
    speech_recognizer.session_stopped.connect(_stop_cb)
    speech_recognizer.canceled.connect(_stop_cb)

    # start continuous speech recognition
    speech_recognizer.start_continuous_recognition()
    while not done:
        time.sleep(0.25)

    speech_recognizer.stop_continuous_recognition()

    return transcripts
<code><pre>

**Comment by dargilco** [comment]
Hi @achen353 it's not clear to me what you are trying to do. Can you give more information?  
Darren

**Comment by achen353** [comment]
Hi @dargilco! I'm trying to create a `pytest` case for speech recognition by mocking the events fired by `speech_recognizier`.

**Comment by achen353** [comment]
@dargilco  This might help to clarify my question:

If I understand the API correctly,`speech_recognizier` is an instance of `SpeechRecognizer` and it fires a `SpeechRecognitionEventArgs` event when it completes transcribing a segment of the given speech file (with the transcription result contained in its `result` property). 

I'd like to create a pytest to test `speech_recognizer` by mocking the transcription result somehow. I was thinking about mocking the `SpeechRecognitionEventArgs` object but I'm not sure how to implement it exactly.

**Comment by dargilco** [comment]
@achen353 So you are trying to write a substibute (a mock) for speech recognition results, in order to test your application (which consumes speech recogntion results). In order for your test to be deterministic and repeatable, you would like the mock to produce the same exact speech recogntion resutls on every run. Is that correct? There is an option of course to use Speech SDK with WAV file input, such that you can autoate it and get the same recognition results on every run (and not mock it). But then of course you will be billed for doing speech recognition every time you run the test. So I can see why you would want to mock Speech SDK. 
I'm not sure I know how to help you with mocking, since this seems specific to your application needs and not a Speech SDK issue.

**Comment by achen353** [comment]
@dargilco I see [here](https://github.com/Azure/azure-sdk-for-python/blob/master/doc/dev/mgmt/tests.md#providing-credentials-to-the-tests) that one could simulate authenticating with Azure with a fake credential file. And further down the same documentation, it mentions a "more sophisticated fake object" in [Example 2](https://github.com/Azure/azure-sdk-for-python/blob/master/doc/dev/mgmt/tests.md#example-2-basic-preparer-usage) and [Example 3](https://github.com/Azure/azure-sdk-for-python/blob/master/doc/dev/mgmt/tests.md#example-3-more-complicated-preparer-usage). I wonder if there's a development SDK for creating substitutes to simulate speech recognition without getting billed for real usage?

Perhaps the contributors of the repo I linked above would be more familiar with what I'd like to achieve but the repo doesn't seem to open to question like this as an Issue :(

**Comment by dargilco** [comment]
@achen353 If I needed to test an app that uses Speech SDK for Speech Recognition, I would write a shim layer above the Speech SDK API calls. My application would interact with this shim layer, instead of Speech SDK directly. This shim layer will normally by a pass-through for API calls and events to Speech SDK (in normal usage), but under test usage, it will mock the Speech SDK APIs by accepting API calls from the app and replying with some pre-defined (configurable) responses. The mock will not contact any web service. The mock will have some internal timing mechanism to invoke a "recognizing" and "recognized" events with pre-defined (configurable) speech recognition results. Will something like this not meet your needs? We don’t have public sample code for it, however I can see how something like this can be useful for developers.
