### ISSUE TITLE
Transcription failed: The recordings URI contains invalid data.

### ISSUE THREAD

**Issue by humak** [Azure-Samples/cognitive-services-speech-sdk#1109]
Hello,
I am using Batch Transcription api with python and getting error 'Transcription failed: The recordings URI contains invalid data.'. My files are on wav format and it is strange that I am getting this error because I used these same files with this api before and it worked properly several times. Can you please help?
I have already read the releated closed issues but not helped. ( https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/399 )
Thanks,
(You can ping me on teams, t-hkalayci )

**Comment by zhouwangzw** [comment]
Could you please share the transcription id of failed transcriptions and the approximate time and regions? Thanks!

**Comment by humak** [comment]
Thank you for your fast response. Here they are:

05/28/2021 03:00:26 PM Turkey Standard Time Starting transcription client...
05/28/2021 03:00:27 PM Turkey Standard Time Created new transcription with id 'e3fac6d4-5436-45ed-9e4e-5a6ceba00ac7' in region westeurope
05/28/2021 03:00:27 PM Turkey Standard Time Checking status.
05/28/2021 03:00:32 PM Turkey Standard Time Transcriptions status: Failed
05/28/2021 03:00:32 PM Turkey Standard Time Transcription failed: The recordings URI contains invalid data.

**Comment by zhouwangzw** [comment]
It seems that your audio is stereo and you asked for diarization in the request. Diarization only works for mono audio, as described [here](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/batch-transcription#configuration-properties). It might have worked in the past due to a bug in our system which just ignores diarization for stereo audio. Now an explicit error is returned users, since diarization cannot be performed on stereo audio. You either need to transform stereo audio into 2 mono audio files or disable diarization if it is not needed. 
Btw. You can find detailed error message in the report.json which is provided as a part of returned result files. You can find the link to report.json via GET files API.
Thanks.

**Comment by humak** [comment]
Worked! Thank you so much for the explanation!
