### ISSUE TITLE
Real-time Speaker Diarization and Transcription

### ISSUE THREAD

**Issue by ajay960singh** [Azure-Samples/cognitive-services-speech-sdk#1119]
Hey guys,

We are building a real-time async pipeline for streaming audio from virtual web conferencing tools.

We are able to do Transcription using 'continuous recognition' but we also want to do Speaker Diarization (SD) to identify who's speaking at what time. We were not able to find documentation for SD. Is it possible share some resource (API, Python SDK, Tutorial) regrading the same?

Thanks

**Comment by BrianMouncer** [comment]
It sounds like you are asking about our "conversational transcription" project?
If so, here is an overview that also has a few links to more details.
This feature is currently in preview so we can get some feed back on design and usage.
Please let us know what you think.
 
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/conversation-transcription

If you are asking about the none real time version, or the stand alone Speaker ID/Speaker verification APIs, please let me know.

**Comment by ajay960singh** [comment]
Hey Brian,

A few questions abt 'conversational transcription'-

1. We want to analyse virtual calls on Zoom etc. (16k Hz) but it seems like it's build for physical meetings. Is that right?
2. Also from Documentation, it seems like conversational transcription SDK is in JS and C#. So can you pls refer us to the Python SDK or REST API  for using and testing this?
3. You mentioned you have stand alone Speaker ID/ Speaker Verification APIs available. Do you also have stand alone Speaker Diarization APIs available?

Thanks

**Comment by HeidiHanZhang** [comment]
Some answers FYI:
1. Conversation transcription is designed for in-room meetings which need to diarize different participates' words thru one microphone device. For online meeting like Zoom, since each participate is in different separate channel, you may have easier and cheaper ways to separate them in client side.
2. current conversation transcription SDK does not support Python. It is in our backlog though.
3. In Conversation Transcription, speaker enrollment is optional but not mandatary, so you can use it just for diarization without SpeakerID.  We do have Batch Diarization https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/batch-transcription#speaker-separation-diarization, it only support 2 speakers and for a offline batch mode, we will extend it to 2+ speakers in the future.

If you have any question on Conversation Transcription, you can send us email thru CTSFeatureCrew@microsoft.com

**Comment by glecaros** [comment]
Hi @ajay960singh, I'll close this item. If you need further help please feel free to reopen or create a new issue.
Thanks!
