### ISSUE TITLE
Multi-device Conversation: Allow conversation to be continued even if Host leaves the conversation 

### ISSUE THREAD

**Issue by priyankblitzz** [Azure-Samples/cognitive-services-speech-sdk#1151]
**Describe the bug**
Hello,
In our application there are chances of more than  2 participants can join the call at the same time. Now during the call if Host
leaves the call in between(which is a very general scenario) the Multi-device Conversation is stopped and now no one can see the Captions as the Host is left. Is there any workaround for this as we want to integrate Live captions feature in our app?

**To Reproduce**
1. Create a conversation  - Host user
2. 3 other users join the same conversation created by Host User
3. Host user leaves the conversation
4. The other 3 users are now not receiving the speech to text transcription. 

**Expected behavior**
The conversation should be continued even if the Host leaves for the multi-party calls.

**Comment by glharper** [comment]
@priyankblitzz Thanks for using Speech SDK, and writing this issue up. I understand your frustration with the current workflow, and we are working on allowing [Conversation Transcription](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-conversation-transcription?pivots=programming-language-javascript) to better accommodate this scenario. For now, you may have to create and manage the conversation host yourself and make all call users participants (with a "Host user" that's not the true conversation host). Would that work for your scenario?

**Comment by priyankblitzz** [comment]
Hi @glharper ,

Can you provide me some more ideas for this statement " make all call users participants (with a "Host user" that's not the true conversation host)"? Maybe a small code snippet?

**Comment by glharper** [comment]
@priyankblitzz 
OnCallStart: 
- create Conversation
- start conversation
- join as host (which is not assigned to any call user)
- add call participants to Conversation using joinConversationAsync
- give first user "designated participant" privileges, which means wiring all host privileges (muting, ejecting, locking) to the "designated participant" (in the normal workflow, you have to do this wiring as well, since lock/mute/remove APIs are on the Conversation object)

OnParticipantLeaving: 
- if number of participants is 1 (meaning just the behind-the-scenes host), end the call
- if the current "designated participant" is leaving, assign another user as the "designated participant"

That should get you going. Does that makes sense?
