### ISSUE TITLE
[Ingestion Client] Is there an easy way to get the template to run on a cheaper app service plan

### ISSUE THREAD

**Issue by Markyboy944** [Azure-Samples/cognitive-services-speech-sdk#1198]
I deployed the template . All 900+ lines of it. It's costing me £125 per month. I wondered if there was any advice on how to run it more cheaply , as this is just a POC. Azure wont let me downgrade the app service plan to "dev/test" so is there something in the template which causes things to go in the production "tier"? thanks in advance for any info

**Comment by pankopon** [comment]
Hi, is this a Speech SDK question? What is the template you mention and what is your use case? Please describe the issue in more detail, currently there is not enough information.

**Comment by Markyboy944** [comment]
Apologies for lack of clarity. Yes - the Batch ARM template here:

https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/ingestion/ingestion-client/Setup/ArmTemplateBatch.json

This is the one I've deployed. It works great, but it is costing about £125 per month to run. I am currently only wanting to use it as a poc, so I woder whether there are any thoughts on how to help reduce the cost, whilst maintaining the  core functionality of ingesting and converting

**Comment by pankopon** [comment]
@PanosPeriorellis @HenryvanderVegte Please advise. Also, if the sample is mainly C# and uses the Speech SDK API, it needs to be moved under a bindings specific folder `samples/csharp` (REST API samples would go under `samples/batch`).

**Comment by HenryvanderVegte** [comment]
Hi,

sorry for the late response!
Yes, in the ARM deployment we set the App Service Plan to "Elastic Premium" here
`        {
            "apiVersion": "2018-02-01",
            "type": "Microsoft.Web/serverfarms",
            "kind": "app",
            "name": "[variables('AppServicePlanName')]",
            "location": "[resourceGroup().location]",
            "properties": {},
            "dependsOn": [],
            "sku": {
                "name": "EP1"
            }
        },`

you can set it to consumption plan
`            "sku": {
                "name": "Y1"
            }`,
 
but it might be that your functions aren't triggered (which is why we set the plan to Elastic Premium by default) and you need to sync the triggers first, there's a small section in our guide regarding that (https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/ingestion/ingestion-client/Setup/guide.md / https://docs.microsoft.com/en-us/azure/azure-functions/functions-deployment-technologies#trigger-syncing)

**Comment by HenryvanderVegte** [comment]
No response from user, closing issue for now.
