### ISSUE TITLE
usage of  StopSpeakingAsync()

### ISSUE THREAD

**Issue by gauravG2021** [Azure-Samples/cognitive-services-speech-sdk#1202]
Once we call synthesizer->SpeakTextAsync(), then how do i free the resources?
is it complsory to call StopSpeakingAsync(), or calling reset() on synthesizer is sufficient.

In case calling reset() on synthesizer is sufficient, then what is the need of StopSpeakingAsync()

**Comment by pankopon** [comment]
Resources are freed when the synthesizer object is destroyed (manually or when it goes out of scope).
StopSpeakingAsync() does not free resources, it was introduced so that synthesis can be stopped/cancelled before it would naturally end. See https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/354 for background.
