### ISSUE TITLE
SPXERR_MIC_NOT_AVAILABLE

### ISSUE THREAD

**Issue by samkuls** [Azure-Samples/cognitive-services-speech-sdk#1246]
**Issue Details**
Created one api for speech to text using microphone. locally working but how to make this work on azure webapp.
i know azure webapp deploy code into vm and there microphone is not enabled . but i need some workaround.
Note: I have developed these api in .Net Core

**How To Reproduce**
Just make an API from below code in .Net core 

        [HttpGet]
        [Route("MicrophoneToSpeec")]
        public async Task<IActionResult> MicrophoneToSpeech(string language)
        {
            var subscription = _config.GetValue<string>("SubscriptionId");
            var location = _config.GetValue<string>("Region");
            var config = SpeechConfig.FromSubscription(subscription, location);
            config.SpeechRecognitionLanguage = string.IsNullOrWhiteSpace(language);

            // Creates a speech recognizer.
            using (var recognizer = new SpeechRecognizer(config))
            {
                Console.WriteLine("Say something...");
                var result = await recognizer.RecognizeOnceAsync();
                if (result.Reason == ResultReason.RecognizedSpeech)
                {
                    Console.WriteLine($"We recognized: {result.Text}");
                }

                return new JsonResult(result.Text});
            }
        }

**Expected behavior**
microphone should enable while application deployed on Azure

Note: I want to  expose this api  to our organization so that anyone can consume it and make stt through microphone .

**Comment by rhurey** [comment]
Ok, I think I have a clear picture now.

This code will run the recognition code on the server that's hosting the web app. In Azure, there isn't a microphone attached to the server. When it's run locally, there is a microphone so the method works as expected. (Presumably because you're sitting in front of the machine hosting the web app)

The key concept is some code running locally where the user and the microphone are is needed to capture the audio, for this there's 3 basic choices:

1. The Speech SDK can run locally, capture audio, and send it to the Speech Service.
2. If you can't install code locally, there's the JavaScript version of the SpeechSDK that can run in a browser.
3. You can run some code to capture audio and forward it to your WebApp.

If you want to run the recognition in a WebApp, you need to get the audio to the WebApp, somehow. You could capture it locally, send it to the WebApp, and get the response back. In this instance instead of using FromDefaultMicrophone, you'd use a PushStream. There's a PushStream sample [here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/6c69e3e4e35049b4eeb385c19527568299cba6a9/samples/csharp/sharedcontent/console/speech_recognition_samples.cs#L488). You'd want to replace the code that reads from a file with some code to read from the HTTP request to your webapp.

We don't have sample code for what the client side would need to do to capture audio and send it to your webapp.

**Comment by rhurey** [comment]
I'm closing this issue, but please let us know if there's any more information we can provide.
