### ISSUE TITLE
java.lang.UnsatisfiedLinkError: com.microsoft.cognitiveservices.speech.SpeechConfig.setTempDirectory(Ljava/lang/String;)V on docker CentOS-7 

### ISSUE THREAD

**Issue by leosam2048** [Azure-Samples/cognitive-services-speech-sdk#1324]
**Describe the bug**
Encountering an error when java codebase is deployed on a linux server but works well when deployed  in a mac PC.

**To Reproduce**

```
cat /etc/os-release


NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"


java -version


java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)

```
 

**Expected behavior**
Based on documentation. codebase should be compatible with CentOS 7 platform
see: https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-devices-sdk-quickstart?pivots=platform-linux

**Version of the Cognitive Services Speech SDK**
Which version of the SDK are you using: Client sdk 1.19.0

 <dependency>
            <groupId>com.microsoft.cognitiveservices.speech</groupId>
            <artifactId>client-sdk</artifactId>
            <version>1.19.0</version>
        </dependency>

Which version of the SDK are you using.

**Platform, Operating System, and Programming Language**
 
OS: CentOS version 7
Hardware - x86_64
Programming language: Java
Browser: N/A

**Additional context**

Please see following stacktrace:

```
java.lang.UnsatisfiedLinkError: com.microsoft.cognitiveservices.speech.SpeechConfig.setTempDirectory(Ljava/lang/String;)V
        at com.microsoft.cognitiveservices.speech.SpeechConfig.setTempDirectory(Native Method) ~[client-sdk-1.19.0.jar!/:?]
        at com.microsoft.cognitiveservices.speech.SpeechConfig.<clinit>(SpeechConfig.java:77) ~[client-sdk-1.19.0.jar!/:?]
        at com.fenbi.conan.zscaudio.server.tts.AzureTtsService.tts(AzureTtsService.java:64) ~[classes!/:?]
        at com.fenbi.conan.zscaudio.server.service.impl.TtsOrderServiceImpl.executeTts(TtsOrderServiceImpl.java:157) ~[classes!/:?]
        at com.fenbi.conan.zscaudio.server.service.impl.TtsOrderServiceImpl.lambda$executeTtsOrder$0(TtsOrderServiceImpl.java:114) ~[classes!/:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_202]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_202]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]

```

**Comment by BrianMouncer** [comment]
Prior to the 1.19.0 release, we built on Ubuntu 16.04, which meant having to upgrade compilers, c runtimes, and several system runtimes to use speech SDK on CentOS7 or RHEL7. Ubuntu 16.04 hit End of Life earlier this year, and building on our new 18.04 build agents meant CentOS7 has some new "old" system libraries that could no longer be easily upgraded by the user to make 18.04 binaries run on the older CentOS7 distributions. 

Since CentOS7 has a while before it also hits EOF, we added another set of binaries actually built on CentOS7 to our C++ and JAVA package to allow at least limited CentOS support in our 1.19.0 release. On the plus side, you should not have to upgrade as many system components on your docker image as before, but you do still need a newer versions of GCC than is available in YUM.

I suspect I need to update our instructions on updating CentOS7 system components, or there might be a bug in the logic I used to auto-detect CentOS7 and switch to the centos7 specific binaries in the JAVA package.  I am able to run our C++ and Java tests on CentOS7 manually and in our daily CiCd tests, so I suspect this is just a setup instruction problem. 

If you have not installed GCC from source code before, you might find these original CentOS7 setup instructions helpful.
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-configure-rhel-centos-7


If something is missing in the linked instructions above, I looked at the last docker file I used, and I YUM install a lot more packages... You probably do not need all of these, especially if you are not using GStreamer to locally transcode audio formats, but these would be a good starting point to find out what is missing.

        ca-certificates \
        make \
        alsa-lib \
        alsa-plugins-pulseaudio \
        gcc-c++ \
        make \
        libmpc \
        zlib-devel \
        openssl-devel \
        openssl \
        java-1.8.0-openjdk-devel \
        libuuid-devel \
        gstreamer1-devel \
        gstreamer1 \
        gstreamer1-plugins-base \
        gstreamer1-plugins-good \
        gstreamer1-plugins-bad-free \
        gstreamer1-plugins-bad-aac \
        gstreamer1-plugins-ugly-free \
        alsa-lib-devel \
        redhat-lsb-core

Then compiled and installed GCC 7.5 from source, and added it to CMAKE and the containers load library path variables.

          ENV CC /usr/local/bin/gcc
          ENV CXX /usr/local/bin/g++
          ENV LD_LIBRARY_PATH "/usr/local/lib64:${LD_LIBRARY_PATH}"

**Comment by BrianMouncer** [comment]
@leosam2048 
Please let me know the results of above.

Thanks,

**Comment by jhakulin** [comment]
@leosam2048 Could you please let us know if the instructions here: https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-configure-rhel-centos-7 helped to your problem? Thank you.

**Comment by jhakulin** [comment]
Possible duplicate to https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1352

**Comment by pankopon** [comment]
Closed since no customer update, presumed solved. Please open a new issue if more support is needed.
