### ISSUE TITLE
Microphone not being found on Raspberry Pi 4

### ISSUE THREAD

**Issue by J-Hardyy** [Azure-Samples/cognitive-services-speech-sdk#1346]
Hi,

I have published and deployed a small .NET console app onto my Raspberry Pi 4. The microphone I am using on the Raspberry Pi is the Respeaker 4 mic array. Using arecord -l on the Pi I can see the Microphone is under Card 3, Device 0. The code below throws the error:
SPXERR_MIC_NOT_AVAILABLE when setting up an audio config for a Keyword Recognizer.

`using AudioConfig audioConfig = AudioConfig.FromMicrophoneInput("hw:CARD=3,DEV=0");`

I have plugged a USB microphone into the Raspberry Pi 4 and the SDK finds the microphone no problem and the Keyword Recognizer works. Although it does throw the same error when using/creating an audio config for a Speech Recognizer.

Both microphones work perfectly in Audacity. So I know the microphones work. The console app I have tested on my Windows 10 laptop and it works using `AudioConfig.FromDefaultMicrophone`

Code snippet:

 ```
            Console.WriteLine($"Base Directory is: {directory}");
            string tablePath = Path.GetFullPath(Path.Combine(directory, "Items", ApplicationConstants.KeywordFileName));
            Console.WriteLine($"Table file Path: {tablePath}");
            var keyword = KeywordRecognitionModel.FromFile(tablePath);

            Console.WriteLine("Say Hey Alex");

            using AudioConfig audioConfig = AudioConfig.FromMicrophoneInput("hw:CARD=3,DEV=0");
            using var keywordRecognizer = new KeywordRecognizer(audioConfig);
            await keywordRecognizer.RecognizeOnceAsync(keyword);

            await PlayResponse(speechConfig, "Yes");

            Console.WriteLine("Speak into microphone");

            using AudioConfig audioConfig2 = AudioConfig.FromMicrophoneInput("hw:CARD=3,DEV=0");
            using var recognizer = new SpeechRecognizer(speechConfig, audioConfig2);
            var result = await recognizer.RecognizeOnceAsync();
```

Creating another AudioConfig was purely for debugging purposes.

So the Respeaker throws an exception at -> await keywordRecognizer.RecognizeOnceAsync(keyword);

The usb microphone throws an excpetion at -> var result = await recognizer.RecognizeOnceAsync();

Things I have doubled checked:
- Raspberry Pi is fully up to date
- .NET 6 is correctly installed.

Any help would be greatly appreciated.

**Comment by pankopon** [comment]
Hi, we don't have a mic array setup like yours so the following example is with a regular USB headset (Jabra UC VOICE 750). Please try the same with your USB microphone, replace the device parameter values with what you have.

Ensure that you are running a [supported Linux distribution](https://docs.microsoft.com/azure/cognitive-services/speech-service/speech-sdk?tabs=linux%2Cubuntu%2Cios-xcode%2Cmac-xcode%2Candroid-studio#get-the-speech-sdk) on RPi. In this example, **Ubuntu Server 20.04.3 LTS 64-bit** was used.

The output of `arecord -l`
```
**** List of CAPTURE Hardware Devices ****
card 1: USB [Jabra UC VOICE 750 MS USB], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```
and `arecord -L` (partial)
```
...
sysdefault:CARD=USB
    Jabra UC VOICE 750 MS USB, USB Audio
    Default Audio Device
...
hw:CARD=USB,DEV=0
    Jabra UC VOICE 750 MS USB, USB Audio
    Direct hardware device without any conversions
plughw:CARD=USB,DEV=0
    Jabra UC VOICE 750 MS USB, USB Audio
    Hardware device with all software conversions
```
(it's practically all the same since there's just 1 microphone + speakers)

Test recording in the Speech SDK default input format
```
arecord -D hw:USB,0 -f S16_LE -c1 -r16000 -t wav test.wav
```
and check the result with `aplay test.wav`

Next test with our C# console samples (https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/csharp):
- Download the samples (`git clone` for the samples repo, or just get the `samples/csharp` part).
- Modify [RecognitionWithMicrophoneAsync()](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/4f9ee79c2287a5a00dcd1a50112cd43694aa7286/samples/csharp/sharedcontent/console/speech_recognition_samples.cs#L21) and [ContinuousRecognitionWithKeywordSpottingAsync()](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/4f9ee79c2287a5a00dcd1a50112cd43694aa7286/samples/csharp/sharedcontent/console/speech_recognition_samples.cs#L596) to use `AudioConfig.FromMicrophoneInput("hw:CARD=USB,DEV=0")` plus your subscription key/region and keyword recognition model.
- Build and run the [console app](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/csharp/dotnetcore/console), the following menu options now use FromMicrophoneInput:
  ```
  1. Speech recognition with microphone input.
  7. Speech recognition with keyword spotting.
  ```
If this doesn't work for you even with a normal USB microphone, please post the complete output from both `arecord -l` and `arecord -L` as well as a [Speech SDK log](https://docs.microsoft.com/azure/cognitive-services/speech-service/how-to-use-logging) from the console samples above.

**Comment by J-Hardyy** [comment]
I have gotten it to work with the Sample code using a USB microphone. From there I changed the CARD=USB to CARD=seeed4micvoicec and this worked! I'm pretty sure I tried this before, but it must have been ever so slightly different. Thank you for the help, I really appreciate it.
