### ISSUE TITLE
Is there a way to get a "final result" of continuous recognition async?

### ISSUE THREAD

**Issue by adammpolak** [Azure-Samples/cognitive-services-speech-sdk#1392]
I am aware that continuous recognition async provides in-between results as the user is speaking.

Is there a way of getting a "final" output when stopping the recognition of everything that has been said?

(microphone client-side Javascript with sockets)

**Comment by dargilco** [comment]
Hi @adammpolak, this is Darren from the Speech SDK team. Thank you for your question. If you stop recognition before the final results, you will not get the "final result" event (e.g. "Recognized" event in C#). You will need to store the latest intermediate result (e.g. from the "Recognizing" event in C#) and treat that as your final result. 
Can you describe your scenario that requires you to support stopping recognition before a final result, but yet still need a result to process or display?
Thanks,
Darren

**Comment by dargilco** [comment]
@adammpolak I'm closing the issue since it was answered and I have not heard back from you. Feel free however to reply anytime and tag me. 
Darren

**Comment by dargilco** [comment]
@adammpolak I'm correcting what I wrote above (now deleted). Per my reply in https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1388 :

We always send a final result ("Recognized" event) based on whatever audio received by the time StopContinuousRecognitionAsync was called. So if you're in the middle of saying "this is a test" you may get "This is." as a final recognition result ("recognized" event) if you called Stop in the middle of the sentence.

The Recognized event will give you recognition results since the previous Recognized event (not since your started continuous recognition). In continuous recognition, you will get multiple Recognized events, after each pause in the audio (after each sentence).

Closing the issue. Feel free to reply here and tag me for any follow up questions, or open a new issue as needed. Thanks!
