### ISSUE TITLE
How to get phoneme of TTS.

### ISSUE THREAD

**Issue by mudong0419** [Azure-Samples/cognitive-services-speech-sdk#1394]
Hello, when I'am synthesizing a speech with a text, is it possible to get phonemes of the text? Thanks in advance.

**Comment by jhakulin** [comment]
@yulin-li Could you please comment on this ?

**Comment by dargilco** [comment]
@jhakulin let me try to answer, since I think @yulin-li is on vacation for the Chinese New Year. Yulin please correct me if I'm wrong.

@mudong0419 can you tell us about your scenario? Do you need phonetic transcription of the text-to-speech audio (phonemes and their start and stop time stamps?) What will these phonemes be used form? Also what is your programming language and operating system? I will assume C#, but it's similar for other programming languages: We have [Viseme output](https://docs.microsoft.com/azure/cognitive-services/speech-service/how-to-speech-synthesis-viseme?pivots=programming-language-csharp) as part of text-to-speech (see sample named SynthesisVisemeEventAsync() in file [speech_synthesis_sample.cs](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/csharp/sharedcontent/console/speech_synthesis_samples.cs). Visemes are used to synchronize the text-to-speech audio with face animation. But we don't have phoneme output as part of text-to-speech.
You can however get phonetic transcription as part of our Speech Recognition service. See [this GitHub issue](https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1284).
So one possible solution is the send the text-to-speech audio to the Speech Recognition service.
Darren.

**Comment by yulin-li** [comment]
Thanks @dargilco !! As Darren said, we don't have phoneme output in text-to-speech service. @mudong0419 could you explain more about your scenario? For lip sync or face animation, the [Viseme output](https://docs.microsoft.com/azure/cognitive-services/speech-service/how-to-speech-synthesis-viseme?pivots=programming-language-csharp) is the best choice.

**Comment by mudong0419** [comment]
Sorry for replying too late, since I was on vacation for the Chinese New Year. We are trying to synthesis a video give a text and an avatar, to make the face animation more nature, we wish to get the phonemes of text. Especially our texts are always Chinese-English code-switched, and if the English phoneme is [CMU phoneme set](http://www.speech.cs.cmu.edu/cgi-bin/cmudict?in=muesli&stress=-s) and Chinese phoneme is pinyin with tone(e.g. 中国 zhong1 guo2) will help us a lot. Thanks a lot.

**Comment by yulin-li** [comment]
@[mudong0419 Happy Chinese New Year! Unfortunately we cannot provide phonemes. But we do have visemes events both for en and zh. You can map our viseme ids to your animation in your system.
Meanwhile, we are dogfooding some new technology for 3D avatar and we have some nice demos. You can email to me (yulili@microsoft.com) and our PM Melinda <melindam@microsoft.com> for details if you are interested

**Comment by mudong0419** [comment]
@yulin-li Thanks for your reply, and happy Chinese New Year! I'm very interested in your demos, and will send you an email.
