### ISSUE TITLE
text-to-speech Unable to use on the Centeros7

### ISSUE THREAD

**Issue by hu1240050829** [Azure-Samples/cognitive-services-speech-sdk#1406]
develop on mac, everything is normal; 
But Deploy to the Center os7, Application not responding;
I use java to develop, import Gradle; Has been run
`
sudo yum update
sudo yum groupinstall "Development tools"
sudo yum install alsa-lib openssl wget
` 
I don't know what the problem is, is there any other action needed?

**Comment by BrianMouncer** [comment]
CentOS7 will reach End Of Life soon.
In the past, you could get the speech sdk built on newer Ubuntu images to work on centos7 by [updating GCC, C runtimes, and some other packages by compiling them from source](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-configure-rhel-centos-7).

If this is for a new development project, I would highly suggest using CentOS8 or 9, rather than jumping through hurdles to get CentOS7 to work.

**Comment by hu1240050829** [comment]
> CentOS7 will reach End Of Life soon. In the past, you could get the speech sdk built on newer Ubuntu images to work on centos7 by [updating GCC, C runtimes, and some other packages by compiling them from source](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-configure-rhel-centos-7).
> 
> If this is for a new development project, I would highly suggest using CentOS8 or 9, rather than jumping through hurdles to get CentOS7 to work.
I see “Environment settings” inside 
“export LD_LIBRARY_PATH=/path/to/extracted/SpeechSDK-Linux-<version>/lib/x64:$LD_LIBRARY_PATH”
Excuse me, where can I download “SpeechSDK-Linux-<version>” ?

**Comment by BrianMouncer** [comment]
@hu1240050829 

It is part of the nuget package,, but it can also be downloaded directly from https://aka.ms/csspeech/linuxbinary
