### ISSUE TITLE
Error code: 1007. Error details: Unsupported audio format.

### ISSUE THREAD

**Issue by amand26** [Azure-Samples/cognitive-services-speech-sdk#1432]
**Describe the bug**

Transcribing audios using Azure Speech To Text SDK in python. For one audio getting the transcription correctly, while for the other getting the error **Speech Recognition canceled: CancellationReason.Error Error details: Connection was closed by the remote host. Error code: 1007. Error details: Unsupported audio format.**

audio1.wav - Getting the correct transcription
audio2.wav - Geting the above error

[files.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/8190602/files.zip)

**Comment by ralph-msft** [comment]
Thanks for using the Cognitive Services Speech SDK.

Unfortunately audio2.wav doesn't have a valid WAVE file header which is why you are getting the cancellation event above. To be specific, the BlockAlign value is incorrectly set to 4 (it should be).

In audio1.wav the BlockAlign is correctly set to 2 in which is why it works.
The reason you are getting that cancellation event from the recognizer is that the WAV/RIFF header in audio2.wav is incorrect/unsupported. Specifically, it specifies a BlockAlign of 4. The expected value in your case should be 2 for that file. For your reference, the BlockAlign header is set as follows:
```
BlockAlign = (Bits_per_sample * num_channels) / 8
           = (16 * 1) / 8
           = 2
```
In audio1.wav the BlockAlign in the WAV/RIFF header is correctly set to 2 which is why it works. For your reference, here are the first 44 bytes of both audio files with the BlockAlign section of the header highlighted:
![image](https://user-images.githubusercontent.com/18542438/157396487-36239d2d-d58f-4dbf-9d4b-c5e9f03e5665.png)

Ideally, you'd want to use well formatted and valid WAVE files.

However, if you know the sampling rate, bits per sample, and number of channels upfront, you can work around the invalid header using a [`PullAudioInputStreamCallback`](https://docs.microsoft.com/azure/cognitive-services/speech-service/how-to-use-audio-input-streams). The idea is to manually specify the PCM format, skip over the invalid header bytes, and then start reading the PCM audio samples from there. Here is some super simplified code that allows you to get recognitions from your audio2.wav:
```python
subsKey = "your_subscription_key"
subsRegion = "your_region e.g. westus"
audioFile = "audio2.wav"

import azure.cognitiveservices.speech as speechsdk

# Custom pull audio input stream input callback that skips over standard WAVE file headers
class SkipRiffHeaderAudioStream(speechsdk.audio.PullAudioInputStreamCallback):
    def __init__(self, filename: str):
        super().__init__()
        self._file = open(filename, "rb")
        # Standard WAVE RIFF headers are 44 bytes in size so seek ahead to skip over the header bytes
        self._file.seek(44)
    
    def read(self, buffer: memoryview) -> int:
        size = buffer.nbytes
        frames = self._file.read(size)
        buffer[:len(frames)] = frames
        return len(frames)

    def close(self) -> None:
        self._file.close()

def recognize_with_bad_header():
    # create and configure your SpeechConfig as usual
    speech_config = speechsdk.SpeechConfig(subscription=subsKey, region=subsRegion)
    speech_config.speech_recognition_language = "en-US"

    # create an AudioConfig that uses your custom pull input stream callback implementation
    # to skip over invalid header bytes
    audio_format = speechsdk.audio.AudioStreamFormat(8000, 16, 1) # assumes your file is 8000Khz 16 bit mono audio
    pull_stream_callback = SkipRiffHeaderAudioStream(audioFile)
    pull_stream = speechsdk.audio.PullAudioInputStream(stream_format=audio_format, pull_stream_callback=pull_stream_callback)
    audio_config = speechsdk.AudioConfig(stream=pull_stream)

    # create your SpeechRecognizer as usual
    speech_recognizer = speechsdk.SpeechRecognizer(speech_config, audio_config)
    
    # get your recognition
    result = speech_recognizer.recognize_once_async().get()
    
    if result.reason == speechsdk.ResultReason.RecognizedSpeech:
        print("Recognized: {}".format(result.text))
    elif result.reason == speechsdk.ResultReason.NoMatch:
        print("No speech could be recognized: {}".format(result.no_match_details))
    elif result.reason == speechsdk.ResultReason.Canceled:
        cancellation_details = result.cancellation_details
        print("Speech Recognition canceled: {}".format(cancellation_details.reason))
        if cancellation_details.reason == speechsdk.CancellationReason.Error:
            print("Error details: {}".format(cancellation_details.error_details))

recognize_with_bad_header()
```

**Comment by amand26** [comment]
Hi @ralph-msft , Thanks for responding to this quickly. I am able to get the transcription now. One quick question, Shouldn't there be a functionality where, if the header is corrupt, it automatically figure out the required metadata from the audio itself?

**Comment by ralph-msft** [comment]
Automatically correcting for corrupted header is not possible. In WAVE files, the header itself is what contains the following information:
* Sampling rate
* bits per sample
* number of channels
* endianness of audio samples
* format of the audio samples

If the header is corrupt, there is no way to definitively know what information is correct. For example, in audio2.wave we could just have easily assumed the audio samples were captured at 16khz, 16 bits per samples, mono. Or 8Khz, 16 bits per sample, stereo. Or 16KHz, 8 bits per sample, mono. Or so on. It wouldn't make sense computationally to try all possible combinations when doing speech recognitions. And is some cases, we can't even tell if the audio header is invalid if all the data in it makes sense, but the audio samples don't match.

Ultimately, it is your responsibility as the end user to ensure that any provided audio is valid.

I am marking this issue as resolved for now. If you have any more questions, or run into any other issues please feel free to either re-open this, or create a new issue.
