### ISSUE TITLE
`fromDefaultMicrophoneInput` vs `createMicrophoneStream`

### ISSUE THREAD

**Issue by rhalaly** [Azure-Samples/cognitive-services-speech-sdk#1471]
https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/74c104ab5b102c8d41270f1569fe2ea88b5cbf78/samples/java/android/sdkdemo/app/src/main/java/com/microsoft/cognitiveservices/speech/samples/sdkdemo/MainActivity.java#L153-L154

What is the reason you wrote your own `createMicrophoneStream` instead of using `fromDefaultMicrophoneInput`?

You just comment the `AudioConfig.fromDefaultMicrophoneInput()` out without any explenation

**Comment by pankopon** [comment]
Hi, thank you for pointing this out, looks like these lines have been there for years.

You need to use `fromStreamInput` if you want to use an external microphone or BT mic (that couldn't be otherwise used) or mix audio from some other source to microphone audio, for example.

With just the system default microphone, it's enough to use `fromDefaultMicrophoneInput` or omit the audio config altogether, like done in the [Android Java quickstart with microphone input](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/quickstart/java/android/from-microphone/app/src/main/java/com/microsoft/cognitiveservices/speech/samples/quickstart/MainActivity.java).

We'll add clarifying comments to the sample.

**Comment by pankopon** [comment]
Internal work item ref. 4199167.

**Comment by rhalaly** [comment]
`fromDefaultMicrophoneInput` doesn't work for me for some reason (permissions I guess). The `createMicrophoneStream` worked. 

So, I wasn't sure why you just commented on that line. Thanks for the explanation.
