### ISSUE TITLE
CrisModelId

### ISSUE THREAD

**Issue by mibuso** [Azure-Samples/cognitive-services-speech-sdk#15]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>Hello! 
I try to start example from SpeechToText-WPF folder.
It has several settings and one setting called CrisModelId. This value assigned to customRecognizer.DeploymentId .
What is it? And where I can find it?
I tried to find it in jsons from resources.azure.com but I couldn't.

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 10 pro

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by zhouwangzw** [comment]
CrisModelId is the deploymentId (or endpoint id) when you use a [customized model for speech ](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-customize-speech-models) recognition. If you only use base model (without customization), you do not need to provide this.

Regarding the sample, you can "change recognition type" to "baseline model", so that you do not need to provide "CRIS Model ID". 

We will update the UI and document to provide clearer instructions.

Thanks for your feedback.

**Comment by zhouwangzw** [comment]
SpeechRecognitionResult.RecognitionFailureReason give you more details on error.

**Comment by wolfma61** [comment]
closing ....
