### ISSUE TITLE
SPXERR_FILE_OPEN_FAILED error in android studio

### ISSUE THREAD

**Issue by lichao252244354** [Azure-Samples/cognitive-services-speech-sdk#1533]
Hello when I use android C++ library  
An error occurred：2022-06-15 18:43:05.830 27867-27867/com.example.myapplication E/libc++abi: terminating with uncaught exception of type std::runtime_error: Exception with an error code: 0x8 (SPXERR_FILE_OPEN_FAILED)，Is the recognized audio file to be placed on the mobile phone? I am now putting the audio files on the PC ，thank you very much

**Comment by pankopon** [comment]
Hi, so you are using audio files as input for the speech recognizer? If yes then the file(s) need to be located and accessible on the device where your application runs. Note that depending on the Android version, direct access to external storage from an application may be restricted - see https://developer.android.com/about/versions/11/privacy/storage for details.

**Comment by lichao252244354** [comment]
thank you ,I set the device read and write file permissions,no more errors，But I found no recognition result， I checked the log,the cancel realse CANCELED: ErrorDetails Connection failed (no connection to the remote host). Internal error: 1. Error details: Failed with error: WS_OPEN_ERROR_UNDERLYING_IO_OPEN_FAILED [0x80000001 | -1] ,Error Code is 1 ,An authentication error occurs if subscription key or authorization token is invalid, expired,my SubscriptionKey is “41f33953c38f44759c0eec97c8649362” ，ServiceRegion = "southeastasia";

**Comment by lichao252244354** [comment]
cloud you help me see the  SubscriptionKey  and ServiceRegion  has expired？

**Comment by pankopon** [comment]
@lichao252244354 Hi, I edited your message to hide your subscription key - you should not post it in public, otherwise anyone can grab and use it.

We cannot check individual users' keys, but please login to https://portal.azure.com/ and check
- Subscriptions: Is your subscription still active?
- Resources: Have you created a Speech services resource, is it still enabled and the key not expired?

What features is your application trying to use, just basic speech recognition or more? Some advanced functionality may not be available with a free subscription if you have one.

Can you try and run some very simple speech recognition quickstart on your PC, for example
https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/cpp/windows/from-microphone
(or a similar one under https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart)
and check if it works with your current subscription key and service region? If it doesn't then you will need a new subscription key.

**Comment by lichao252244354** [comment]
HI ， I can run on a PC, but the same code will have authentication errors on Android Phones，the ErrorLog :CANCELED: ErrorDetails Connection failed (no connection to the remote host). Internal error: 1. Error details: Failed with error: WS_OPEN_ERROR_UNDERLYING_IO_OPEN_FAILED [0x80000001 | -1]
    wss://southeastasia.stt.speech.microsoft.com/speech/recognition/interactive/cognitiveservices/v1?language=en-US
    X-ConnectionId: 562c8b022c684ded9f33b5c55929e21b SessionId: 562c8b022c684ded9f33b5c55929e21b ,cloud you help check this  connection error  ,thank you very much ,

**Comment by pankopon** [comment]
Does your Android application have android.permission.INTERNET?

Can you run this Android quickstart
https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/java/android/from-microphone
on your phone? It's all Java but has all the required permission settings, so you can verify the connection as long as your subscription is valid.

**Comment by pankopon** [comment]
Closing this since the original issue with files was resolved and there's now a new item about connection specific errors. (Previous suggestions for troubleshooting still apply.)
