### ISSUE TITLE
CPP Text-To-Speech quickstart doesnot work on Chinese

### ISSUE THREAD

**Issue by cuijiaxu** [Azure-Samples/cognitive-services-speech-sdk#1603]
**Describe the bug**
CPP Text-To-Speech quickstart doesnot work on Chinese
when I input an english sentence, it runs well. But crash down when input a chinese sentence.

**To Reproduce**

`
auto language = "zh-CN";
config->SetSpeechSynthesisLanguage(language);
auto synthesizer = SpeechSynthesizer::FromConfig(config);`

**Expected behavior**
![image](https://user-images.githubusercontent.com/15241705/182129325-f65c64e3-bc3d-4c34-ae24-c8a947b2226e.png)

`Exception with an error code: 0x21 (SPXERR_INVALID_HANDLE)
[CALL STACK BEGIN]

    > GetModuleObject

    - push_audio_input_stream_set_property_by_name

    - synth_result_get_result_id

    - Microsoft::CognitiveServices::Speech::SpeechSynthesisResult::SpeechSynthesisResult

    - std::_Construct_in_place<Microsoft::CognitiveServices::Speech::SpeechSynthesisResult,_azac_empty * &>

    - std::_Ref_count_obj2<Microsoft::CognitiveServices::Speech::SpeechSynthesisResult>::_Ref_count_obj2<Microsoft::CognitiveServices::Speech::SpeechSynthesisResult><_azac_empty * &>

    - std::make_shared<Microsoft::CognitiveServices::Speech::SpeechSynthesisResult,_azac_empty * &>

    - <lambda_895efbafc16341ac5a45d806b074b406>::operator()

    - std::invoke<<lambda_895efbafc16341ac5a45d806b074b406> >

    - std::_Invoke_stored_explicit<<lambda_895efbafc16341ac5a45d806b074b406>,0>

    - std::_Invoke_stored<<lambda_895efbafc16341ac5a45d806b074b406> >

    - std::_Fake_no_copy_callable_adapter<<lambda_895efbafc16341ac5a45d806b074b406> >::operator()

    - std::invoke<std::_Fake_no_copy_callable_adapter<<lambda_895efbafc16341ac5a45d806b074b406> > &>

    - std::_Invoker_ret<std::shared_ptr<Microsoft::CognitiveServices::Speech::SpeechSynthesisResult>,0>::_Call<std::_Fake_no_copy_callable_adapter<<lambda_895efbafc16341ac5a45d806b074b406> > &>

    - std::_Func_impl_no_alloc<std::_Fake_no_copy_callable_adapter<<lambda_895efbafc16341ac5a45d806b074b406> >,std::shared_ptr<Microsoft::CognitiveServices::Speech::SpeechSynthesisResult> >::_Do_call

    - std::_Func_class<std::shared_ptr<Microsoft::CognitiveServices::Speech::SpeechSynthesisResult> >::operator()`

**Version of the Cognitive Services Speech SDK**
Microsoft.CognitiveServices.Speech  1.23.0

**Platform, Operating System, and Programming Language**
 - OS: Windows
 - Hardware - x64
 - Programming language: C++

**Comment by rhurey** [comment]
Thanks for this report. There are a few things going on here to discuss.

First off, the root cause of the problem is that the string format coming from the console isn't capturing the non-ascii characters properly. The (quickest) solution for that would be to use the std::wstring overloads for SpeakTextAsync to ensure properly encoded strings are passed in. (Alternately, the std::string overload will work with a UTF-8 encoded string)

Later on the Speech SDK internally hits an error due to the string encoding not being what was expected, and doesn't return an overly useful error. I've opened a bug in our internal tracking system to address that.

Thanks again.

**Comment by cuijiaxu** [comment]
Thanks! Got it.
