### ISSUE TITLE
[JS] can I get the audio file in Real-time Speech-to-Text?

### ISSUE THREAD

**Issue by Aethey** [Azure-Samples/cognitive-services-speech-sdk#1687]
i am looking for a way to get the audio file when i use 
`SpeechSDK.AudioConfig.fromDefaultMicrophoneInput()`
,but all most answers said it should be 
`SpeechSDK.AudioConfig.fromStreamInput(pushStream)`

so the `fromStreamInput` is only way in JS?
and in this official page.the **Realtime Speech-to-Text** use it too?
<img width="1362" alt="demo1" src="https://user-images.githubusercontent.com/17793203/195052380-1ec25eb2-aee2-4199-83de-4cbe5ab80cf2.png">

**Comment by rhurey** [comment]
Speech Studio should let you record from the microphone and download the wav file.

If you're using the SDK directly you could enable audio logging (off by default) on the SpeechConfig object and then use this REST API to retrieve the audio:
https://{region}.dev.cognitive.microsoft.com/docs/services/speech-to-text-api-v3-0/operations/GetBaseModelLogs

**Comment by Aethey** [comment]
> Speech Studio should let you record from the microphone and download the wav file.
> 
> If you're using the SDK directly you could enable audio logging (off by default) on the SpeechConfig object and then use this REST API to retrieve the audio: https://{region}.dev.cognitive.microsoft.com/docs/services/speech-to-text-api-v3-0/operations/GetBaseModelLogs

Thank you for your reply,and i got the log.but it is a list,and in this doc
[https://eastus.dev.cognitive.microsoft.com/docs/services/speech-to-text-api-v3-0/operations/GetEndpointLog](url)
i should give the **logId** but i can't find a way to get it...
```
there is a resultId,but not logId

**Comment by pankopon** [comment]
@Aethey See https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1742.

**Comment by Aethey** [comment]
> @Aethey See #1742.

Thank you，
but this answer is about **Get Custom Model Endpoint Logs**,not **Get Custom Model Endpoint Log**,if i want to get a file not a list, i need a **logId**,but how to get the **logId**。

**Comment by pankopon** [comment]
@Aethey In 1742 it was asked
> Could you tell how can I get the specific audio's **logid** that I want .

but if this indeed does not match your question then @mahilleb-msft to the rescue.

**Comment by pankopon** [comment]
@andreasjl @mahilleb-msft Please advise.

**Comment by pankopon** [comment]
Since there is apparently not going to be any further advice on this question, my take is that based on https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1742#issuecomment-1319835713 (highlight added)

> you can enumerate custom models endpoints logs through [Get Custom Model Endpoint Logs](https://westus.dev.cognitive.microsoft.com/docs/services/speech-to-text-api-v3-0/operations/GetEndpointLogs), **check .values[].self on the result.**

you need to select one value of `.values[].self` from [GetEndpointLogs](https://westus.dev.cognitive.microsoft.com/docs/services/speech-to-text-api-v3-0/operations/GetEndpointLogs) response and use that as the value of `logId` for [GetEndpointLog](https://westus.dev.cognitive.microsoft.com/docs/services/speech-to-text-api-v3-0/operations/GetEndpointLog). (If it's really like that, obviously the API could be better described.) Of course, if there are several audio files then you need to "know" which one you want - maybe based on `name`, `kind` and/or `createdDateTime` - or just download them all.

**Comment by pankopon** [comment]
Closed as answered. Please create a new issue if more support is needed.
