### ISSUE TITLE
Continuous speech

### ISSUE THREAD

**Issue by louloubo** [Azure-Samples/cognitive-services-speech-sdk#169]
Is it possible for continuous_speech_recognition (cognitive-services-speech-sdk/samples/python/console/speech_sample.py in function :  def speech_recognize_continuous_from_file()) to keep the text in a variable in the same way that we could do for recognize_once "result = speech_recognizer.recognize_once()" and to print the whole text?
I'm using Python 3.7 on Windows 64.
Thanks for help

**Comment by chlandsi** [comment]
You can save the result to a variable in an outside scope inside a callback for the `recognized` event:

```
all_results = []
def handle_final_result(evt):
    all_results.append(evt.result.text)

speech_recognizer.recognized.connect(handle_final_result)
speech_recognizer.start_continuous_recognition()
# etc.
```

**Comment by louloubo** [comment]
Thanks!!!
Where should I put it exactly in the code ? (Sorry I'm new in Python...)
and what command should I do to obtain the results?

**Comment by chlandsi** [comment]
In the example (speech_recognize_continuous_from_file), add it to the place where the other callbacks are defined (around [here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/258949599ec32c8a7b03fb38a53f2033010b6b26/samples/python/console/speech_sample.py#L203)). After a few utterances have been recognized, the `all results` variable will contain the transcriptions. You can print them simply like `print(all_results)`.

**Comment by arielcedola** [comment]
Hi @chlandsi ! When doing continuous recognition from micropohone (not from file), in which conditions the stopped session event is fired by the recognizer? Automatically after recognizing a few utterances? Only after executing speech_recognizer.stop_continuous_recognition() in the script? Or in both cases?
In the example of speech_recognize_continuous_from_file it seems that the session is stopped by the recognizer (tell me if I'm wrong), probably because the end of the audio file is easily detected. But I think that in the case of recognizing from mic it's different. Could you explain? Thanks a lot!

**Comment by zhouwangzw** [comment]
In continuous recognition, the session stopped event is only fired after the stop_continuous_recognition() is called. For microphone input, if the app knows when the microphone input is completed, it can call stop_continuous_recognition() to stop the session. For example, a button like "Stop speaking" could trigger such an event. Of course there are other ways depending on application scenarios.

Thanks,
Zhou

**Comment by arielcedola** [comment]
Perfect Zhou, thanks a lot! In fact in my application of continuous recognition from mic I tested both, triggering the stop session event after a certain time in seconds and upon pressing a key. 

I still have a doubt regarding the session stopped event in the example [speech_recognize_continuous_from_file()](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/258949599ec32c8a7b03fb38a53f2033010b6b26/samples/python/console/speech_sample.py#L185). The call to `stop_continuous_recognition()` is made inside the callback function `stop_cb(evt)`, which as far as I understand is called once received the session stopped event through the line `speech_recognizer.session_stopped.connect(stop_cb)`, this means, after `stop_continuous_recognition()` is called. What am I missing? Thanks again!

**Comment by chlandsi** [comment]
In that sample, the `stop_cb` callback function is triggered in response to a `canceled` event, which the service sends at the end of the stream from the file. `stop_continuous_recognition` is then called inside the callback to close the connection. Calling it again the callback for the `session_stopped` event is a no-op in that case.

**Comment by arielcedola** [comment]
That explains everything, thank you so much @chlandsi and @zhouwangzw.

**Comment by madkote** [comment]
@chlandsi Question to `speech_recognizer.start_continuous_recognition()` - does it run in thread or event loop? thx!

**Comment by chlandsi** [comment]
@madkote Continuous recognition runs in a native thread.

**Comment by yashugupta786** [comment]
I have created  a program in python for continuous  speech to text from microphone for real time . The problem is when there are multiple speaker (foreg   skype ,Zoom conference meeting ).The program only taking audio from my microphone .I want to capture audio of all users in the meeting and want to perform speech to text translation  .how to achieve that in python
