### ISSUE TITLE
Voice listing stopped working today.

### ISSUE THREAD

**Issue by Tukurai** [Azure-Samples/cognitive-services-speech-sdk#1693]
Today the synthesizer.GetVoicesAsync() stopped working for an application I've been running unchanged for half a year now. I'm still able to get a list of voices using curl. 

Has something changed?

**Comment by trrwilson** [comment]
If you happen to be running on Windows 10 or Windows 11, this may be another manifestation of an active issue: #1692 

Long story short, a security patch for Windows on Tuesday changed the way that network security behaves and it's caused failures across a range of Microsoft and non-Microsoft services -- the text-to-speech service is impacted. Workarounds exist (including rolling back the hotfix or forcing TLS 1.2 use) but the Windows team is working on a change to undo the root cause of the problem.

Now, that's speculation based on the timing and scenario -- if you're not using Windows then this wouldn't be the issue, and it's of course quite possible it's something else entirely. If you can share a log file with us, we can take a further look: https://learn.microsoft.com/azure/cognitive-services/speech-service/how-to-use-logging

Thank you!

**Comment by Tukurai** [comment]
Its is actually the problem you described. Rolling back the patch solved the issues for the user of the application.
