### ISSUE TITLE
[LINUX SDK Java] Openssl 3 compatibility

### ISSUE THREAD

**Issue by aberthout** [Azure-Samples/cognitive-services-speech-sdk#1747]
Hello, 

Is there soon to be an integration of version 3 of OpenSSL ? We use the ASR with the Java SDK inside a Docker container with OS Ubuntu 22.04 and the library libssl1.1_1.1.1f-1ubuntu2.16_amd64.deb. But as you know new vulnerabilities about OpenSSL arrived since the end of October. Unless building yourself the latest version from sources (https://github.com/openssl/openssl/releases/tag/OpenSSL_1_1_1s) it is impossible to have it. Ubuntu 22.04 (Jammy version) registry provides only OpenSSL 3 with fix vulnerabilities of course.

My other worry is the end of the support OpenSSL 1.1.1 after 2023 (https://www.openssl.org/policies/releasestrat.html). This confirms my question with OpenSSL 3.

Thanks :)

**Comment by pankopon** [comment]
Hi, we have a work item on the backlog to support OpenSSL 3.x but no ETA yet. We should have a plan for it before OpenSSL 1.x is discontinued. (@jhakulin)

**Comment by pankopon** [comment]
Internal work item ref. 4254856.

**Comment by Tenzer** [comment]
Debian 12 is now released and it no longer comes with OpenSSL 3. Any progress on this so we can upgrade the operating system?

**Comment by pankopon** [comment]
@Tenzer The compatibility is still in the works, but you can install the latest OpenSSL 1.x from sources and use Speech SDK applications with that. I just verified the following setup on Debian 12:
```
sudo apt-get install build-essential ca-certificates libasound2 wget
wget -O - https://www.openssl.org/source/openssl-1.1.1u.tar.gz | tar zxf -
cd openssl-1.1.1u
./config --prefix=/usr/local
make -j $(nproc)
sudo make install_sw install_ssldirs
sudo ldconfig -v
export SSL_CERT_DIR=/etc/ssl/certs
```

The last line to set SSL_CERT_DIR is critical (it must be in effect systemwide or at least in the console where the app is launched from), otherwise OpenSSL 1.x installed in `/usr/local` won't find certificates.

(In the future, please open a new issue if the original has been already closed - I only noticed your question here by accident.)

**Comment by niklaskorz** [comment]
OpenSSL 1.x will reach EOL in less than a month. Starting September 11 2023, installing it from source is not a sensible solution anymore.

**Comment by Baklap4** [comment]
Linking issue: https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/2048 since all other issues are closed.
