### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by eduardoagr** [Azure-Samples/cognitive-services-speech-sdk#1761]
I wanted to know if there is a way to track the percentage of the SpeexhRecognition from a wav.

For example, I am using WPF and would like to put a progress bar, but I know internet speed would be an issue. Is there a way a accomplish this? also, it will  depend of the length of the wav

**Comment by pankopon** [comment]
Hi, you can do this by tracking `OffsetInTicks` and `Duration` properties of `RecognitionResult` (see https://learn.microsoft.com/dotnet/api/microsoft.cognitiveservices.speech.recognitionresult?view=azure-dotnet).

`OffsetInTicks` tells the offset of recognized speech, measured from the beginning of audio input (when you started recognition), and `Duration` is the duration of the recognized speech segment. So when you add the offset and duration together, you get the duration of processed audio so far which you can compare to the total duration of input (if known in advance). Please note that you need to read the length of an input file in your app by some other means, the Speech SDK does not have methods for that.

Example:
```
speechRecognizer.Recognized += (sender, e) =>
{
    Console.WriteLine($"Offset {e.Result.OffsetInTicks}, duration {e.Result.Duration}");
    var processedDurationMs = e.Result.OffsetInTicks / 10000.0 /* to milliseconds */ + e.Result.Duration.TotalMilliseconds;
    var currentProgress = processedDurationMs / totalDurationMs; /* 0.0...1.0 */
    Console.WriteLine($"Progress {currentProgress.ToString("P", CultureInfo.InvariantCulture)}");
```

Because a file does not necessarily contain speech to the very end, the final progress after all `Recognized` events may be less than 100%, therefore you should update your progress indicator to 100% at the end of input (e.g. on `SessionStopped`).
