### ISSUE TITLE
Orange Pi Zero LTS / ARM32 Python support?

### ISSUE THREAD

**Issue by bbence84** [Azure-Samples/cognitive-services-speech-sdk#1785]
Not sure if I understood what I read here and there, but is ARM32 still not supported for the Python package? I would like to use the SDK on an ARM32 board, the Orange Pi Zero LTS.
Are there any plans?

Getting the following errors when trying to install the package via pip:
ERROR: Could not find a version that satisfies the requirement azure-cognitiveservices-speech (from versions: none)
ERROR: No matching distribution found for azure-cognitiveservices-speech

**Comment by pankopon** [comment]
Hi, Python is supported on Linux ARM64 but not ARM32, see
https://learn.microsoft.com/azure/cognitive-services/speech-service/quickstarts/setup-platform?tabs=linux%2Cubuntu%2Cdotnet%2Candroid%2Cmaven%2Cnodejs%2Cmac%2Cpypi&pivots=programming-language-python
At the moment there are no plans for ARM32 support. Is your board ARM32-only and cannot run 64-bit?

**Comment by bbence84** [comment]
Thanks! Unfortunately that device is ARM32 only: 
http://www.orangepi.org/html/hardWare/computerAndMicrocontrollers/details/Orange-Pi-Zero-LTS.html
It's a device that has low power requirements, hence my choice. I was wondering if e.g. the TTS and STT packages have any dependencies that are ARM64 only.

**Comment by pankopon** [comment]
All Speech SDK flavors except JavaScript are based on native C++ libraries, the pure Python part is just a bindings layer.
You can see this on a system where the Speech SDK Python package is installed, with command
```
pip show azure-cognitiveservices-speech
```
and then go to Location from above + `azure/cognitiveservices/speech`, you'll find several native library files (`.so` or `.dll` or `.dylib`).
That's why even the Python packages are platform specific. The currently available packages are listed in https://pypi.org/project/azure-cognitiveservices-speech/#files

We can create a backlog item for Python support on Linux ARM32 in the future, though, there hasn't been much demand so far. The only current 32-bit package is for Windows x86.

**Comment by pankopon** [comment]
Internal work item ref. 4776990.

**Comment by pankopon** [comment]
Closing the issue as we now have a work item on the backlog but no ETA. We'll provide a status update when there is a release plan for this. Please open a new issue if further support is needed.

**Comment by bbence84** [comment]
Thanks a lot and sorry for the late response! Actually based on various factors, I decided to move to an ARM64 architecture (RPi4), hence it's not important for me personally anymore to have ARM32 support. But thanks for your swift response in any case!

**Comment by Clinale** [comment]
Hi, when will the sdk supporting arm32 version be released? I want to use the sdk on the Raspberry Pi arm32 architecture, and I also encountered this problem.
