### ISSUE TITLE
set EndSilenceTimeoutAmbiguous and BabbleTimeout from Python

### ISSUE THREAD

**Issue by hendryman** [Azure-Samples/cognitive-services-speech-sdk#1804]
There is a number of speech properties not exposed in the Python SDK - e.g. `EndSilenceTimeoutAmbiguous` and `BabbleTimeout`.

How can I set these properties from a Python script?

**Comment by ralph-msft** [comment]
Those two properties are not applicable when using the [Cognitive Services Speech SDK](https://learn.microsoft.com/azure/cognitive-services/speech-service/speech-sdk) since it uses newer and more robust speech recognition models.

You can find more information about the timeouts that can be set for the new speech recognition service here:
https://learn.microsoft.com/azure/cognitive-services/speech-service/how-to-recognize-speech?pivots=programming-language-csharp#change-how-silence-is-handled.

**Comment by hendryman** [comment]
Awesome. Thanks a lot!
