### ISSUE TITLE
Microsoft.CognitiveServices.Speech.Core.dll not found when using the Speech SDK in a VS Extensibility Project

### ISSUE THREAD

**Issue by bradygaster** [Azure-Samples/cognitive-services-speech-sdk#1833]
Similar to a few other issues reported:

* https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/619
* https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/132

I am having a problem using the Speech SDK when I use it in a Visual Studio extensibility project. I copied the code from the documentation's quick start and used it in a .NET Core Console App and it works. I notice that the file `Microsoft.CognitiveServices.Speech.Core.dll` appears in the `bin` folder for the application. 

However, when I build the VSIX from my Extensibility project, the `Microsoft.CognitiveServices.Speech.Core.dll` does not appear in the extension's folder, but a similarly-named file, `Microsoft.CognitiveServices.Speech.csharp.dll` does appear there. I've tried manually referencing the DLL rather than the NuGet package, but this doesn't provide a good workaround and the errors still occur. 

CC @achandmsft and @scottaddie as we were chatting about this together. Also @madskristensen, who may have additional context.

**Comment by bradygaster** [comment]
Appreciate it!

**Comment by glharper** [comment]
This has been taken up via email by @wade0016.

**Comment by tristanlbailey1** [comment]
What was the solution to the issue?

I have a very similar issue when attempting to install and run a console app that uses the Microsoft.CognitiveServices.Speech package through NuGet. The following error message is displayed:

> Unhandled exception: System.DllNotFoundException: Unable to load DLL 'Microsoft.CognitiveServices.Speech.core.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E) at Microsoft.CognitiveServices.Speech.Internal.SpeechConfig.speech_config_from_subscription(IntPtr& config, String subscriptionKey, String region) at Microsoft.CognitiveServices.Speech.SpeechConfig.FromSubscription(String, subscriptionKey, String region) at CommandApp.Program.Main()

Since NuGet manages (or should manage) the dependencies for such packages, I can't see this file included in the Application Files list of the Publish settings screen, nor can I see a way to include the file.

Thanks in advance.

**Comment by jtsoftware** [comment]
This is a problem. NuGet is not installing Microsoft.CognitiveServices.Speech.core.dll into the bin directory.

**Comment by frank-vanderhulst** [comment]
@tristanlbailey1 Can you please share exactly what you entered in the .csproj file to workaround the problem?

**Comment by tristanlbailey1** [comment]
Here you go:
[https://stackoverflow.com/questions/75616169/unable-to-load-dll-microsoft-cognitiveservices-speech-core-dll-could-not-be-f#answer-75623332](url)
It might pay to read the comments, too.

**Comment by DJSures** [comment]
Hello, my application, which uses plugins, is experiencing issues from this situation. It has been almost a year since the Stack overflow recommendation, and the issue remains. I'm using .net 8, and the .core is not being copied to the bin output folder without additional effort. I need help explaining to our customers, who build plugins in our application, that this process may (or may not) be required for various Nuget packages. Instead, the customer gets an error about the DLL not existing in the BIN folder and gives up blaming our application.

Has there been progress on this, as stated by the commenter in the referenced Stackoverflow answer? To plan to move forward with our migration to .net 8 from .net framework 4.7.2, we need to understand how to document this for our customers.

I respect this topic is "closed", but there does not seem to be a fix/resolution for it.

**Comment by kcwalina** [comment]
you need to add  RuntimeIdentifier to your csproj file, e.g. <RuntimeIdentifier>win-x64</RuntimeIdentifier>

**Comment by DJSures** [comment]
> you need to add RuntimeIdentifier to your csproj file, e.g. win-x64

Thanks for taking the time to write some words, but you can take a moment to expand on your statement? Are you stating that i should add the DLL's within the runtime\win-x64 folder? Or are you saying there is a RuntimeIdentifier parameter to add to the csproj file? 

If I add the DLL's from the runtime folder, i have to do so for each build platform and its respective folder? Is this not easily automated with an option? .NET 4.8 had no problem including the dll's from the nuget in a build. Why does .NET 8 not include the DLLs from its respective runtime within the build?
