### ISSUE TITLE
Get Mac Microphone UUID in Python

### ISSUE THREAD

**Issue by hendryman** [Azure-Samples/cognitive-services-speech-sdk#1861]
According to the [SDK documention](https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-select-audio-input-devices#audio-device-ids-on-macos), the `NAME` parameter in `speechsdk.audio.AudioConfig(device_name="NAME")` is the UUID of the microphone. However, the UUID seems only retreivable via C. Is there a retrieval method for Python? 

I can't get the answers given [here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1805#issue-1551852879) to work - pyaudio doesn't retrieve the UUID, and /`Library/Preferences/Audio/com.apple.audio.DeviceSettings.plist` does not contain the internal microphone, and doesn't label the UUID.

Please help. I've been trying to solve this for weeks now...

**Comment by dargilco** [comment]
Hi @hendryman this is Darren from the Speech SDK team. Thank you for opening this issue! I don't think there is much more we can help. Try to use other resources to find a way to do this. We have a work item on the SDK, as Panu mentioned in your original GitHub issue, to add an API on the SDK to enumerate audio devices. We need to prioritize this work item against other more urgent items, that's why it's in the backlog.
