### ISSUE TITLE
Multiple "threads" of SpeechRecognizer in python?

### ISSUE THREAD

**Issue by bbence84** [Azure-Samples/cognitive-services-speech-sdk#1863]
I am building a small prototype where the SpeechRecognizer is used to detect the users questions and then I call the OpenAI GPT model to respond to the question. This works pretty well, however now I am thinking about the best way to incorporate simple voice commands. Ideally I would need to understand the following "intents" regardless of how exactly they are phrased. Intents like the following:
1. Stop talking until I tell you that you can speak
2. Now you can speak
3. Reply in english / german / etc.
4. Stop what you are currently saying
5. Speak louder / speak with less volume
Etc. So again there should be a parallel thread that picks up these commands from the mic indepdently from the main SpeechRecognizer. Also this part of the code should understand the "intent" even if the commands are phrased independently. 

What are the most suitable Azure APIs and techniques to realize this? I saw LUIS that might suitable but that is going to be deprecated. And I am not sure about the intent recognition part.

Thanks a lot! :)

**Comment by chschrae** [comment]
Hi there @bbence84 ,

There are lots of ways you could approach this:

The Conversational Language Understanding offering from Microsoft which is what is replacing LUIS. https://learn.microsoft.com/en-us/azure/cognitive-services/language-service/conversational-language-understanding/overview

Since you are already calling GPT, you could use it to do intent classification for you. https://www.pragnakalp.com/intent-classification-paraphrasing-examples-using-gpt-3/ but that will likely be slower.

I hope this helps!

I'll close the issue to keep our list fresh, but feel free to reply or reopen it if you have more questions.
