### ISSUE TITLE
Continuous keyword recognition through Objective C 

### ISSUE THREAD

**Issue by sagarmahewar** [Azure-Samples/cognitive-services-speech-sdk#1868]
For once keyword recognition, we can use SPXKeywordRecognizer ----> recognizeOnceAsync
But for continuous keyword recognition, it doesn't have any specific API in SPXKeywordRecognizer.

should we loop in same (recognizeOnceAsync) call, for continuous keyword recognition behaviour ?
or any plan in progress to introduce a new feature ? 

Please suggest/confirm.

**Comment by dargilco** [comment]
Hi @sagarmahewar, this is Darren from the Speech SDK team. You will need to set up a loop that does a call to SPXKeywordRecognizer.recognizeOnceAsync, then and once keyword is detected, feed the audio into the speech recognizer for a call to SPXSpeechRecognizer.recognizeOnceAsync. Once an utterance has been recognized (or timed out due to no speech), repeat the loop.
