### ISSUE TITLE
Continuous Recognition times out after period of inactivity

### ISSUE THREAD

**Issue by Boboswitch** [Azure-Samples/cognitive-services-speech-sdk#1942]
Hi, I am writing a python script for a Virtual Assistant that needs to run 24/7. When the speech recognition works, it runs flawlessly. However, the issue I run into is when there is no noise or anybody talking, it times out. I don't get any error codes, just a script that is still running with no output. Even the microphone icon on my desktop goes away once this happens. I have spent weeks researching ways to deal with a time out issue or anything related to it and thorough testing, but with the same end result.

My environment:
Windows 10
Visual Studio Code
Python Version 3.11.3
Venv
Imports include: openai, azure.cognitiveservices.speech, pywhatkit, and lifxlan

I have tried examples from [this](https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-recognize-speech?pivots=programming-language-python) Microsoft website to try and get a better understanding of what I'm doing wrong. However, I have ended up with the same result.

Thank You!

**Comment by brandom-msft** [comment]
Hi @Boboswitch - thanks for using the SDK. It sounds like part of what you are running into is by design. Using continuous recognition will process speaking until StopContinuousRecognitionAsync() is called. 

If several minutes of silence are detected the recognition will be cancelled and the connection is closed. In this case you would receive notification of the termination, you'll need make sure you've [subscribed to the `canceled` event](https://learn.microsoft.com/azure/cognitive-services/speech-service/how-to-recognize-speech?pivots=programming-language-javascript#use-continuous-recognition) and handle the result.

With that said, have you taken a look at the Virtual Assistant documentation? It seems like it may better fit the scenario you're working on. [Voice assistants overview](https://learn.microsoft.com/azure/cognitive-services/speech-service/voice-assistants). That path would utilize keyword recognition, allowing you to invoke speech recognition whenever the keyword is spoken. You can [read more about keyword recognition here](https://learn.microsoft.com/azure/cognitive-services/speech-service/keyword-recognition-overview). 

Since you mentioned using python, [here's a link to our python sample demonstrating keyword recognition.](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/b4257370e1d799f0b8b64be9bf2a34cad8b1a251/samples/python/console/speech_sample.py#LL290C48-L290C48)

**Comment by Boboswitch** [comment]
Thank you so much. I am still working on getting it to work and I will let you know if I have any issues.

**Comment by Boboswitch** [comment]
Ok, so I have been working through trying to get the keyword recognition to work. I’m using the code example from GitHub. It runs fine, but it only runs once. I have tried putting it in a loop, but I get the same result. Is there a way to run keyword recognition in a continuous loop? So that it’s always listening for the keyword?

**Comment by brandom-msft** [comment]
If you're referencing the python example, I'm guessing it is stopping because of the call to [stop_keyword_recognition()](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/b4257370e1d799f0b8b64be9bf2a34cad8b1a251/samples/python/console/speech_sample.py#LL343C49-L343C49). Even if you're not referencing that one, many of our samples/tests have a similar "stop" mechanism that could be misleading. For your scenario, it sounds like you would want KWS to run continuously so you would remove the call to `stop` from that location. 

You will likely still want a stop mechanism, for error handling or for flow control of whatever your scenario is. I'd encourage you to look around at the various samples/tests we offer across various languages. While they aren't all in Python, the general approaches still apply and can be useful to coming up with your own solution. e.g. [Here's one in C++](https://github.com/Azure-Samples/Cognitive-Services-Voice-Assistant/blob/439001c896c27b3a55c8d4bd3fce6955d660b7d4/clients/cpp-console/src/common/DialogManager.cpp#LL322C30-L322C30) that [calls `stop` based on user input](https://github.com/Azure-Samples/Cognitive-Services-Voice-Assistant/blob/439001c896c27b3a55c8d4bd3fce6955d660b7d4/clients/cpp-console/src/common/Main.cpp#L125) from a menu of command options.

**Comment by Boboswitch** [comment]
I have been working on getting keyword recognition running in my script. I have it all working fine the way I want it to. However, when I say the wake word once, it runs normally. Then if I say it again, it runs twice, etc. I have gone through and have tried to figure out the issue. I checked loops, functions, and variables. I have pasted part of my script below.


`import time
import azure.cognitiveservices.speech as speechsdk

speech_key, service_region = "My SpeechKey", "My Region"
model = speechsdk.KeywordRecognitionModel("My_Keyword_Model.table")
keyword = "Hey, Computer"
speech_config = speechsdk.SpeechConfig(subscription=speech_key, region=service_region)
speech_synthesizer = speechsdk.SpeechSynthesizer(speech_config=speech_config)
speech_recognizer = speechsdk.SpeechRecognizer(speech_config=speech_config)



def speech_recognize_keyword_from_microphone():
    """performs keyword-triggered speech recognition with input microphone"""
    done = False
    def stop_cb(evt):
        """callback that signals to stop continuous recognition upon receiving an event `evt`"""
        print('CLOSING on {}'.format(evt))
        nonlocal done
        done = True
    def recognized_cb(evt):
        """callback for recognized event"""
        if evt.result.reason == speechsdk.ResultReason.RecognizedKeyword:
            print('RECOGNIZED KEYWORD: {}'.format(evt))
            time.sleep(1)

        elif evt.result.reason == speechsdk.ResultReason.NoMatch:
            print('NOMATCH: {}'.format(evt))
    #Function that preforms the task based on user input
    def main(args):
        instruct = ""
        time.sleep(1)
        instruct = args.result.text[11:]
        print(instruct)
        if "hello" in instruct.lower():
            speech_synthesizer.speak_text_async("Hello")
    
    # Connect callbacks to the events fired by the speech recognizer
    speech_recognizer.recognized.connect(recognized_cb)
    speech_recognizer.recognized.connect(main)
    # stop continuous recognition on either session stopped or canceled events
    speech_recognizer.session_stopped.connect(stop_cb)
    
    # Start keyword recognition
    speech_recognizer.start_keyword_recognition(model)
    print('Say something starting with "{}" followed by whatever you want...'.format(keyword))
    while not done:
        time.sleep(.5)


#Runs it in a forever loop
while True:
    speech_recognize_keyword_from_microphone()`

**Comment by Boboswitch** [comment]
Thank you for your help. Removing the recognizing call back seemed to be the root cause of my problem. Thanks again!

**Comment by Quilljou** [comment]
> Hi @Boboswitch - thanks for using the SDK. It sounds like part of what you are running into is by design. Using continuous recognition will process speaking until StopContinuousRecognitionAsync() is called.
> 
> If several minutes of silence are detected the recognition will be cancelled and the connection is closed. In this case you would receive notification of the termination, you'll need make sure you've [subscribed to the `canceled` event](https://learn.microsoft.com/azure/cognitive-services/speech-service/how-to-recognize-speech?pivots=programming-language-javascript#use-continuous-recognition) and handle the result.
> 
> With that said, have you taken a look at the Virtual Assistant documentation? It seems like it may better fit the scenario you're working on. [Voice assistants overview](https://learn.microsoft.com/azure/cognitive-services/speech-service/voice-assistants). That path would utilize keyword recognition, allowing you to invoke speech recognition whenever the keyword is spoken. You can [read more about keyword recognition here](https://learn.microsoft.com/azure/cognitive-services/speech-service/keyword-recognition-overview).
> 
> Since you mentioned using python, [here's a link to our python sample demonstrating keyword recognition.](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/b4257370e1d799f0b8b64be9bf2a34cad8b1a251/samples/python/console/speech_sample.py#LL290C48-L290C48)

Can we set a 3-second silence to automatically cancel recognition? I want to achieve this functionality now.
