### ISSUE TITLE
I am using SpeechRecognizer class in JavaScript and the intermediate recognition result obtained using the recognize method does not have punctuation, what should I do if I want to have punctuation?

### ISSUE THREAD

**Issue by pengchengZhi001** [Azure-Samples/cognitive-services-speech-sdk#1960]
I am using SpeechRecognizer class in JavaScript and the intermediate recognition result obtained using the recognize method does not have punctuation, what should I do if I want to have punctuation?

**Comment by glharper** [comment]
@pengchengZhi001 Thank you for using JS Speech SDK, and writing this issue up. Because each sentence is usually a longer collection of words, and the intermediate recognition result merely parses shorter collections of words, punctuation can't really be assigned correctly without a large context.

For example, if you got the intermediate response "my friend drove a car", what punctuation should be assigned to that?
The final sentence could be, depending on the rest of the turn, "My friend drove a car to New York." or "My friend drove a car, but decided to start taking the bus instead" or "My friend drove. A car was over there." or just "My friend drove a car."

Does that make sense?

**Comment by pankopon** [comment]
Closed as answered; punctuation and capitalization is only added in the final result. Please open a new issue if more support is needed.

**Comment by lenqing6** [comment]
@glharper What if I need him to return the recognizer. recognized event faster? How do I configure SpeedConfig?

**Comment by glharper** [comment]
> @glharper What if I need him to return the recognizer. recognized event faster? How do I configure SpeedConfig?

There's nothing in the JS SDK to configure the speed or size of the recognized callback. You could possibly throttle the input  speed of the audio using a pushstream, which might have the desired effect.

**Comment by fantinuoli** [comment]
@glharper Just wanted to point out that Google ASR API offers punctuation on Temporary results. There are possible use cases why a user wants prediction of punctuation while the incoming speech is still unfolding. Predictions are unstable towards the end of the transcription, but tend to be stable towards the beginning. You might want to reconsider adding this in future.

**Comment by glharper** [comment]
@fantinuoli Thanks for letting us know, I'll pass this info on to the service team.
