### ISSUE TITLE
Request for UPM package installable through git for more consistent update process

### ISSUE THREAD

**Issue by TheXRMonk** [Azure-Samples/cognitive-services-speech-sdk#2028]
**Is your feature request related to a problem? Please describe.**
Just the fact that manually installing unity packages is not the best practice for code-only SDK's.

**Describe the solution you'd like**
A unity package installable through git. 
Like; https://github.com/Cysharp/UniTask#install-via-git-url

**Describe alternatives you've considered**
Manually checking for updates and deleting the old SpeechSDK folder and then importing the new. (updating without deleting the old package could result in deprecated files being left alive in a project - the manual unity package importer never deletes anything - only overwrites if file already exists)

**Comment by glharper** [comment]
@jhakulin @BrianMouncer Is this a feasible ask for unity support?

**Comment by jhakulin** [comment]
@TheXRMonk Thanks for the request, we do have Unity UPM package for Speech SDK, however it is not yet publicly released. We will look at your request and let you know.

**Comment by jhakulin** [comment]
Created internal workitem; 5051426.

Currently releasing of Speech SDK packages via GitHub repo is not included in the current team release practices and we do not have a plan yet for this issue. Apologizes for the inconvenience this may cause for you. I will close the issue here, but we will have internal work item in our backlog.
