### ISSUE TITLE
Unity TTS Streaming Sample creates huge UI lock-up spike 

### ISSUE THREAD

**Issue by TheXRMonk** [Azure-Samples/cognitive-services-speech-sdk#2045]
**Describe the bug**
Unity TTS Streaming Sample creates huge UI lock-up spike. 

https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/db4a5a9a4a152e86348f3c016ac0b0cf3b539cf7/quickstart/csharp/unity/text-to-speech/Assets/Scripts/HelloWorld.cs#L1-L178

**To Reproduce**
Just download the sample script and implement in a scene to see the issue.

**Expected behavior**
A sample that shows how to integrate correctly with Unity's audio system to avoid UI lock-ups.

**Version of the Cognitive Services Speech SDK**
1.31.0

**Additional context**
Profiler recorded on device (MagicLeap2). The big blue spike is when clicking the button;
![image](https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/54309738/9e39b64b-6de2-4c3e-a846-acd622d2ad59)
First spike is AudioClip.InvokePCMReaderCallback_internal() under LoadFMODSound.
![image](https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/54309738/a457b2f2-3337-453f-b8fa-2af9bd983451)

The second spike is from "HelloWorld.Update()"
![image](https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/54309738/f15aed78-0106-4d5b-a2f7-1724914d2095)

I've tried moving the creation of the audio clip to start and reusing the clip, but am still getting spike for AudioClip.InvokePCMReaderCallback_internal().

**Comment by glecaros** [comment]
@yulin-li can you please take a look?

**Comment by chschrae** [comment]
@TheXRMonk I'm not really the expert here, but the sample allocates an audio clip buffer of 10 min to show the maximum. Have you tried reducing that size to something closer to what you are expecting?

**Comment by TheXRMonk** [comment]
> @TheXRMonk I'm not really the expert here, but the sample allocates an audio clip buffer of 10 min to show the maximum. Have you tried reducing that size to something closer to what you are expecting?

I've tried 5 minutes without any change (even though that's still much more than needed). I think the issue is rather in how the PCMReaderCallback is implemented. 
Some online forum posts suggests using OnAudioFilterRead instead because of bad performance with PCMReader - havn't tried this, mostly because our architecture needs the clip returned from the service rather than playing directly on an audio source without an audioclip (which is what happens when implementing "OnAudioFilterRead" - its more like creating a synthesizer). 

But in general it would be good to get a concise working example that shows how to use your push/pull/audioDataStreams correctly with Unity, to avoid these issues.

**Comment by yinhew** [comment]
Hi, @TheXRMonk 

I was able to reproduce your UI lock issue today.

And here is the root cause I found:
The audio clip need collect enough data (4096 audio samples) before it gets ready to play.
This collection need hundreds of milliseconds, as service side need such time to synthesize 4096 samples.
And based on current sample code, this collection procedure is a blocking code scope, which caused the UI lock.

Now I updated this sample code, to move this collection procedure into a routine method, and make yield return during the collection. And I verified that the UI lock issue was gone after this update.
Here is the updated code, you can have a try:
https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/yinhew/tts/quickstart/csharp/unity/text-to-speech/Assets/Scripts/HelloWorld.cs

Thanks,
Yinhe

**Comment by jhakulin** [comment]
Thank you @yinhew ! Setting the issue pending close.
