### ISSUE TITLE
Docker :: Python 3.7 :: which base image to use?

### ISSUE THREAD

**Issue by madkote** [Azure-Samples/cognitive-services-speech-sdk#205]
I would like to put my app into Docker container. And now I faced the problem...

Python 3.7 - which Docker base image for azure speech services?

python:3.7 -> does not work, it is missin libssl.1.0.0
python:3.7-alpine -> seems that python package can not be installed there...

**Comment by mahilleb-msft** [comment]
Hi @madkote, we're working on lifting this in future releases. For the python:3.7 container the underlying distro is Debian 9, which we do not yet support.
So right now, please use Ubuntu 16.04 or 18.04 as underlying distro and make sure to install the [prerequisites](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-sdk#linux).

**Comment by madkote** [comment]
thx @mahilleb-msft !

ok, good to know that this issue is known.<
indeed, I had to go with ubuntu 18, but with python 3.6.

**Comment by mahilleb-msft** [comment]
Hi @madkote, with version 1.5.0 of the Speech SDK, Debian 9 based images like python:3.7 should also be supported. libssl1.0.2 should be already pre-installed, but libasound2 is still a dependency on top.

I'm closing this issue here, but please re-open if you run into problems using python:3.7 with Speech SDK 1.5.0.
