### ISSUE TITLE
TTS For On-premises not supporting ws 

### ISSUE THREAD

**Issue by vdharashive** [Azure-Samples/cognitive-services-speech-sdk#2058]
The On Cloud instance support wss but on-premise does not support support wss using docker based implementation. 

There should not be any implementation change for connecting azure cloud and on-premise , 

 {"level":30,"time":1691920520035,"pid":3645508,"hostname":"ip-10-0-214-82","reason":"websocket send error: Websocket not ready  Error\n    at WebsocketMessageAdapter.sendRawMessage (/home/admin/apps/jambonz-feature-server/node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/common.browser/WebsocketMessageAdapter.js:277:144)\n    at WebsocketMessageAdapter.<anonymous> (/home/admin/apps/jambonz-feature-server/node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/common.browser/WebsocketMessageAdapter.js:328:51)\n    at step (/home/admin/apps/jambonz-feature-server/node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/common.browser/WebsocketMessageAdapter.js:65:23)\n    at Object.next (/home/admin/apps/jambonz-feature-server/node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/common.browser/WebsocketMessageAdapter.js:46:53)\n    at fulfilled (/home/admin/apps/jambonz-feature-server/node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/common.browser/WebsocketMessageAdapter.js:37:58)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","msg":"synthAudio: (Microsoft) synthesis canceled"}

**Comment by rhurey** [comment]
Thanks for reaching out with the question.

Speech to Text and Text to Speech containers do not have any TLS certificates installed in them to encrypt traffic with, so by default they will only supprt ws:// or http:// connections.

There's some documentation on securing Azure containers [here](https://learn.microsoft.com/azure/ai-services/cognitive-services-container-support#azure-ai-services-container-security)

Also, because the SDK has different API's to connect to an Azure cloud region vs a local host name, the way the SpeechConfig is constructed needs to differ between a cloud and container use case. [This article](https://learn.microsoft.com/azure/ai-services/speech-service/speech-container-ntts?tabs=container&pivots=programming-language-javascript#use-the-container) shows the call differences.

**Comment by vdharashive** [comment]
Thanks for replying ,

Currently we are working with http and ws for onpreme docker.

Also have modified the code to connect using 

const speechConfig = sdk.SpeechConfig.fromHost("http://localhost:5000");

Here our expectations is the connection with onprimese docker  to be WS for tts, which is not happening , since the implementation of code is done for ws. Since same api we are using azure cloud to connect overs ws/wss , 

Why there is change in http and ws for onprime and cloud

**Comment by rhurey** [comment]
I'm following up with the team that owns the TTS container...

**Comment by yanchang-gyc** [comment]
Hello @vdharashive , sorry for your inconvenience, we are developing to support websocket for onprem tts. this will be done in next month(Sep 2023).
