### ISSUE TITLE
time out 

### ISSUE THREAD

**Issue by ThetaRgo** [Azure-Samples/cognitive-services-speech-sdk#2079]
Current RTF: 1.63551 (threshold 2), frame interval 10025ms (threshold 3000ms). USP state: ReceivingData. Received audio size: 246528 bytes.

text is too long ? how to set the threshold ?

**Comment by BrianMouncer** [comment]
try experimenting with our public samples first.

https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/04e4fbdee065978ea0bff09b6de26fe7b80cf2a7/samples/csharp/sharedcontent/console/speech_synthesis_samples.cs

**Comment by brandom-msft** [comment]
Unable to investigate or troubleshoot with the given information, closing issue.

If you are still running into issues, please open a new ticket. If your issue is a bug or unexpected behavior, use [this template](https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/new?assignees=&labels=&projects=&template=bug_report.md) and fill in the required information. Thanks!
