### ISSUE TITLE
How to set up Setting.cs in embedded_speech_samples?

### ISSUE THREAD

**Issue by begood0513** [Azure-Samples/cognitive-services-speech-sdk#2096]
I'm surprised there isn't any documentation on how to set the value of 'Setting.cs‘. For those unfamiliar with this kind of project, it's unclear how to proceed. The sample code is in [here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/csharp/dotnetcore/embedded-speech)

![image](https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/51038432/4d6c61a4-68c9-492c-b838-ee97d73dfe4f)

**Comment by pankopon** [comment]
@begood0513 Hi, are you a registered customer of the [embedded speech public preview](https://aka.ms/embedded-speech)? (Otherwise the sample is not applicable.)

Instructions can be found in the sample [README](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/csharp/dotnetcore/embedded-speech/README.md).
You can either modify the settings file directly and replace placeholder strings ("Your...") according to your setup as noted in [how to build the sample](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/csharp/dotnetcore/embedded-speech/README.md#build-the-sample), or use environment variables for the same effect as described in [how to run the sample](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/csharp/dotnetcore/embedded-speech#run-the-sample).

Are there some specific settings that you would like to get more information about?

**Comment by begood0513** [comment]
Thank you for your reply. I didn't register it, it seems that I have to use Microsoft.CognitiveServices.Speech.

**Comment by pankopon** [comment]
Closed as resolved, please create a new issue if more support is needed.
