### ISSUE TITLE
Speech Recognizer - 0x19 (SPXERR_BUFFER_TOO_SMALL)

### ISSUE THREAD

**Issue by SantwaniRoma** [Azure-Samples/cognitive-services-speech-sdk#2118]
**Describe the bug**

We are using SpeechRecognizer to for STT. We have registered all the events such as Canceled, Recognized, Recognizing, SpeechEndDetected, etc. We are using PCM wav format, as recommended.

`AudioStreamFormat.GetWaveFormatPCM(16000, 16, 1);
`

We have been using the same code base and implementation from past few months now. Recently, speech recognizer has started throwing errors. One error is thrown when speech recognizer stops the recognition. The issue is intermittent but it's happening quite often.

`SpeechRecognizer.StopContinuousRecognitionAsync()
`

Below is the error:
```
[SpeechRecognizer_Canceled] CANCELED: ErrorDetails=Exception with an error code: 0x19 (SPXERR_BUFFER_TOO_SMALL) SessionId: _some-session-id_
[SpeechRecognizer_Canceled] CANCELED: ErrorCode=RuntimeError
SpeechRecognizer_Canceled CANCELED: Reason=Error
```

When we try to start the recognition post CANCELED event, speech recognizer throws below error:

`SpeechRecognizer.StartContinuousRecognitionAsync()
`

`Exception: System.AggregateException: One or more errors occurred. (Exception with an error code: 0x13 (SPXERR_START_RECOGNIZING_INVALID_STATE_TRANSITION)) ---> System.ApplicationException: Exception with an error code: 0x13 (SPXERR_START_RECOGNIZING_INVALID_STATE_TRANSITION) at Microsoft.CognitiveServices.Speech.Internal.SpxExceptionThrower.ThrowIfFail(IntPtr hr) at Microsoft.CognitiveServices.Speech.Recognizer.StartContinuousRecognition() at Microsoft.CognitiveServices.Speech.Recognizer.DoAsyncRecognitionAction(Action recoImplAction) at Microsoft.CognitiveServices.Speech.SpeechRecognizer.<StartContinuousRecognitionAsync>b__52_0() at System.Threading.Tasks.Task.InnerInvoke() at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj) at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) --- End of stack trace from previous location --- at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) --- End of inner exception stack trace `

**Version of the Cognitive Services Speech SDK**
Microsoft.CognitiveServices.Speech v1.32.1

We were using v1.24 when this error first occurred and upgraded to v1.32. But that didn't help either.

**Platform, Operating System, and Programming Language**

 - OS: Windows
 - Hardware - Any CPU
 - Programming language: C#, .NET 6.0

**What does this error mean? When and why this error occurs and what are the steps to fix this?
Has there been any changes in the framework/speech recognizer recently that triggered this behavior?**

**Comment by SantwaniRoma** [comment]
Can someone please assist on the issue?

**Comment by ralph-msft** [comment]
Generally, `SPXERR_BUFFER_TOO_SMALL` could happen because the internal audio buffer is too small for the audio being sent. There are also some non-audio related circumstances when that error could occur.

In order to better diagnose the issue you are seeing, could you please:
* Capture and share the SDK logs. You can find instructions here: https://learn.microsoft.com/azure/ai-services/speech-service/how-to-use-logging
* Share the minimum code that reproduces the issue you are seeing

**Comment by SantwaniRoma** [comment]
Thank you @ralph-msft.  We are integrating the logs as recommended and will share once we have the detailed logs.

Meanwhile, can you help understand what does _SPXERR_START_RECOGNIZING_INVALID_STATE_TRANSITION_ exception mean? Why does this occur when we start the speech recognition post _speech_cancelled_ event?

**Comment by SantwaniRoma** [comment]
@ralph-msft - we have added logs as instructed here - [](https://learn.microsoft.com/azure/ai-services/speech-service/how-to-use-logging)

```
string tempPath = Path.GetTempPath()
string speechRecognizerLogFilePath = Path.Combine(tempPath, "SpeechRecognizerLog.txt");
```
           
But we are unable to find the file inside app service's temp folder. How do we access this log file and share? 

![MicrosoftTeams-image (6)](https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/149184793/f96e0053-2c83-46b0-9c74-4e861663f5ee)

**Comment by pankopon** [comment]
@SantwaniRoma What is the working directory (launch folder) of your application? As a guess, if it's `C:\home\site\wwroot` (or underneath) as in your screenshot and your app runs in a restricted/sandbox environment then of course it cannot access folders outside of that. Either specify just a filename without a path, so that the log file is created in the app working directory (where it presumably can write to) or use an absolute path to an accessible location.
How is the audio data fed to the Speech SDK? Are you using a push or pull stream? If yes, make sure that the length of data as communicated to the SDK is not negative (check the value and/or add a trace in your application code).

**Comment by SantwaniRoma** [comment]
The working directory is `C:\home\site\wwroot.`
Tried without specifying the file path and still unable to access the file.
Is there any other way of accessing the file? Keen to know how others are using SDK logging and accessing the files in app service. Can you share an example or documentation with concrete example on how to access SDK logs file?

As for audio stream, I am using pull audio stream in PCM wav format.
`AudioStreamFormat.GetWaveFormatPCM(16000, 16, 1); 
`

**Comment by pankopon** [comment]
The log file is a normal file that's created on the file system on the device where your application runs. The instructions are as linked earlier. Be sure to specify the file in `speechConfig` before creating a recognizer. After the application has run you can access the log file on the command line or file explorer like any other file. If you don't specify a path and the working directory really is `C:\home\site\wwroot` or somewhere underneath, the log file must be there - search the whole directory tree. Otherwise your application possibly does not have permission to create files, which depends on your "app service" configuration. Unfortunately we cannot provide support without logs.

**Comment by pankopon** [comment]
Closed since no update, please open a new issue if more support is needed.
