### ISSUE TITLE
How can I set the recognition time parameters to reach the 1 minute limit of the official interface?

### ISSUE THREAD

**Issue by Bruce337f** [Azure-Samples/cognitive-services-speech-sdk#2153]

**Comment by pankopon** [comment]
Missing a proper description of the use case, as well as details of the platform, operating system, and programming language.
Ambiguous terms: 1 minute limit for... speech? Or silence? Or overall audio? What is the "official interface" in this context? Is this about using the Speech SDK (and which version) or REST API, or something else? All this basic information should have been provided when the issue was created.

If the intention is to adjust the silence timeout, it can be done like (Python example):
```
speech_config.set_property(speechsdk.PropertyId.SpeechServiceConnection_InitialSilenceTimeoutMs, "30000")
```
(for 30 sec)

There is currently no way to configure the max length of speech or overall audio. As a workaround, you could use `PushAudioInputStream` and keep a track of the length of audio written to the stream, and close the stream when the desired max length has been reached, which will end recognition at the latest. See a [Python sample](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/73ab99ea32c744bd5e9e1d7aa4ac8495197ea0ef/samples/python/console/speech_sample.py#L555) for speech recognition with a push stream.

**Comment by pankopon** [comment]
Closed as answered. Please open a new issue with a proper description and details if more support is needed.
