### ISSUE TITLE
When calling the function RecognizeOnceAsync, an error message "WS-OPEN-ERROR-UNDERLYING-IO-OPENFAILED" was returned

### ISSUE THREAD

**Issue by yeliucn** [Azure-Samples/cognitive-services-speech-sdk#2173]
When calling the function RecognizeOnceAsync, an error message "WS-OPEN-ERROR-UNDERLYING-IO-OPENFAILED" was returned；
System parameter SSL_ CERT_ FILE has been set；
The attachment contains relevant logs
[asr.log](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/13630650/asr.log)

**Comment by BrianMouncer** [comment]
Thank you for contacting us,

What distro and version of Linux are you using, and does it have the latest OpenSSL 1.1.x installed (some newer distros are coming only with openssl 3, and we have not migrated to 3.0 yet)?

Does this also happen with a different data center (e.g. could you reproduce the same error with something like westcentralus instead of westeurope)?

can you reproduce this error using just our [linux c++ sample](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/cpp/linux/from-microphone), or does this only with your own project?

Thanks,

Brian.

**Comment by yeliucn** [comment]
We have found the cause. It was the use of setcap to modify the program's capability during compilation that caused this exception; We are looking for which missing capability caused the issue

**Comment by yeliucn** [comment]
May I ask if you know which capabilities support needs to be added

**Comment by BrianMouncer** [comment]
You will need network, microphone, and speaker access permissions..

**Comment by yeliucn** [comment]
Okay, thank you for your support
