### ISSUE TITLE
FastAPI based "real time" wrapper APIs for Azure TTS and STT APIs?

### ISSUE THREAD

**Issue by bbence84** [Azure-Samples/cognitive-services-speech-sdk#2207]
I have built a Raspberry Pi based AI voice assistant in Python, using the Azure TTS and STT APIs. It works really well: https://github.com/bbence84/pi_gptbot

I am now planning to recreate it in Flutter. My problem is that I really don't want to use the API keys in the mobile app, because even if it's obfuscated, it could still be reverse engineered or traced. So I am thinking of creating a "proxy" / wrapper using FastAPI. But I am not a seasoned Python developer to assess if it's technically possible. I would like to "wrap" the continuous voice recognition and the text to speech APIs of Azure. Reducing latency as much as possible would be an important thing.

So essentially I am looking for some guidance on how to realize this.

And yes, I know there are other possibilities (like using the native TTS and STT functionality of the mobile devices), but I would like to assess the feasibility of a pure rest API using FastAPI. And for flutter, there are already Azure API wrappers, but those require the API keys to be shipped, and this is something I would like to avoid.

Thanks in advance!

**Comment by pankopon** [comment]
Hi, sorry for the delay in answering. For an example of real-time processing in particular, you might want to look into the [Python call center scenario](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/scenarios/python/console/call-center) (see also the scenarios common [intro page](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/scenarios)). However, you will still need to provide some form of [authentication](https://learn.microsoft.com/azure/ai-services/speech-service/rest-speech-to-text-short#authentication) in order to use the service.

**Comment by pankopon** [comment]
Closed as answered, please open a new issue if more support is needed.

**Comment by xKENNETHx** [comment]
Hi @bbence84 
I hope you are doing well.

I've recently implemented this code to run a Continouos Speech Recognizer in FastAPI (with WebSocket) using the Azure Speech Recognition Service, for a Real-Time application.

Check out this post in StackOverflow and see if that helps you: https://stackoverflow.com/a/78743136/26354907
