### ISSUE TITLE
如何下载到1.35.0的iOS-arm64版本MicrosoftCognitiveServicesSpeech.framework

### ISSUE THREAD

**Issue by fxps** [Azure-Samples/cognitive-services-speech-sdk#2274]
我正在将MicrosoftCognitiveServicesSpeech接入到UE4 4.27.2的游戏工程里，由于MicrosoftCognitiveServicesSpeech-XCFramework-1.35.0在synthesis-samples或speech-samples的demo里使用时需要在xcode的synthesis-samples Targets->Build Phases->Link Binary With Libraries里添加MicrosoftCognitiveServicesSpeech.xcframework，同时还需要在synthesis-samples Targets->Build Phases->Copy Bundle Resources里指定具体的资源即MicrosoftCognitiveServicesSpeech.xcframework/ios-arm64/MicrosoftCognitiveServicesSpeech.framework时才能正常生成ipa格式的iOS安装包，但是在UE4里，我到目前为止还未找到如何配置类似Xcode里配Copy Bundle Resources的方法，所有我想下载一个直接能用的1.35.0 [iOS-arm64版本framework格式的SDK。
![AruzeSpeechSDK](https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/8587555/1dd2e8a1-95d9-4ee0-aae5-58c7d45bd762)

**Comment by dargilco** [comment]
Translation:

Title:
How to download the iOS-arm64 version to 1.35.0 MicrosoftCognitiveServicesSpeech.framework

Content:
I'm plugging Microsoft CognitiveServicesSpeech into UE4 In game projects 4.27.2, since Microsoft CognitiveServicesSpeech-XCFramework-1.35.0 is used in synthesis-samples or speech-samples demos, you need to use the synthesis-samples Targets->Build Phases->Link Binary in xcode With Libraries, you need to add MicrosoftCognitiveServicesSpeech.xcframework, and you also need to specify the specific resource in synthesis-samples Targets->Build Phases->Copy Bundle Resources. xcframework/ios-arm64/MicrosoftCognitiveServicesSpeech.framework can normally generate the iOS installation package in ipa format, but in UE4, I haven't found a way to configure Copy Bundle Resources similar to Xcode, all I want to download a direct 1.35.0 [ The iOS-arm64 SDK is in the framework format.

**Comment by fxps** [comment]
我自己已解决，不需要下载MicrosoftCognitiveServicesSpeech.framework了，直接使用官方下载的原版MicrosoftCognitiveServicesSpeech.xcframework即可，谢谢。
