### ISSUE TITLE
SAPI output for en-GB is incorrect

### ISSUE THREAD

**Issue by peterolson** [Azure-Samples/cognitive-services-speech-sdk#2284]
[As described here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/2223#issuecomment-1900629948), the SAPI output for en-GB and en-US is identical, even though US and GB accents are different.

Here is the SAPI output that I currently receive. The columns are word, en-US SAPI and en-GB SAPI.
```
tour    t ao r   -      t ao r
beard   b iy r d         -      b iy r d
pillow  p ih l ow        -      p ih l ow
ernest  er r n ih s t    -      er r n ih s t
comma   k aa m ax        -      k aa m ax
hear    h iy r   -      h iy r
bug     b ah g   -      b ah g
bottle  b aa t ax l      -      b aa t ax l
hair    h eh r   -      h eh r
driver  d r ay v ax r    -      d r ay v ax r
```

As you can see, the output is identical for the two regions.

The [documentation here describing the phonetic alphabet for en-GB](https://learn.microsoft.com/en-us/azure/ai-services/speech-service/speech-ssml-phonetic-sets#en-gben-ieen-au) does not use SAPI, but based on the information there I would expect the output to differ as follows for en-GB:

- There should only be two phonemes in "tour": t ʊə
- There should only be three phonemes in "bird": b ɜː d
- There should only be five phonemes in "ernest": ɜː n ɪ s t
- There should only be two phonemes in "hear": h ɪə
- There should only be two phonemes in "hair": h ɛə
- There should only be five phonemes in "driver": d r aɪ v ə

**Comment by wangkenpu** [comment]
Thanks for reporting the issue @peterolson . We have noticed it because we wrongly copied the en-US phoneme table. Currently, we do not expose the en-GB SAPI phoneme name.

If you still need the en-GB phoneme name. It's a new request. Because we need some bandwidth to prioritize the new request, we only support new features for big customers, i.e., the usage on pronunciation assessment is larger than 1k/month or reach the minimum bar of the [Commitement Tiers](https://azure.microsoft.com/en-us/pricing/details/cognitive-services/speech-services/). Once you reach this bar, welcome to contact us again by [mspafeedback@microsoft.com](mailto:mspafeedback@microsoft.com).

**Comment by peterolson** [comment]
@wangkenpu At the time that [I originally reported this issue,](https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/2223#issuecomment-1900629948) the documentation stated that en-GB was supported. I now see that this information [was removed recently](https://github.com/MicrosoftDocs/azure-docs/commit/61065bcbbc8c7a7d6501c1468e3e13af8371c4e1) to make it easier to dismiss this issue as a feature request rather than a bug. 

This has been a very frustrating experience, getting mixed messages about what is supported and what is not supported, and having bugs reclassified as feature requests to avoid dealing with them.

**Comment by pankopon** [comment]
@wangkenpu @iamwwn Was en-GB earlier included in the [SAPI support table](https://github.com/MicrosoftDocs/azure-docs/blob/b42ba4f8170aa4b0b735e4eb74f9148835da7082/articles/ai-services/speech-service/how-to-pronunciation-assessment.md#supported-features-per-locale) by accident even though it was not really available? Do you need to actually develop SAPI phoneme support for en-GB, it does not exist yet?

**Comment by pankopon** [comment]
Closing the item since it doesn't seem useful to expect any further response from the service side.
@peterolson Sorry about the bad experience, certainly not the best example of handling customer issues here. In case of similar service incidents in the future, please consider creating an Azure support ticket (ref. https://azure.microsoft.com/en-us/support/plans/) as those are guaranteed to go through a systematic review and more formal processing.
@wangkenpu @iamwwn FYI
