### ISSUE TITLE
Ingestion Client Diarisation

### ISSUE THREAD

**Issue by stephenadam5** [Azure-Samples/cognitive-services-speech-sdk#2299]
Hi team, do we know of anyway that we can change the amount diarised speakers using batch. I'm trying to use Whisper to diarise up to 30 speakers and by default the ingestion client only seems to accept 2 speakers (through being true or false in AddDiarization). Is there a way to up this or adjust the amount of speakers? Thanks

**Comment by BrianMouncer** [comment]
@HenryvanderVegte is this something that you can answer?

**Comment by HenryvanderVegte** [comment]
Hey @stephenadam5 ,
the issue here is that the ingestion client uses the 
[Speech to Text API v3.0](https://eastus.dev.cognitive.microsoft.com/docs/services/speech-to-text-api-v3-0/operations/CreateTranscription) which only supports the DiarizationEnabled boolean flag:
```json
        "diarizationEnabled": {
          "description": "A value indicating whether diarization (speaker separation) is requested.",
          "type": "boolean",
          "readOnly": false
        },
```


but diarization with up to 36 speakers was added in [Speech to Text API v3.1](https://eastus.dev.cognitive.microsoft.com/docs/services/speech-to-text-api-v3-1/operations/Transcriptions_Create):
```json
        "diarization": {
          "title": "DiarizationProperties",
          "required": [
            "speakers"
          ],
          "type": "object",
          "properties": {
            "speakers": {
              "title": "DiarizationSpeakersProperties",
              "type": "object",
              "properties": {
                "minCount": {
                  "format": "int32",
                  "description": "A hint for the minimum number of speakers for diarization. Must be smaller than or equal to the maxSpeakers property.",
                  "minimum": 1,
                  "type": "integer"
                },
                "maxCount": {
                  "format": "int32",
                  "description": "The maximum number of speakers for diarization. Must be less than 36 and larger than or equal to the minSpeakers property.",
                  "minimum": 1,
                  "type": "integer"
                }
              }
            }
          }
        },
```

with v3.0 there is unfortunately no way to up adjust the number of speakers. I don't believe there is any ETA when we'll update the ingestion client to v3.1..
