### ISSUE TITLE
[iOS SPXSpeechSynthesizer]: Can we cache the synthesizer result, then speak it out at a later time.

### ISSUE THREAD

**Issue by maxxfire** [Azure-Samples/cognitive-services-speech-sdk#2304]
Every time we synthesizer a sentence, it takes 2-3 seconds to start speaking due to the network delay maybe. We need every sentence be spoken fluently one followed by another one.
So we'd like to cache the synthesizer result first (without speaking it), util the previous sentence speaking finished. And it will use the cached result, and no need to fetch it from the server.

Do we have some API to accomplish this?
Thanks.

**Comment by bptstmlgt** [comment]
@maxxfire may I ask you for an example of your implementation of the synthesizer?
I have this issue (other developers too) and no answer/solution has been provided:
https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/2150

Curious to know if you're facing the same issue. Else, know what your implementation looks like to prevent this crash.

Thanks!

**Comment by BrianMouncer** [comment]
I would suggest setting the synthesizer output to a file or stream, rather than setting it for automatic playback to the default audio device. Then you will have control over when you play back the audio.  If you are using things like word level timing events, it would also allow you to more tightly sync highlight text in a read along scenario, to when the audio is header by the user, as opposed to when the audio was generated and streamed to the client...

you can find several examples of using push and pull output streams with TTS at https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/f57dcd21de09a8dca64e7c577e11b0b683b632dc/samples/csharp/sharedcontent/console/speech_synthesis_samples.cs#L373

**Comment by BrianMouncer** [comment]
If you would like an example of using word level timing data, take a look at this sample.

https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/f57dcd21de09a8dca64e7c577e11b0b683b632dc/samples/csharp/sharedcontent/console/speech_synthesis_samples.cs#L671

**Comment by BrianMouncer** [comment]
Sorry, I just noticed the iOS in the issue title.

you can see some Objective C example of stream output here https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/f57dcd21de09a8dca64e7c577e11b0b683b632dc/samples/objective-c/ios/synthesis-samples/synthesis-samples/ViewController.m#L240

**Comment by pankopon** [comment]
Closed as answered, please open a new issue if more support is needed.
