### ISSUE TITLE
 can't return result

### ISSUE THREAD

**Issue by wall3001** [Azure-Samples/cognitive-services-speech-sdk#232]
It can't return result. It had  happened when I used android/ios/java. I'm sure the network is OK and the audio data also normal.

**Comment by wall3001** [comment]
sometimes the result take so long time to return.

**Comment by wolfma61** [comment]
perhaps some more information - because sometimes it is hard to give advice if you don't have any information about the scenario

what version of the sdk?
are you using recognizeonce or continuousrecognition?
if you have a specific example where you had to wait for a long responce, please report the sessionid of the request

thank you
Wolfgang

**Comment by wall3001** [comment]
I used the android sample.SDK's version is 1.3.1. I keep speaking 5 minutes above that can't resopnce result to me.This is the one sessionID 8C3108B7AB4CEEB4B298FA4991DBAFCE. Thank you.

**Comment by wolfma61** [comment]
I searched for the session id, but couldn't find it in the service logs. 

What sample are you trying? 
you are using a sample with continuous recognition?
do you receive any results? interim results? cancel events?

if you post a sessionid, please add the region. makes it easier to search in service logs....

**Comment by wolfma61** [comment]
@wall3001  - any more information available?

**Comment by wolfma61** [comment]
closing, no feedback / additional information
