### ISSUE TITLE
Runtime error: Failed to create transport request

### ISSUE THREAD

**Issue by secbug** [Azure-Samples/cognitive-services-speech-sdk#236]
**Describe the bug**
When I run for speech_sample.py from main.py, I get an error.

**To Reproduce**
1. Clone files from cognitive-services-speech-sdk/samples/python/console/.
2. Add in your keys and endpoints.
3. Place a uncompressed, PCM-encoded mono audio wav file in the folder all the source code is located in.
4. Set weatherfilename to the name of your wav file.
5. Run main, and select any from file options.
6. Main says you've selected: <speech_recognize..._from_file at [object reference to the wav file>
7. Receive the above error message.

**Expected behavior**
I expect it to work.

**Version of the Cognitive Services Speech SDK**
SDK version number 1.5.0

**Platform, Operating System, and Programming Language**
 - OS: Windows 10
 - Hardware - x64 and x86
 - Programming language: Python

**Additional context**
When I run for speech_sample.py from main.py, I get the following error:

**You selected: <function speech_recognize_once_from_file at 0x0000013CF0C692F0>
Speech Recognition canceled: CancellationReason.Error
Error details: Runtime error: Failed to create transport request.**

**Comment by chlandsi** [comment]
We'll need some information to help identify the error:

1. Could you check if recognition works with our [sample audio file](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/cpp/windows/console/samples/whatstheweatherlike.wav)?
2. Please enable logging by calling `config.set_property(speechsdk.PropertyId.Speech_LogFilename, "logfile.log")` after initializing the `SpeechConfig` instance, and post the logfile.

Thanks!

**Comment by secbug** [comment]
Ran it with that sample first and it never ran either, but here is a zip containing all of the details of my run.
[RequiredFiles.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/3172963/RequiredFiles.zip)

**Comment by chlandsi** [comment]
Are you using a proxy? Could you post the exact code you're running, if it differs at all from the sample?

**Comment by secbug** [comment]
It doesn't differ at all. All we did was fill in the two required fields (sub and api region) and try a different wav file. And no, there is no proxy.

**Comment by chlandsi** [comment]
You may be entering an endpoint instead of a region. Please try
`service_region="eastus2"`, instead of something like 
`service_region="https://eastus2.api.cognitive.microsoft.com"`.

**Comment by secbug** [comment]
That was it. Why exactly is this one cognitive sdk code asking for a region where all of the rest of the cognitive sdks ask for the full url/hostname? Doesn't this limit the ability to run a local version of a cognitive api?
To append to this, I'd like to see this turned into or followed up by a feature request. Can there be more descriptive errors for networking issues? Nothing really explained the issue other than "transport error."

**Comment by chlandsi** [comment]
Good to hear that the problem is solved. Across all languages the speech SDK supports, the different recognizers can be constructed with different authentication parameters (subscription + region, subscription + endpoint, etc.). For Python, this is documented [here](https://docs.microsoft.com/en-us/python/api/azure-cognitiveservices-speech/azure.cognitiveservices.speech.speechconfig?view=azure-python), and in the samples.

We will be adding additional checks on the input arguments in future versions of the SDK.

**Comment by wiazur** [comment]
A note for others who got this error from different methods, if you are using the general Cognitive Services key/endpoint, you also have to use the region instead of the endpoint. The [SpeechConfig constructor](https://docs.microsoft.com/en-us/python/api/azure-cognitiveservices-speech/azure.cognitiveservices.speech.speechconfig?view=azure-python) allows for using an endpoint, but I got the same error as this issue until I scrapped the endpoint and used region instead. I also tried the Speech endpoint from my Speech resource and that "endpoint only" option in the constructor also did not work. The key/region is the only one I got to work for both the Cognitive Services resource and the Speech resource. (I didn't test the host or token constructor options).
