### ISSUE TITLE
GStreamer Speech to Text in Azure Functions

### ISSUE THREAD

**Issue by frigon** [Azure-Samples/cognitive-services-speech-sdk#2401]
I know that support for compressed audio formats is documented [here](https://learn.microsoft.com/en-us/azure/ai-services/speech-service/how-to-use-codec-compressed-audio-input-streams?tabs=windows%2Cdebian%2Cjava-android%2Cterminal&pivots=programming-language-csharp).  While, I **_believe_** it might be possible to implement this in Azure Functions but any examples or documentation as to how is completely lacking.  

I have to assume my use case is common and high volume... I want to upload a compressed audio file (webm opus format)  to blob storage and have an Azure Function run the Speech-to-Text job.

1. Is that even possible?
2. If, so, given it would be common use-case can a github sample or at least some documentation on it be possible to provide.

**Comment by frigon** [comment]
I definitely don't need real-time, streaming transcript but I also don't need "batch".  I only want to process one file at a time and want to process it once received not at some other batching cadence.  So the workflow is essentially receive a single file via an Azure Function save that to blob storage and initiate the transcription it.  If the processing happens offline it's trivial enough to use a storage queue to check the progress of the file.

**Comment by pankopon** [comment]
Hi, unfortunately the Speech SDK support for compressed audio formats requires GStreamer. And if GStreamer is not already included in the OS environment where your application is meant to run, and installation and configuration according to the linked instructions is not possible due to access restrictions or otherwise, then compressed audio just cannot be used as input.

Please note that in addition to batch transcription, compressed audio is also supported by the new [fast transcription API (preview)](https://learn.microsoft.com/azure/ai-services/speech-service/fast-transcription-create) - maybe the latter could be useful for you.
