### ISSUE TITLE
ImportError: cannot import name 'Model'

### ISSUE THREAD

**Issue by dhairyadeewan** [Azure-Samples/cognitive-services-speech-sdk#245]
Cannot check import for swagger_client.
![bug_swagger](https://user-images.githubusercontent.com/21145757/58414581-6dae4580-8099-11e9-8e9e-d51e84e9c203.png)

**Comment by chlandsi** [comment]
This is a [known bug in the swagger autogeneration](https://github.com/swagger-api/swagger-codegen/issues/7541). These can be fixed by deleting the line with the content `    from swagger_client.models.model import Model  # noqa: F401,E501` from the file `swagger_client\models\model.py` and the line with the content `from swagger_client.models.inner_error import InnerError  # noqa: F401,E501` from the file `swagger_client\models\inner_error.py` inside the installed package. The error message will tell you where these files are located for your installation.

**Comment by jhakulin** [comment]
Closed the issue with the current resolution. Let us know if you need more information.
