### ISSUE TITLE
 After real-time speech-to-text conversion in IOS, can the resulting voice file be saved, and where to get it if it is saved?

### ISSUE THREAD

**Issue by pengcheng933** [Azure-Samples/cognitive-services-speech-sdk#2464]
After real-time speech-to-text conversion in IOS, can the resulting voice file be saved, and where to get it if it is saved?

**Comment by pankopon** [comment]
Hi, what do you mean by "the resulting voice file"? If it's really [speech to text](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/swift/ios/from-microphone) that you are using, then the input is audio that you provide and the output is speech recognition results as text. There is no output audio.

**Comment by pengcheng933** [comment]
我使用的是这个(https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/quickstart/objectivec/ios/text-to-speech/README.md)。它是SDK直接从麦克风获取的音频，一边说话一边转文本。我也想得到这份音频，但我找不到再哪儿，SDK也没提到

**Comment by pankopon** [comment]
Your current link points to a **text-to-speech** example ("Quickstart: Synthesize audio in Objective-C on iOS") which is a different thing. But if it's really speech-to-text you are using and you would like to get the original audio that corresponds to the recognized phrase, then unfortunately it's simply not available from the SDK. The input audio is sent to the cloud service (which does not send it back with recognition results) and the SDK does not keep audio that the service has already acknowledged for processing.

The recognition results do report the phrase offset and duration in input audio, so what you could do is use a push or pull audio stream instead of direct microphone audio (see examples in https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/objective-c/ios/speech-samples), meaning that your application reads audio from the microphone (using an appropriate platform API for the purpose) and copies it to the SDK input. Then maintain a buffer of this audio (up to a certain max length at a time) in your app, and use the offset and duration info from recognition results to find the portion that corresponds to the recognized phrase. This would require some additional implementation and logic in your app, however.

**Comment by pengcheng933** [comment]
Thank you very much. This is really helpful.
