### ISSUE TITLE
Function errors deployed via ARM template

### ISSUE THREAD

**Issue by myh-st** [Azure-Samples/cognitive-services-speech-sdk#2524]
Both StartTranscriptionFunction and FetchTranscriptionFunction encounter errors when deployed via ARM template from the provided link

https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/ingestion/ingestion-client/infra/guide.md

![image](https://github.com/user-attachments/assets/7e7cdf00-2ce6-40bd-970b-967288e23a90)

![image](https://github.com/user-attachments/assets/05df24f2-90f6-40ac-b8a6-0e896692f261)

However, these functions work correctly in the older version from this Git repository.

https://github.com/amulchapla/AI-Powered-Call-Center-Intelligence/tree/main/postcall-analytics-azure

**Comment by HenryvanderVegte** [comment]
Hey @myh-st ,

thanks for creating the issue. I was able to reproduce, root cause was that the app config did not load the environment variables correctly and therefore all functions crashed during startup with NullReferenceExceptions. I fixed the issue, it should work again with v2.1.10. 

Thanks!
Henry
