### ISSUE TITLE
UnsatisfiedLinkError: dlopen failed: library "libMicrosoft.CognitiveServices.Speech.core.so" not found:

### ISSUE THREAD

**Issue by fengye11** [Azure-Samples/cognitive-services-speech-sdk#2528]
UnsatisfiedLinkError: dlopen failed: library "libMicrosoft.CognitiveServices.Speech.core.so" not found:

**Comment by pankopon** [comment]
Hi, on the github page of issues there is a "New issue" button:
![image](https://github.com/user-attachments/assets/188111ee-ace4-404b-a13d-09812c8e6bdd)

When you use that, it takes you to a page where you can select whether to file a Bug report or some other type:
![image](https://github.com/user-attachments/assets/7e3d986e-6983-4b2f-94d6-d52579bd7d5d)

And if you select "Bug report" you will be then presented a template that expects you to provide details of the issue, **including** the environment such as specific OS and version, programming language etc.

So please first verify that your system meets the [platform requirements](https://learn.microsoft.com/azure/ai-services/speech-service/quickstarts/setup-platform#platform-requirements) in order to use the Speech SDK, then create a new issue by using the bug template, as this current item is unactionable as is.
