### ISSUE TITLE
Are samples using conversation-transcription-service available on Github?

### ISSUE THREAD

**Issue by takuto-yamada** [Azure-Samples/cognitive-services-speech-sdk#257]
I have verified how to use the speech transcription service, but I do not understand how to implement it.
Do you have a simple sample program?
I would like to create an app like the MS-Build demo that took place in May.

https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-conversation-transcription-service

**Comment by jhakulin** [comment]
Thanks for the comments, currently there is sample under Speech Devices SDK:

https://github.com/Azure-Samples/Cognitive-Services-Speech-Devices-SDK/blob/master/Samples/Android/Speech%20Devices%20SDK%20Starter%20App/example/app/src/main/java/com/microsoft/coginitiveservices/speech/samples/sdsdkstarterapp/conversation.java

Let us know if you need more information to use Speech Devices SDK sample or some other details which you need in order to implement the functionality you need.

**Comment by takuto-yamada** [comment]
Thank you for your reply.

I am implementing Speech-to-Text function using Speech SDK (JavaScript) to build Web application now. 
And  I would like to Add　Build a mechanism to determine who spoke at a web conference.
Can I implement conversation-transcription with Speech SDK (JavaScript)?

**Comment by rhurey** [comment]
The JavaScript client doens't have the transcription recognizer implemented. We do have plans to add it.

**Comment by takuto-yamada** [comment]
Thank you for answering.
I am looking forward.
