### ISSUE TITLE
About ASR incorrectly recieves TTS although I have even muted the microphone and set asr_active flag to disable the recognized activity.Please help!

### ISSUE THREAD

**Issue by phoenixdna** [Azure-Samples/cognitive-services-speech-sdk#2608]
I found quite frustrating while I trying to use the TTS combine with azure 's ASR . For some reason, The TTS output was received by ASR incorrectly even if I mute the microphone with Pyaudio. So please someone help 

### The Code pieces
```
def text_to_speech(text):
    
    speech_config2 = speechsdk.SpeechConfig(subscription='xxx', region='eastasia')
    audio_config2 = speechsdk.audio.AudioOutputConfig(use_default_speaker=True)

    # The neural multilingual voice can speak different languages based on the input text.
    speech_config2.speech_synthesis_voice_name='zh-CN-XiaoyiNeural'
    speech_synthesizer = speechsdk.SpeechSynthesizer(speech_config=speech_config2, audio_config=audio_config2)

    # Get text from the console and synthesize to the default speaker.
    

    global asr_active
    asr_active = False
    mute_microphone()
    #speech_recognizer.stop_continuous_recognition()
    time.sleep(1)
    print("《《《《《《《《《《《tts=>>>",text)
    speech_synthesis_result = speech_synthesizer.speak_text_async(text).get()
    print("tts=>》》》》》》》》》》》》》》》》》>>")

    time.sleep(1)
    asr_active = True
    unmute_microphone()

    #speech_recognizer.start_continuous_recognition()
```

### System output
final response recived
model response: 很抱歉，我无法提供实时的日期信息。请您查看您的电子设备或询问您的语音助手来获取今天的日期。
microphone muted
《《《《《《《《《《《tts=>>> 很抱歉，我无法提供实时的日期信息。请您查看您的电子设备或询问您的语音助手来获取今天的日期。
tts=>》》》》》》》》》》》》》》》》》>>
Speech synthesized for text [很抱歉，我无法提供实时的日期信息。请您查看您的电子设备或询问您的语音助手来获取今天的日期。]
microphone UNmuted
RECOGNIZED: SpeechRecognitionEventArgs(session_id=cf14ed11f79a444faa988fab687687c0, result=SpeechRecognitionResult(result_id=96877e5119b74d2e9f7b394072741b87, text="很抱歉，我无法生气。", reason=ResultReason.RecognizedSpeech))
sent to model reached

### Question:
As you can seen in the code, even I muted the microphone during speech_synthesizer.speak_text_async(text).get(), I still can see some of the words has been incorrectly received in speech_recognizer,

RECOGNIZED: SpeechRecognitionEventArgs(session_id=cf14ed11f79a444faa988fab687687c0, result=SpeechRecognitionResult(result_id=96877e5119b74d2e9f7b394072741b87, text="很抱歉，我无法生气。", 

I don't know why ASR can recognize the TTS voice although I have muted microphone, actrually I also add the active flag in callback function of SpeechRecognizer.recognized, but no help..., so please help ,Thx in advance.

**Comment by pankopon** [comment]
Hi, you can see that it's actually just what looks like the very beginning of the TTS output that is recognized. So the microphone appears to remain open for enough time to capture that, still. Does your `mute_microphone()` using Pyaudio really mute the microphone at once or even within a 1 second delay (as you are calling `time.sleep(1)` right after)?

Test this by running only speech recognition and call the same function to mute the microphone while you are continuously speaking - do "recognizing" results end so quickly? See https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1793 for alternative mute/unmute (though Linux-only, but you didn't tell about your system). Otherwise try increasing the time to sleep before TTS by a couple of seconds.

Just to note, if you intend to use the default speaker for output then you don't actually need to specify `audio_config` for `speech_synthesizer`.

**Comment by phoenixdna** [comment]
Thank u very much for your detailed feed back, I have tried and you are right about the mute_microphone doesnt' work at all even I delete the code, currently I avoid this by specifically use the threading to handle the TTS while I am having ASR as the main programme. I am not sure why this had happened though.

**Comment by pankopon** [comment]
Maybe Pyaudio at least cannot mute the microphone if it's already reserved and in use for recognition by the SDK. Alternatively you could stop recognition before TTS and start again after TTS, but it can add some delay and looks like you already tried it as well.

It's fine to use `audio_config` of `use_default_speaker=True`, it's just redundant because that's already the internal default for `SpeechSynthesizer`. Similar thing with `SpeechRecognizer`, if you use the system default microphone for input then you are not required to specify `audio_config` (although it doesn't matter if you do).

**Comment by pankopon** [comment]
Closed as answered since no further questions received.
