### ISSUE TITLE
Can I use SDK on CentOS7.9 my  programming language is python

### ISSUE THREAD

**Issue by changingshow** [Azure-Samples/cognitive-services-speech-sdk#2641]
cat /etc/centos-release
CentOS Linux release 7.9.2009 (Core)
My server system version is CentOS7.9，Can I use SDK on this system? my  programming language is python。What does the following picture mean？This SDK does not support CentOS7.9？
![image](https://github.com/user-attachments/assets/984e56a4-36f4-4201-8e22-b8a24a0b8119)

**Comment by pankopon** [comment]
Hi, CentOS 7 is not supported anymore due to its **end-of-life** as explained in SDK release notes. Please note that this is not a Speech SDK specific thing, it is a general Microsoft policy. Unfortunately we cannot provide support for older SDK releases on CentOS 7 either.

To emphasize, CentOS 7 is now out of support by its original vendor. This means that unless you are actively monitoring and fixing security issues by yourself or receiving support from some third party, your server system can become very vulnerable. We can only recommend migrating to a newer OS as soon as possible.

Current Linux environments supported by the Speech SDK:
https://learn.microsoft.com/en-us/azure/ai-services/speech-service/quickstarts/setup-platform?tabs=linux&pivots=programming-language-python#platform-requirements
