### ISSUE TITLE
Geting error --No speech could be recognized with azure.cognitiveservices.speech in python from microphone

### ISSUE THREAD

**Issue by rsougata** [Azure-Samples/cognitive-services-speech-sdk#393]
I am geting error -- **No speech could be recognized** with azure.cognitiveservices.speech SDK in Python environment. bellow is my code 

 speech_config = speechsdk.SpeechConfig(subscription=speech_key, region=service_region)

    # Creates a recognizer with the given settings
    audio_config=speechsdk.audio.AudioConfig(use_default_microphone=True)
    speech_recognizer=speechsdk.SpeechRecognizer(speech_config=speech_config, audio_config=audio_config)

    speech_recognizer.recognized.connect(lambda evt: print('\n{}'.format(evt.result.text)))

    print("Say something...")

    time.sleep(10)

    result = speech_recognizer.recognize_once()

    # Check the result
    if result.reason == speechsdk.ResultReason.RecognizedSpeech:
        print("Recognized: {}".format(result.text))
    elif result.reason == speechsdk.ResultReason.NoMatch:
        print("No speech could be recognized")
    elif result.reason == speechsdk.ResultReason.Canceled:
        cancellation_details = result.cancellation_details
        print("Speech Recognition canceled: {}".format(cancellation_details.reason))
        if cancellation_details.reason == speechsdk.CancellationReason.Error:
            print("Error details: {}".format(cancellation_details.error_details))

Can any one help me out

**Comment by jhakulin** [comment]
Thanks for question,
I wonder why you have time.sleep(10) in the script ?
speech_recognizer.recognize_once() is blocking call and will return after you have said something.
I can see your script fails with No speech could be recognized if you have 10sec sleep there and you said all words before recognize_once is started.

**Comment by rsougata** [comment]
Hi jhakulin, 
Thanx for the reply,
I have removed the syntax  **time.sleep(10)**, but the same error i am getting.
if i send the recorded voice as WAV format file its working , bellow is the code to send recorded voice as WAV format.

speech_config = speechsdk.SpeechConfig(subscription=speech_key, region=service_region)
    audio_config = speechsdk.audio.AudioConfig(filename=path)
    speech_recognizer = speechsdk.SpeechRecognizer(speech_config=speech_config, audio_config=audio_config)
 result = speech_recognizer.recognize_once()
    if result.reason == speechsdk.ResultReason.RecognizedSpeech:
        print("Recognized: {}".format(result.text))
    elif result.reason == speechsdk.ResultReason.NoMatch:
        print("No speech could be recognized: {}".format(result.no_match_details))
    elif result.reason == speechsdk.ResultReason.Canceled:
        cancellation_details = result.cancellation_details
        print("Speech Recognition canceled: {}".format(cancellation_details.reason))
        if cancellation_details.reason == speechsdk.CancellationReason.Error:
            print("Error details: {}".format(cancellation_details.error_details))

above code giving me the actual result, but if i send the voice through the mic, i am  getting  error

**Comment by jhakulin** [comment]
In my side your code works ok with microphone, tested on Windows 10. 
Have you verified your microphone setup works OK?
Which OS you are using ?

**Comment by rsougata** [comment]
Thx jhakulin, for the reply.
i am using mac OS Mojave 10.14.6, 

I have verified the mic also, i can able to record the voice through my default mic.

Please help me out

**Comment by jhakulin** [comment]
@rsougata Do you have some external mic (headset or USB) or using integrated mic as default ?
Could you try to record 16khz PCM to wav file, e.g. using arecord and see if that works ok ?
Based on the information given, microphone is probably set-up correctly but since you get "No speech could be recognized" error, the problem could be e.g. low level signal from microphone, which is not detected by speech recognition engine.

**Comment by jhakulin** [comment]
@rsougata did you find out solution for the issue ?

**Comment by rsougata19** [comment]
NO @jhakulin ,

I think azure.cognitiveservices.speech SDK dose not support  ma4 format sound, that's why it is not working. Actually when you recording the voice through the mic in mac , it is passing the voice to cognitive speech as a ma4 format, and the  cognitive speech sdk dose not support ma4.

**Comment by jhakulin** [comment]
@rsougata How did you record .m4a format ? Using QuickTime player to capture audio probably gives you .m4a recording as an outcome, however PCM should be the format from your Mac's microphone driver. If you try to record e.g. 5sec audio using "sox -d recording.wav trim 0 5", you should get PCM audio recording.

I just verified on macOS Mojave 10.14.5, python quickstart with microphone works OK with Speech SDK 1.7.0. So I believe error is due to your Mac sound configuration.

**Comment by rsougata19** [comment]
Thanks for the reply --Jhakulin,
 I will check it with macOS again, and will let you know.

**Comment by wolfma61** [comment]
closing
