### ISSUE TITLE
Text-to-speech .NET Core basic example hangs only on Windows

### ISSUE THREAD

**Issue by pviotti** [Azure-Samples/cognitive-services-speech-sdk#454]
**Describe the bug**
A [very basic text-to-speech example](https://github.com/pviotti/sayit) in F# works perfectly on Linux but sometimes (often) hangs or gives garbled output on windows.  
This happens only when pronouncing a string directly, not when the output is a file.

**To Reproduce**
Steps to reproduce the behavior, on a PowerShell console on Windows 10:
1. `git clone https://github.com/pviotti/sayit`
2. `cd sayit/SayIt`
3. `dotnet run --setup`
3. `dotnet run hello`

It hangs instead of pronouncing the "hello" string.  
If executed from VS2019 sometimes it plays part of the audio.

**Expected behavior**
It just plays "hello" and exits normally - as it does on Linux.

**Version of the Cognitive Services Speech SDK**
1.8.0

**Platform, Operating System, and Programming Language**
 - OS: Windows
 - Hardware: x64
 - Programming language: F#

**Additional context**
There's no error from the API, so I suppose there's some race condition or incompatibility when playing the audio locally that prevents the audio from being played and makes the whole application hang.  
In fact, if you use the write to audio feature (`dotnet run -o output.mp3 hello`) it works just fine.  
Any idea of what might be causing this and on how to prevent it?

**Comment by yulin-li** [comment]
Hi @pviotti 
Thanks for your feedback. I was trying to repro your bug. The codes pronounced "hello" in my machine and it hung. I found the reason is that the `SpeechSynthesisResult` was not disposed.

I added `task.Result.Dispose()` in your code at [this line](https://github.com/pviotti/sayit/blob/master/SayIt/Program.fs#L30) and then it works and exits normally. You can add this as a workaround, and we will take further look.
