### ISSUE TITLE
DllNotFoundException in ASP.NET Core 3.1 Docker container

### ISSUE THREAD

**Issue by sibbl** [Azure-Samples/cognitive-services-speech-sdk#481]
**Describe the bug**

I'd like to build a docker container of my ASP.NET Core 3.1 application which uses the Speech SDK.

Unfortunately I get the following exception as soon as `SpeechConfig.FromEndpoint(any(Uri), any(string))` is called: 
```
DllNotFoundException: Unable to load shared library 
'libMicrosoft.CognitiveServices.Speech.core.so' or one of its dependencies.
In order to help diagnose loading problems, consider setting the LD_DEBUG
environment variable: liblibMicrosoft.CognitiveServices.Speech.core.so:
cannot open shared object file: No such file or directory
```

I'm building it with the "bionics" base images from Microsoft, which is based on Ubuntu 18.04. As far as I read this should be supported.

I've provided a small test project which can be run as is to reproduce the issue: [SpeechSdkDockerTestProject.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/4058289/SpeechSdkDockerTestProject.zip)

**To Reproduce**
1. Open the project above in Visual Studio (2019, Windows, all updates installed)
2. Run the "Docker" target
3. Wait until `/helloworld` is loaded in your browser or open it yourself

**Expected behavior**
The string "hello world" should be returned instead of the exception above.

**Version of the Cognitive Services Speech SDK**
1.8.0
**Platform, Operating System, and Programming Language**
 - OS: Windows
 - Hardware: x64
 - Programming language: C#
 - Browser doesn't matter

**Additional context**
 - I'm using Linux containers in Docker v2.1.0.5
- running `cat /etc/os-release` inside the Docker container returns `Ubuntu 18.04.3 LTS (Bionic Beaver)`
- the runtimes directory including the `*.so` libs exist in the container

**Comment by Curious425** [comment]
In addition to ensuring the so file is there, have you set your LD_LIBRARY_PATH to include that location.

Also, did you install openssl and libasound packages inside the docker image?

https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/quickstart/cpp/linux/from-microphone/README.md

**Comment by sibbl** [comment]
@Curious425 thanks a lot, that helped me solving it! Indeed these packages were missing in my container. No `LD_LIBRARY_PATH` was necessary though.

**Comment by kiran9879** [comment]
Hi, can you specify what exactly solved your problem? I am having the same issue on Debian 10.

**Comment by sibbl** [comment]
@kiran9879 I ran the `apt-get` commands from the linked readme (see above) at the beginning of my Dockerfile.

**Comment by trenslow** [comment]
For anyone running their .NET Core 3.1 application using the official image (whose base is Debian 10), I simply had to install the libasound2 library for our application to use the Microsoft.CognitiveServices.Speech package. Here's all I needed to add to the Dockerfile:

```
RUN apt-get update
RUN apt-get -y install libasound2
```

It would be nice if Microsoft could update their documentation to make it more clear what exactly is required to add on to their official Linux images in order to be able to use the Speech service.

**Comment by pankopon** [comment]
Please note that Linux system requirements are stated on the "About the Speech SDK" page:
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-sdk?tabs=linux
Debian 10 is not yet officially supported, but in practice you just need to install the same packages as on Debian 9, incl. libasound2. For libssl, use libssl1.1 instead of libssl1.0.2.
