### ISSUE TITLE
Source language recognition not working

### ISSUE THREAD

**Issue by hramoser** [Azure-Samples/cognitive-services-speech-sdk#503]
Source language recognition is not working for the service region westeurope. 
The application receives a SpeechStartDetected event followed by ResultReason::NoMatch.
Without language recognition the programs works as expected. The program uses StartContinuousRecognitionAsync().

Tested with C++ SDK 1.9 on Ubutu 18.04.

**Comment by fmegen** [comment]
can you please verify that you get a recognized text for the input when not using Language detection.

does the input have a huge amount of silence in the beginning? language detection will fail if silence is too long.

**Comment by fmegen** [comment]
in case you still have issues, please provide a session id so we can debug this in more details on the service side.

**Comment by hramoser** [comment]
First of all - thanks for the quick response.
The audio sample is the word "quit" followed by silence. There is only very brief silence before the utterance. (I am using this for unit tests.)
The text is recognized without language recognition.
Maybe you have time to take a look at this session id: 89f2b1634ebb4194a023cd8105a7a1d2

**Comment by fmegen** [comment]
thanks a lot for the info.
i checked the service logs for your session id.
language detection reported an error indicating that it could not detect the language from the audio.
in this case, NoMatch is returned to the client without any further result (i.e., this is expected behavior).

please run your tests with input that contains at least 3-5 seconds of audio.

please let me know if that fixed your issues.

**Comment by hramoser** [comment]
Ok, this was the issue. Long audio works fine.
The problem is that for our use case people often respond with "yes", "no", etc. (but in a variety of languages).
Thank you for your assistance.
I will close now this issue.

**Comment by hramoser** [comment]
Resolved.
