### ISSUE TITLE
Redundant voice assistant sample/quick start app?

### ISSUE THREAD

**Issue by managedcoder** [Azure-Samples/cognitive-services-speech-sdk#540]
I've been researching how to build a voice assistant with the DirectLineSpeech channel and I've run into what looks to be two different version of the same sample app.  The first can be found in the "master/samples" folder in the Speech SDK [here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/csharp/uwp/virtualassistant-uwp) and the other can be found in the "master/quickstart" folder in the Speech SDK [here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/csharp/uwp/virtual-assistant).  Are these essentially the same sample app but just slightly different versions?  Why are both needed?  Would one sample be less confusing?

**Comment by trrwilson** [comment]
Thanks for raising this issue -- and apologies it's taken so long to get a response!

You're quite right that the difference between the quickstart and sample is subtle. The biggest difference is that the "sample" version has some additional supporting code for cleaner result displays and audio streaming -- this makes getting things running slightly less "quick," hence why it's moved out as a sample.

I agree there's some room for making this more clear and I've opened a work item on our team to either consolidate the two or integrate more changes for a more meaningful difference.

Separately, because you're looking at the UWP sample, we also recently published a much more comprehensive sample that includes upcoming Windows Assistant integration along with Direct Line Speech (you can use pieces just for the latter as needed); you can find this at http://aka.ms/mva/sample. We're making updates to the docs now to cross-link to this and I anticipate that that this newer sample will be the more definitive "sample" resource (versus the quickstart).

Thank you!
