### ISSUE TITLE
about the PHP script for JS speech sdk

### ISSUE THREAD

**Issue by inglesuniversal** [Azure-Samples/cognitive-services-speech-sdk#547]
is there any advantage of including this code? (eg. faster process) 

can the PHP file be hosted and accessed from a remote site (cors previously set up) ?

best regards

PS.- Where can I access the change logs for the JS SDK? Thanks

**Comment by rhurey** [comment]
The token.php script is offered as a sample of how to use Auth tokens instead of the subscription key with the JS SDK in a browser.

The theory is you can control access to the php script on your site, and it will generate a limited use token to send to the browser to enable speech recognition.

If you sent the speech key to the browser, someone could read the key from the script at use it freely.

The JS SDK's source is at: https://github.com/microsoft/cognitive-services-speech-sdk-js

**Comment by jhakulin** [comment]
Closing, if there is more information needed, please let us know.
