### ISSUE TITLE
How to make the Recognizer recognize an OPUS or RAW PCM encoded file

### ISSUE THREAD

**Issue by viju2008** [Azure-Samples/cognitive-services-speech-sdk#588]
Hello,

Language Used: JAVA  1.8 on Windows

I have RAW PCM as well as OPUS files which i need to pass to the recognizer and get the speech recognition result.

I tried various options in the speech recognizer in java however it is not working.

Can anyone please guide me how to use the SDK to POST OPUS or RAW PCM files to the speech recognition (REST or WEBSOCKET ENDPOINT) and get the output transcript.

Currently i am able to do get output only with WAV files

Code I have tried..

InputStream inputStream = new FileInputStream("F:\\Welcome.opus");

        com.microsoft.cognitiveservices.speech.internal.AudioStreamContainerFormat as =com.microsoft.cognitiveservices.speech.internal.AudioStreamContainerFormat.OGG_OPUS;
        
        PushAudioInputStream pushStream = AudioInputStream.createPushStream(AudioStreamFormat.getCompressedFormat(as));
        
        AudioConfig audioInput = AudioConfig.fromStreamInput(pushStream);

    SpeechRecognizer recognizer = new SpeechRecognizer(config, audioInput);
        {
            // Subscribes to events.
            recognizer.recognizing.addEventListener((s, e) -> {
                System.out.println("RECOGNIZING: Text=" + e.getResult().getText());
            });

**Comment by pankopon** [comment]
Hi, in order to use compressed audio input on Windows, first do the following steps:

1. Make sure you are using the Speech SDK version 1.11.0 or newer.
2. If you don't already have GStreamer for Windows installed, download https://gstreamer.freedesktop.org/data/pkg/windows/1.14.4/gstreamer-1.0-x86_64-1.14.4.msi and install. Note the target location!
3. Add the GStreamer bin directory to your system path. For example, if GStreamer was installed to `C:\gstreamer` then add `C:\gstreamer\1.0\x86_64\bin` to PATH (open Control Panel, go to System - Advanced system settings - Environment Variables, and modify PATH).

Example code for using an OPUS input file (with a pull stream):

```
import com.microsoft.cognitiveservices.speech.*;
import com.microsoft.cognitiveservices.speech.audio.*;
import com.microsoft.cognitiveservices.speech.internal.AudioStreamContainerFormat;
// ...
SpeechConfig config = SpeechConfig.fromSubscription(YourSubscriptionKey, YourServiceRegion);
String filePath = "YourOpusFile.opus";

AudioStreamFormat audioFormat = AudioStreamFormat.getCompressedFormat(AudioStreamContainerFormat.OGG_OPUS);
PullAudioInputStream pullStream = AudioInputStream.createPullStream(new BinaryAudioStreamReader(filePath), audioFormat);

AudioConfig audioInput = AudioConfig.fromStreamInput(pullStream);
SpeechRecognizer recognizer = new SpeechRecognizer(config, audioInput);
```

For the input stream, you need some implementation of a binary file reader. This example uses
https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/java/android/compressed-input/app/src/main/java/com/microsoft/cognitiveservices/speech/samples/compressedinput/BinaryAudioStreamReader.java
If you want to use it, copy the file to your project and modify the package statement at the top of the file.

**Comment by viju2008** [comment]
Thank now I am able to send the OPUS file with the Above code. 

How do i send RAW PCM file. 

However i noticed that when i use OPUS the response time is higher than that for WAV. Any scope for performance optimization here. The File size of OPUS is considerably smaller than wav hence i am trying with OPUS.

**Comment by pankopon** [comment]
For a raw PCM input file, please try the following code

```
String filePath = "YourPcmFile.pcm"; // 16kHz, 16-bit, 1 channel
AudioStreamFormat audioFormat = AudioStreamFormat.getWaveFormatPCM((long)16000, (short)16, (short)1);
PullAudioInputStream pullStream = AudioInputStream.createPullStream(new PcmFileAudioInputStream(filePath), audioFormat);
AudioConfig audioInput = AudioConfig.fromStreamInput(pullStream);
```

and use/adapt the attached example of PcmFileAudioInputStream class in you project (at minimum, adjust the package statement at the top).
[PcmFileAudioInputStream.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/4513327/PcmFileAudioInputStream.zip)

The response time with compressed audio like OPUS is higher because the audio is uncompressed locally by GStreamer before it is sent to the service, which adds some delay. We will note this for potential future improvements.

If you have use cases where real-time operation is not required, there's also the batch transcription REST API:
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/batch-transcription

**Comment by pankopon** [comment]
To add, you may simply just rename PcmFileAudioInputStream to BinaryAudioStreamReader and use it instead of the previous BinaryAudioStreamReader implementation, it works either way.

**Comment by viju2008** [comment]
I am Websocket endpoint as i plan to move to containerized version of speech to text. Containzers i believe dont support REST as of now.
Do containers support batch operations ?

**Comment by viju2008** [comment]
> For a raw PCM input file, please try the following code
> 
> ```
> String filePath = "YourPcmFile.pcm"; // 16kHz, 16-bit, 1 channel
> AudioStreamFormat audioFormat = AudioStreamFormat.getWaveFormatPCM((long)16000, (short)16, (short)1);
> PullAudioInputStream pullStream = AudioInputStream.createPullStream(new PcmFileAudioInputStream(filePath), audioFormat);
> AudioConfig audioInput = AudioConfig.fromStreamInput(pullStream);
> ```
> 
> and use/adapt the attached example of PcmFileAudioInputStream class in you project (at minimum, adjust the package statement at the top).
> [PcmFileAudioInputStream.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/4513327/PcmFileAudioInputStream.zip)
> 
> The response time with compressed audio like OPUS is higher because the audio is uncompressed locally by GStreamer before it is sent to the service, which adds some delay. We will note this for potential future improvements.
> 
> If you have use cases where real-time operation is not required, there's also the batch transcription REST API:
> https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/batch-transcription

Instead of gstreamer i beleive the LIBOPUS library could included inside the Java SDK and jni call could be made. May be it will speed up things

**Comment by amitkumarshukla** [comment]
@viju2008 what is your scenario with OPUS. In speech SDK we do not send compressed data to the service. We currently decode the OPUS using gstreamer and send the PCM data to the service. Do let us know if you are looking for the same use case.

**Comment by pankopon** [comment]
Closing this issue, since the original questions were answered and there are no further updates. We have a backlog item for creating a how-to on push/pull streams, in order to make it easier to use them in the future.
