### ISSUE TITLE
Access Docker Luis Image

### ISSUE THREAD

**Issue by tonyalves** [Azure-Samples/cognitive-services-speech-sdk#617]
I just downloaded the docker container of Luis and I successfully deployed and run on my machine, but a I can't access the endpoint from my application. I tried run with "`SpeechConfig config = SpeechConfig.fromEndpoint(new URI("http://localhost:5000"));` ", but I got this error:
`[2020-05-02 20:37:39] [INFO   ] STARTING 
[2020-05-02 20:37:40] [INFO   ] IntentRecognitionResult result = recognizer.recognizeOnceAsync().get() 
[2020-05-02 20:37:40] [INFO   ] CANCELED: ErrorCode=ConnectionFailure 
[2020-05-02 20:37:40] [INFO   ] CANCELED: ErrorDetails=Runtime error: Failed to create transport request. SessionId: b7a9fcd70f6842eb966ff10d33876ce7 
[2020-05-02 20:37:40] [INFO   ] CANCELED: Did you update the subscription info? `
Anyone knows how I fix this?

**Comment by rhurey** [comment]
There's a detailed discussion here: https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/424

The short version is that today for containers the stitching that exists in the Azure cloud services between speech recognition and LUIS hasn't made it into a single container.

The IntentRecognizer (generally) depends on the cloud service to stitch the speech and LUIS services into a single cloud request. (Generally because there is some basic string matching capability in the recognizer, but matching doesn't involve LUIS.)

**Comment by tonyalves** [comment]
> There's a detailed discussion here: #424
> 
> The short version is that today for containers the stitching that exists in the Azure cloud services between speech recognition and LUIS hasn't made it into a single container.
> 
> The IntentRecognizer (generally) depends on the cloud service to stitch the speech and LUIS services into a single cloud request. (Generally because there is some basic string matching capability in the recognizer, but matching doesn't involve LUIS.)

I understand. thanks.
