### ISSUE TITLE
When the KWS is enabled the TTS stops working

### ISSUE THREAD

**Issue by raafaelima** [Azure-Samples/cognitive-services-speech-sdk#651]
Hi Everyone,

Im using the VAClient as base implementation. When I say the keyword, The app wake, show the animation, as expected. However do not show any signs of recognising my voice from the wake moment, even when I click on the microfone icon. 

When I try to use the ```botConnector.startKeywordRecognitionAsync(model) ``` instead, on the recognized section, they return to me the Keyword name plus my actual command. Instead of getting **Do This**, im getting **Computer, Do This.**

Am I doing something wrong?

Im using the new released SDK: 
> com.microsoft.cognitiveservices.speech:client-sdk:1.12.0

Here is the code Sample:

```
KeywordRecognizer keywordRecognizer = new KeywordRecognizer(AudioConfig.fromDefaultMicrophoneInput());
final KeywordRecognitionModel model = KeywordRecognitionModel.fromStream(inputStream, keyword, false);
final Future<KeywordRecognitionResult> task = keywordRecognizer.recognizeOnceAsync(model);

keywordRecognizer.recognized.addEventListener((o, speechRecognitionResultEventArgs) -> {
      final KeywordRecognitionResult result = speechRecognitionResultEventArgs.getResult();
      if (result.getReason() == ResultReason.RecognizedKeyword) {
        EventBus.getDefault().post(new BotListening());
        botConnector.listenOnceAsync(); 
     } else {
        LogException("Error: got the wrong sort of recognition.");
    }
});

botConnector.recognized.addEventListener((o, speechRecognitionResultEventArgs) -> {
   final String recognizedSpeech = speechRecognitionResultEventArgs.getResult().getText();
   LogInfo("Final result received: " + recognizedSpeech); //NEVER GET HERE
});
```

**Comment by raafaelima** [comment]
Duplicate

**Comment by jhakulin** [comment]
@raafaelima Thanks for your report, I can see that there is a problem with Android microphone control inside Speech SDK. Speech SDK for Android currently has limitation to support only single microphone access at the same time. In your scenario botConnector tries to access microphone while keywordRecognizer still owns it which leads to the issue. If you arrange your code so that keywordRecognizer is e,g, closed before listenOnceAsync is called, you should get result correctly.

We will work on this limitation for microphone handling in Speech SDK for Android.

Related to botConnector.startKeywordRecognitionAsync(model), indeed keyword is included in the result currently. Using this method one solution for you could be to strip the keyword from the result in your app.
