### ISSUE TITLE
[Android] Issue with Silence Timeout

### ISSUE THREAD

**Issue by xymelon** [Azure-Samples/cognitive-services-speech-sdk#669]
**Describe the bug**
Silence timeout not working when I set `SpeechServiceConnection_InitialSilenceTimeoutMs` and `SpeechServiceConnection_EndSilenceTimeoutMs` in SpeechConfig.

**To Reproduce**
1. Run sdk demo, download from [speech-devices-sdk-quickstart](https://docs.microsoft.com/zh-cn/azure/cognitive-services/speech-service/speech-devices-sdk-quickstart?pivots=platform-android).
2. Set custom silence timeout's properties, eg. `speechConfig.setProperty(PropertyId.SpeechServiceConnection_EndSilenceTimeoutMs, "5000");` .
3. Start SpeechRecognizer#recognizeOnceAsync, you will find end silence timeout does not work.

**Version of the Cognitive Services Speech SDK**
implementation 'com.microsoft.cognitiveservices.speech:client-sdk:1.12.0'.

**Platform, Operating System, and Programming Language**
 - Android

**Comment by xymelon** [comment]
All code comes from [Android SDK zip](https://docs.microsoft.com/zh-cn/azure/cognitive-services/speech-service/speech-devices-sdk#get-the-speech-devices-sdk).
Examples：
`
final SpeechRecognizer reco = new SpeechRecognizer(this.getSpeechConfig(), this.getAudioConfig());
reco.recognizing.addEventListener((o, speechRecognitionResultEventArgs) -> {
    final String s = speechRecognitionResultEventArgs.getResult().getText();
    Log.i(logTag, "Intermediate result received: " + s);
    setRecognizedText(s, true);
});
final Future<SpeechRecognitionResult> task = reco.recognizeOnceAsync();

private AudioConfig getAudioConfig() {
    // run from the microphone
    return AudioConfig.fromDefaultMicrophoneInput();
}

public static SpeechConfig getSpeechConfig() {
    SpeechConfig speechConfig = SpeechConfig.fromSubscription(SpeechSubscriptionKey, SpeechRegion);

    speechConfig.setProperty(PropertyId.SpeechServiceConnection_InitialSilenceTimeoutMs, "5000");
    speechConfig.setProperty(PropertyId.SpeechServiceConnection_EndSilenceTimeoutMs, "5000");
    speechConfig.setSpeechRecognitionLanguage(LanguageRecognition);

    return speechConfig;
}
`

**Comment by pankopon** [comment]
What is the actual Android device being tested? The Speech **Devices** SDK for Android only supports Roobo v1 at the moment (ref. https://docs.microsoft.com/en-US/azure/cognitive-services/speech-service/speech-devices-sdk).

For Android phones, use the Speech SDK directly with quickstart samples like
https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/java/android/from-microphone.

In either case, just to confirm the usage:

- InitialSilenceTimeoutMs is the max amount of silence at the beginning of input that the service waits for before it stops recognition (returns "no match") due to no speech. The current defaults are 5s with recognizeOnceAsync and 15s with startContinuousRecognitionAsync. The actual elapsed time will include some other delays, so it won't be exactly the same as the timeout value in any case.
  - This is easy to verify by not saying anything and waiting for a "no match" result.

- EndSilenceTimeoutMs is the max amount of silence after the last recognized speech, that the service waits for before it stops recognition. However, in case of continuous recognition the Speech SDK does automatically resume it, so in practice continuous recognition remains active until stopContinuousRecognitionAsync is called.
  - One way to verify the effect of EndSilenceTimeoutMs is to first say something that gets recognized, then wait and not say anything until the next "no match" result - the time taken will be EndSilenceTimeoutMs + InitialSilenceTimeoutMs (+ some). The default value of EndSilenceTimeoutMs in continuous recognition is 20s.
  - With recognizeOnceAsync the default is 2s but only a single recognition is done anyway.

**Comment by pankopon** [comment]
Closing the issue, as we have verified the functionality of silence timeout parameters with the current latest Speech SDK release and samples based code on Android. Please refer to the previous comment for clarifications on their usage, and re-open or create a new item for any further issues in this matter.

**Comment by mackwu828** [comment]
@pankopon i am facing the same issue

```
speechConfig.setProperty(PropertyId.SpeechServiceConnection_EndSilenceTimeoutMs, "5000");
```

when i say something, speechRecognizer.recognized alreay invoked, and wait 2 seconds when i continue say something，nothing happed.

**Comment by IhorKirei** [comment]
Same thing

**Comment by jychoudh** [comment]
@mackwu828 As pankopon mentioned above, `recognizeOnceAsync` will only do a single recognition. So, if you say, "I have an appointment tomorrow afternoon" with 2 seconds pause between the words "appointment" and "tomorrow", the recognized event will be fired after the word "appointment" and the recognized text will be "I have an appointment".
