### ISSUE TITLE
[Multi-Device Conversation] Exception with an error code: 0x2b (SPXERR_UNSUPPORTED_API_ERROR)

### ISSUE THREAD

**Issue by cdumon** [Azure-Samples/cognitive-services-speech-sdk#672]
**Describe the bug**
So I was trying to manage the participants in a multi-device conversation, and when trying to add a Participant using:
```cpp
public inline std::future< std::shared_ptr<Participant> > AddParticipantAsync (const std::shared_ptr<Participant>& participant);
```
, the program fails and breaks, and SPXERR_UNSUPPORTED_API_ERROR is raised;

**To Reproduce**
1. Create a sample program using this quickstart: https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/quickstarts/multi-device-conversation?pivots=programming-language-cpp
2. Insert this bit of code:
```cpp
conversationTranslator->JoinConversationAsync(conversation, "Host").get();
conversationTranslator->StartTranscribingAsync().get();
auto participant = Participant::From("user@example.com", "en-us");
try {
    conversation->AddParticipantAsync(participant).get();
}
catch (const std::runtime_error& e) {
    std::cerr << "Runtime Error: " << e.what() << std::endl;
}
```
**Expected behavior**
I can add a Participant in the conversation in order to make use of the Conversation class's member:
```cpp
public const std::vector<std::shared_ptr<Participant>> & Participants;
```
to retrieve the list of participants later on.

**Version of the Cognitive Services Speech SDK**
1.12.0 NuGet Package

**Platform, Operating System, and Programming Language**
 - OS: Windows 10 Home Edition
 - Hardware - x64
 - Programming language: C++

**Additional context**
After investigating, I found this stacktrace:

![image](https://user-images.githubusercontent.com/41568720/83633794-cc0dde00-a5a1-11ea-969c-f27641e95dc3.png)

As you can see, SPX_UNSUPPORTED_API_ERROR is raised. Unfortunately, I searched everywhere to find informations on this code, without any success.

While trying to navigate to the source of the issue, I stumbled upon this bit of code that does explain that "The API is not applicable":
#### **`spxerror.h`**
```cpp
/// <summary>
/// The API is not applicable.
/// Added in version 1.5.0.
/// </summary>
#define SPXERR_UNSUPPORTED_API_ERROR  __SPX_ERRCODE_FAILED(0x02B)
```

Does anybody knows what precisely is causing this error to show up and what the SDK means by "The API is not applicable" ?

I would be really grateful if you guys could enlighten me!

**Comment by amitkumarshukla** [comment]
Thanks a lot for filing the issue. We will get back to you very soon.

**Comment by pankopon** [comment]
@ralph-msft @lisaweixu Can you please have a look, is this a genuine bug?

**Comment by ralph-msft** [comment]
The typical case for the multi device conversation translator scenario is that participants are joining from other devices. In that case, you wouldn't have a ```Conversation``` instance on those devices. The ```SPXERR_UNSUPPORTED_API_ERROR``` is by design to indicate that you shouldn't add participants using the ```Conversation``` instance.

Instead, you'll need to create a new ```ConversationTranslator``` instance and then call join on that. For example:
```C++
auto partAudioConfig = AudioConfig::FromDefaultMicrophoneInput();
auto partConvTran = ConversationTranslator::FromConfig(audioConfig);

partConvTran->JoinConversationAsync("conversation ID e.g. ABCDE", "participant's name", "participant's language e.g. en-US").get();
```
It is up to your specific scenario to determine how the conversation ID is shared to participant devices. For example, if you are using this in a conference setting to provide live captions in multiple languages, you could project the conversation ID along with your slides/presentations where everyone could see it.

You can find more details on how to join a conversation here:
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/quickstarts/multi-device-conversation?pivots=programming-language-cpp#build-and-run-the-application-to-join-an-existing-conversation

The ```Conversation::AddParticipantAsync(...)``` methods are for the ```ConversationTranscriber``` scenario that supports diarization (identifies who is speaking), requires a multi channel audio device, and does not support joining from different devices.
