### ISSUE TITLE
Mac OS - Java - STT with Microphone issue

### ISSUE THREAD

**Issue by abhilashjohn** [Azure-Samples/cognitive-services-speech-sdk#715]
**Describe the bug**

https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/quickstarts/setup-platform?tabs=dotnet%2Clinux%2Cjre%2Cbrowser&pivots=programming-language-java
In this document, there are pre-requisites mentioned for many OS, except Mac. What are the pre-requisites for running the CLI? I am unable to run the application and provide mic input. The program is not accepting a mic input, however, audio from a file is accepted. 

**To Reproduce**
1. In Mac OS, try running the STT example (SpeechRecognitionSamples.recognitionWithMicrophoneAsync())
**NOMATCH: Speech could not be recognized.**
     **Execution done. Your choice (0: Stop):** 
     **0**
**Exiting...**

**Execution done. Your choice (0: Stop):** 
**Finishing demo.**

**Expected behavior**
As per the documentation, a speech input should be accepted via Mic and converted to a text

**Version of the Cognitive Services Speech SDK**
Which version of the SDK are you using. : **1.12.1**

**Platform, Operating System, and Programming Language**
 **- OS:MacOS 10.15.5 (19F101)**
 **- Hardware - 1.4 GHz Quad-Core Intel Core i5**
 **- Programming language: Java**
 **- Browser NA**

**Additional context**
 - Error messages, log information, stack trace, ...
 - If you report an error for a specific service interaction, please report the SessionId and time (incl. timezone) of the reported incidents. The SessionId is reported in all call-backs/events you receive.
 - Any other additional information

**Comment by trrwilson** [comment]
Hello! Thanks for getting in touch.

I'll follow up with some of the macOS experts on our team, but the fact that you see a "no match" rather than an error suggests that default microphone capture is coming from another device (I run into this all the time with samples if I plug in a headset and forget that default capture has routed to that instead of an in-built microphone array).

One thing to check is the default microphone configuration on the OS (this is where I need to draw from the team's macOS expertise as I have very little); another is that you can try modifying the AudioConfig to use `fromMicrophoneInput(string id)` rather than `fromDefaultMicrophone()`, which will allow you to specify a device explicitly. We have instructions (written for obj C but transferrable) for getting the device ID here: https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-select-audio-input-devices#audio-device-ids-on-macos

**Comment by abhilashjohn** [comment]
Further on this, this looks like a permission issue in Mac. Eclipse/Java doesn't seem to be having mic access. Tried multiple options including reinstallations and restarts, no luck yet..

**Comment by chlandsi** [comment]
Could you please check that eclipse has been granted microphone access following these [docs](https://support.apple.com/en-gb/guide/mac-help/mchla1b1e1fe/10.15/mac/10.15)?

**Comment by abhilashjohn** [comment]
I am not seeing Eclipse/Java listed in there. That is the challenge I am facing currently.

**Comment by chlandsi** [comment]
Can you try to run the sample from a terminal? The Terminal app should then ask for microphone permissions.

**Comment by abhilashjohn** [comment]
Tried , no luck yet. will try additional pointers I am seeing in the web

**Comment by pankopon** [comment]
Closed since no updates + general macOS permission issue. Please open a new item if you need more support.
