### ISSUE TITLE
Cannot set Direct Line Speech Bot ID using C# client 1.11

### ISSUE THREAD

**Issue by leocurrie** [Azure-Samples/cognitive-services-speech-sdk#733]
**Describe the bug**

Setting the botId in the third parameter of `BotFrameworkConfig.FromAuthorizationToken` seems to have no effect

**To Reproduce**
Steps to reproduce the behaviour:
1. In Azure Portal, create two different Bot Channel Registrations in the same region. Enable the Direct Line Speech channel for both bots. Configure both Direct Line Speech channels to share the same Speech Resource (subscription key). Ensure one of the two DLS channels is configured with the _Make this a default bot for chosen cognitive service account_ checkbox checked.
2. Create a client that connects to the bot using the botId of the second (non-default) bot. The botId should be passed into the third parameter of `BotFrameworkConfig.FromAuthorizationToken`

**Expected behaviour**
According to the [documentation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.dialog.botframeworkconfig.fromauthorizationtoken?view=azure-dotnet), setting the botId should result in a conversation being started with the second, non-default bot.
In fact it seems as though setting this parameter has no effect - the Activities are always sent to the default bot.

**Version of the Cognitive Services Speech SDK**
C# 1.11

**Platform, Operating System, and Programming Language**
 - OS: Windows 10 19041.330
 - Hardware: x64
 - Programming language: C#
 - Browser: N/A

**Additional context**
When using the Javascript (1.12.1) version of the client SDK, we are able to set the botid correctly by calling `setServicePropery("botid", botId, ServicePropertyChannel.UriQueryParameter)` on the config. However, using this approach with the C# client causes an error: 

> ErrorCode=ConnectionFailure, ErrorDetails=Error: Connection was closed by the remote host. Error code: 1011. Error details: 'https' is an unexpected token. The expected token is '"' or '''. Line 1, position 96.

**Comment by rhurey** [comment]
Thanks for contacting us with this. Our team is investigating the cause and will update when they know more.

**Comment by trrwilson** [comment]
Hi Leo! Great to chat with you again and thanks for posting here.

We've identified the root cause of this issue and we're discussing the right longer-term fix to make these factory methods (with the bot ID overloads) work as expected. One way or another, it'll quietly arrive in an upcoming SDK release or service deployment. In the meantime, we very clearly have a bug in the fact that the parameter effectively doesn't do anything.

But we do have a workaround that can be employed for a while--definitely until we have the above-mentioned fix. That workaround is to set a "botid" query string parameter on the config object (either instead of or in addition to the factory; I'd recommend in addition to since that part will then need no future code changes):

```csharp
var config = BotFrameworkConfig.FromAuthorizationToken(authToken, region, botId);
// Needed temporarily pending the resolution of the bug around the factory use of botId
config.SetServiceProperty("botid", botId, ServicePropertyChannel.UriQueryParameter);
var connector = new DialogServiceConnector(config);
```

This will appropriately make the `DialogServiceConnector` contact the bot you specify in that query string parameter.

**Disclaimer:** the `SetServiceProperty` call is *not* a recommended long-term solution since we reserve the right to mess with string literal properties at any time--the `PropertyId` enum (which doesn't have this) is the stable property mechanism. I'll make sure we don't mess with this particular property for the time being, though.

Thanks!

**Comment by leocurrie** [comment]
Hi Travis - Thanks for picking this up.

We followed your suggestion and this is now working for us as desired. I have no idea why the 'https' error was appearing either - I can only assume it was some kind of typo because we're now unable to reproduce it.

Anyway - the `SetServiceProperty `approach is working fine for us now. 

Thanks!

**Comment by glecaros** [comment]
Hi, we have an item in our backlog to fix this in an upcoming release. Please reopen this issue if there is anything else that needs follow-up.
