### ISSUE TITLE
Big size of iOS SDK

### ISSUE THREAD

**Issue by emelyanovkirill** [Azure-Samples/cognitive-services-speech-sdk#744]
Why SDK for iOS has a large size, about 250Mb? App for AppStore has this size, even if it is empty

**Comment by rhurey** [comment]
Thanks for asking, in all honesty this took us by surprise the first time we saw it also.

The package size explodes because it contains bitcode. The Speech SDK provides bitcode in the developer package to enable SDK users to publish bitcode enabled apps. (You can read more about bitcode and publishing options here: https://help.apple.com/xcode/mac/11.0/index.html?localePath=en.lproj#/devde46df08a)

End user downloads and device installs will be processed through [App Thinning](https://help.apple.com/xcode/mac/current/#/devbbdc5ce4f) and only the required code for the device will be sent down from the App Store. (Typically the Speech SDK adds a few MB).

Please let me know if this doesn't answer your question.

**Comment by rhurey** [comment]
I'm going to close this assuming my response answered the question. If not lease comment and we can re-open tnis.
