### ISSUE TITLE
speech recognition through rest api or sdk?

### ISSUE THREAD

**Issue by sakethpo** [Azure-Samples/cognitive-services-speech-sdk#758]
Hi!

I'm trying to use python sdk from my application for speech recognition (stt). My app sends opus encoded audio thru the sdk. 

I read that the sdk internally decodes the OPUS audio using gstreamer and sends the raw pcm data to the azure service. Is this true? If so:
1. will using rest api give me better results when sending opus audio? (because i'm pushing opus audio to the service)
2. if i decide to change my audio format to pcm, which among rest api/sdk will give me better performance (best time) for stt?

Additional details:
 Version of the Cognitive Services Speech SDK: 1.13.0
 OS: Ubuntu 18.04
 Hardware - x86_64
 Programming language: Python

Thanks! :)

**Comment by lisaweixu** [comment]
You are right about the SDK internally decodes the OPUS data to PCM and send the PCM to the Speech Service. REST API won't give you better accuracy since REST API and the SDK in the end call the same backend. The SDK offers better accuracy since SDK has retry logic to make sure all bytes are sent to the service. With REST API, you would need to implement the retry logic yourself. In term of latency ( better time), the two should be the more or less the same. You might have to experiment with how fast you are feeding data to REST API to reduce latency. Or you can leave this job to the SDK since it internally figures out the best way to send data to the service.

**Comment by sakethpo** [comment]
@lisaweixu since rest api can send direct opus audio to the backend, would it be possible do the same inside sdk too? probably an enhancement, but it may help in reducing the network traffic imo.

**Comment by glecaros** [comment]
Hi @sakethpo, we have put this on our backlog, and will consider this for one of our next releases. We try to release every month.

**Comment by sakethpo** [comment]
@glecaros thanks!
