### ISSUE TITLE
Swift iOS from Microphone Sample app doesn't work

### ISSUE THREAD

**Issue by Ananya-96** [Azure-Samples/cognitive-services-speech-sdk#765]
**Description**
Sample app for Swift IOS from Microphone doesn't display the recognized text. Throws error

```
020-08-13 17:56:21.189503+0530 helloworld[3869:86736] [] nw_connection_get_connected_socket [C1] Client called nw_connection_get_connected_socket on unconnected nw_connection
2020-08-13 17:56:21.189766+0530 helloworld[3869:86736] TCP Conn 0x600003345a40 Failed : error 0:-65554 [-65554]

```

**To Reproduce**
1. Clone the repo
2. pod install and opened it in Xcode 

**Expected behavior**
Recognized text should be shown

**Version of the Cognitive Services Speech SDK**
SDK version : 1.7
MacOS: 10
XCode version: 11
iPhone 11 simulator: iOS 13

Sample app displays blank screen

![Screenshot 2020-08-13 at 5 58 01 PM](https://user-images.githubusercontent.com/24409739/90134663-1fb15a80-dd8f-11ea-84c6-d28ee5941959.png)

**Comment by glecaros** [comment]
Hi, can you try uploading to the latest version of the SDK?

**Comment by Ananya-96** [comment]
Hi,

Tried SpeechSDK version 1.13.0

Still the recognised text is not getting printed

Getting this error
![Screenshot 2020-08-14 at 10 12 53 AM](https://user-images.githubusercontent.com/24409739/90214791-3f8c6100-de17-11ea-8961-88deb6739ecf.png)

**Comment by jhakulin** [comment]
@Ananya-96 Thanks for report, the problem seems to be in you Mac microphone settings as I tested the sample with the latest 1.13.0 release and sample was working OK, Please check your microphone is configured correctly on Mac. Please also check if you need to add microphone access in your Mac's privacy settings for Xcode similarly as described in this issue
https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/516

**Comment by Ananya-96** [comment]
@jhakulin Thank you for the feedback. I have tested it again in a different phone. Think its an issue with Mac microphone. Thanks.
