### ISSUE TITLE
GPF when using custom PullAudioInputStream in Docker

### ISSUE THREAD

**Issue by witling** [Azure-Samples/cognitive-services-speech-sdk#777]
**Describe the bug**

I am implementing a STT-Service running inside a Docker container. I installed the Python package according to documentation. As I want to forward incoming streaming data to the Microsoft service, I am implementing a custom `PullAudioInputStream`:

```
class CustomAudioInputStream(speechsdk.audio.PullAudioInputStreamCallback):
    def __init__(self, stream):
        super().__init__()
        self._stream = stream
        
    def read(self, view):
        print(view.nbytes)
        return 0
        
    def close(self):
        return super().close()

stream_reader = CustomAudioInputStream(stream)
stream_format = speechsdk.audio.AudioStreamFormat(16_000)
audio_config = speechsdk.AudioConfig(
    stream=speechsdk.audio.PullAudioInputStream(
        pull_stream_callback=stream_reader,
        stream_format=stream_format,
    )
)
recognizer = speechsdk.SpeechRecognizer(audio_config=audio_config, speech_config=self._speech_config)
...
result = await recognizer.recognize_once_async()
```

Running this code causes the following error in `/var/log/messages` on the Docker host:

```
Aug 20 09:28:56 kernel: traps: gunicorn[28266] general protection ip:7f0222d44ed4 sp:7f021e150ce8 error:0 in _speech_py_impl.so[7f0222bd9000+26d000]
```

Passing in a standard `PullAudioInputStream` causes no problem.

**Expected behavior**
Print the size of the given `memoryview`.

**Version of the Cognitive Services Speech SDK**
1.13.0

**Platform, Operating System, and Programming Language**
 - OS: RHEL 7
 - Hardware: x64
 - Programming language: Python

**Additional context**
Related issue: https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/321

**Comment by pankopon** [comment]
Hi, I made an example (attached) that uses a pull stream and prints memoryview nbytes.

[pull_stream_example.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/5144403/pull_stream_example.zip)

This is not 1:1 with your current implementation as the example uses a wav file as a source whereas in your case the data may come from elsewhere, but in general the logic is the same. I tested it on a CentOS 7.8 x64 container (with the necessary newer C/C++ runtimes built from sources) which should work exactly like RHEL 7.

Please first try the attached example as is (with your subscription key and service region, plus some speech wav file). If you can run it successfully then just adapt the code to your use case, otherwise let us know of any issues.

**Comment by witling** [comment]
Hi @pankopon, Thanks for your feedback on this issue. Your example works indeed. My guess would be that the usage of `gunicorn` leads to some error here - maybe even related to `multiprocessing`.

I personally stopped using the official microsoft api as it requires installation of OS packages and feels more restricted. Chunked HTTP transport onto the rest api seems to work quite well though. Feel free to close this issue if you count it as resolved.

**Comment by pankopon** [comment]
Closing the issue as resolved.
