### ISSUE TITLE
Is there a Maximum Time Limit For Speech Synthesis To Detect An Input Before It Turns The Mic Off?

### ISSUE THREAD

**Issue by roperjonathan** [Azure-Samples/cognitive-services-speech-sdk#781]
Hi there,

When using the Azure STT on a web page, I'm noticing that if a speech recognition session doesn't detect an input after 15 seconds or so, it will then trigger the call to stop the session and turn the microphone off?

Is this the expected behaviour or should it be that I can keep the microphone on for as long as I need to? If this is the expected behaviour, is there a way to be able to keep the microphone on longer before the session is stoped and the mic gets closed?

**Comment by pankopon** [comment]
Hi, so this is about recognition not synthesis (text-to-speech), right? The Speech Service stops recognizing if there is no speech within a certain timeout period. Please see issue #502 for more information about the timeout parameters.

With a single-shot recognition (RecognizeOnceAsync or similar, depending on the programming language you are using), you will need to call the method again to do another recognition if the (initial) silence timeout expires.

With continuous recognition (StartContinuousRecognitionAsync), the Speech SDK does internally handle the situation so that connection to the Speech Service is maintained and recognition continues (you will get 'no match' or empty results if there is no speech) until your app calls StopContinuousRecognitionAsync.
