### ISSUE TITLE
Speaker Identification not working in javascript

### ISSUE THREAD

**Issue by GithubUsernameRuchi** [Azure-Samples/cognitive-services-speech-sdk#786]
The browser is throwing error everytime the function is invoked.
The data is not getting passed from the mic.
Am I missing something? Please suggest.

**Comment by brandom-msft** [comment]
hi @GithubUsernameRuchi - can you share some more information about your setup? 


**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. ...
2. ...

**Expected behavior**
A clear and concise description of what you expected to happen.

**Version of the Cognitive Services Speech SDK**
Which version of the SDK are you using.

**Platform, Operating System, and Programming Language**
 - OS: [e.g. Windows, Linux, Android, iOS, ...] - please be specific
 - Hardware - x64, x86, ARM, ...
 - Programming language: C#, C++, Java, JavaScript, Objective-C, Python
 - Browser [e.g. Chrome, Safari] (if applicable) - please be specific

**Additional context**
 - Error messages, log information, stack trace, ...
 - If you report an error for a specific service interaction, please report the SessionId and time (incl. timezone) of the reported incidents. The SessionId is reported in all call-backs/events you receive.
 - Any other additional information

**Comment by pankopon** [comment]
@GithubUsernameRuchi Is this still a valid issue for you? Please update with more details as requested.

**Comment by pankopon** [comment]
Closed since no update from the customer, please open a new issue if you need further support.
