### ISSUE TITLE
spx client fails when run inside default docker image

### ISSUE THREAD

**Issue by qstearns** [Azure-Samples/cognitive-services-speech-sdk#822]
**Describe the bug**

Running the `spx` CLI via Docker fails by default when run with:

```bash
docker run -v $PWD:/data -it --rm msftspeech/spx recognize --format mp3 --file /data/test.mp3
```

It yields the error message:
```
SPX - Azure Speech Service Command Console, Version 1.13
Copyright (c) 2020 Microsoft Corporation. All Rights Reserved.

  audio.input.file=/data/test.mp3
  audio.input.format=mp3
  audio.input.type=file
  diagnostics.config.log.file=log-{run.time}.log
  output.all.audio.input.id=true
  output.all.recognizer.recognized.result.text=true
  output.all.recognizer.session.started.sessionid=true
  service.config.key=e7523794afe046e081b592cb15eed8fa
  service.config.region=eastus
  x.command=recognize

  ERROR: Exception with an error code: 0x29 (SPXERR_GSTREAMER_NOT_FOUND_ERROR)
```

**To Reproduce**
1. From a fresh directory, run:
```bash
docker run -v $PWD:/data -it --rm msftspeech/spx config @region --set [your region]
docker run -v $PWD:/data -it --rm msftspeech/spx config @key --set [your key]
curl -SLo test.mp3 http://soundbible.com/grab.php?id=2112&type=mp3
docker run -v $PWD:/data -it --rm msftspeech/spx recognize --format mp3 --file /data/test.mp3

```
2. ...

**Expected behavior**
This should execute the recognize request.

**Version of the Cognitive Services Speech SDK**
Which version of the SDK are you using.

**Platform, Operating System, and Programming Language**
 - OS: Manjaro Linux, Kernel 5.8.6.1
 - Hardware - x86
 - Programming language: CLI

**Additional context**
I fixed for myself by adding the following install to a local Docker image:

```
apt-get install -y libgstreamer1.0-0 \
  gstreamer1.0-plugins-base \
  gstreamer1.0-plugins-good \
  gstreamer1.0-plugins-bad \
  gstreamer1.0-plugins-ugly
```

**Comment by BrianMouncer** [comment]
@qstearns thanks for contacting us,

Yes, by default docker is only configured to support wave file input.
To use MP3 files, you need to add the GStreamer and codecs so SPX can transcode MP3 to an input the service supports.

I'll ask and see if GStreamer was left out accidentally, or intentionally due to "redistribution" licensing restrictions.
If we are allowed to, I will create a work item request to update our default docker container so MP3 would work by default in a future release.

If there is nothing else, I would like to close this GitHub issue?

Thanks,

Brian.

**Comment by pankopon** [comment]
Closed as resolved.
