### ISSUE TITLE
in windows 7 ModuleNotFoundError: No module named '_speech_py_impl'

### ISSUE THREAD

**Issue by 123rui** [Azure-Samples/cognitive-services-speech-sdk#849]
I wrote software in Python on windows 10, It works.but on some windows 7 systems will report this error ModuleNotFoundError: No module named '_speech_py_impl'.Then I follow the introductory tutorial in the windows 7 run demo, found also reported this error.The software on another windows7 worked fine again.
So is there any special dependent file for this? If there is any solution, please tell me. Thank you very much.

![报错](https://user-images.githubusercontent.com/26771382/97337603-740ea580-18bb-11eb-88f5-bb733e83b401.png)

**Comment by 123rui** [comment]
I've already installed VC_redist.x64

**Comment by lisaweixu** [comment]
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-sdk?tabs=windows%2Cubuntu%2Cios-xcode%2Cmac-xcode%2Candroid-studio#get-the-speech-sdk

Sorry, Win7 is not supported. I can't find a win7 box near me since I am WFH. 
However, you need to install the vs2019 runtimes, following [here](https://docs.microsoft.com/en-us/azure/cognitive-services/Speech-Service/releasenotes#speech-sdk-1130-2020-july-release)
The Speech SDK on Windows depends on the shared Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019. Download and install it from [here](https://support.microsoft.com/help/2977003/the-latest-supported-visual-c-downloads).
