### ISSUE TITLE
How to define the output language in quickstart.py

### ISSUE THREAD

**Issue by JoergZ2** [Azure-Samples/cognitive-services-speech-sdk#886]
I am currently learning how to use Azure language services with Python scripts. The script quickstart.py works basically. But I get the voice output of a German text with an American colored voice. I tried speech_recognition_language() an endpoint definition with added language append: https://westeurope.tts.speech.microsoft.com/cognitiveservices/v1?language=de-DE. No success. So far I haven't found any hint in the documentation how to activate the German voices. Can you give me a hint or a few lines of code example how to get a german voice output?

**Comment by BrianMouncer** [comment]
What API area, or end goal are you using (SR, TTS, Translation)?

If translation, can you take a look at this sample?
https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/python/console/translation_sample.py

If just TTS, then look here...
https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/python/console/speech_synthesis_sample.py

If you want to use a specific voice, rather than just set the spoken language, see this code with speech_synthesis_voice_name()  in the above sample...

```
def speech_synthesis_with_voice():
    """performs speech synthesis to the default speaker with specified voice"""
    # Creates an instance of a speech config with specified subscription key and service region.
    speech_config = speechsdk.SpeechConfig(subscription=speech_key, region=service_region)
    # Sets the synthesis voice name.
    # The full list of supported voices can be found here:
    # https://docs.microsoft.com/azure/cognitive-services/speech-service/language-support#text-to-speech
    voice = "Microsoft Server Speech Text to Speech Voice (en-US, BenjaminRUS)"
    speech_config.speech_synthesis_voice_name = voice
    # Creates a speech synthesizer for the specified voice,
    # using the default speaker as audio output.
    speech_synthesizer = speechsdk.SpeechSynthesizer(speech_config=speech_config)

**Comment by JoergZ2** [comment]
Thanks! Just some ours later I found the example codes for TTS you mentioned. They are really helpful.
