### ISSUE TITLE
RUNNING status since 3 hours and half instead of 20 minutes for python batch_transcription sdk

### ISSUE THREAD

**Issue by veromos** [Azure-Samples/cognitive-services-speech-sdk#891]
Hi all,

I'm using python sdk for batch_transcription, it works well until now, it usually takes 20 minutes to transcript my 140 daily audio files.
But today i launched my batch_transcription at 11:52am 2020-12-07 and it's been returning status : RUNNING since 3 hours and half now, is it possible that the transcription crashed and ran into an infinite loop ?

How good is batch_transcription for industriel solutions ?
And is there a way to print more informations about the transcription instead of showing only the status ?

Thanks you in advance,

My transcription informations : 
```
"self": "https://francecentral.api.cognitive.microsoft.com/speechtotext/v3.0/transcriptions/e1fc7e7c-dfbd-4b4c-9a07-a966a254ccd5",
"lastActionDateTime": "2020-12-07T11:52:02Z",
"status": "Running",
"createdDateTime": "2020-12-07T11:51:56Z",

"self": "https://francecentral.api.cognitive.microsoft.com/speechtotext/v3.0/transcriptions/4dcd2a39-c8ad-44d6-8ba5-b2049e56d91a"
"lastActionDateTime": "2020-12-07T13:34:17Z",
"status": "Running",
"createdDateTime": "2020-12-07T13:34:15Z",
```

**Comment by chlandsi** [comment]
Hi @veromos, there was indeed a problem with the service where some of your files were not processed in due time. The request is completed now, but some of the transcriptions failed, presumably because the SAS Urls were expired. Please retry those transcriptions.
While we are still investigating why the processing was slow in this particular case, we have already deployed a fix which will schedule transcriptions more aggressively, so a large delay like the one today shouldn't happen again. I apologize for the inconvenience.
It is also on the roadmap to expose more status information about transcription jobs, but not with a fixed date yet.

**Comment by chlandsi** [comment]
Hi @veromos, it seems there is something particular about the audio files you were trying to transcribe which causes our streaming audio processing to fail. Would it be possible to make some of the failed audio files available to us for analysis? You can contact me at <my alias> at microsoft.com.

**Comment by veromos** [comment]
Hi @chlandsi,

I figured out that some of my audio files i'm trying to transcribe are empty (audio track of 0 seconds), so that's what caused the bug that confused me.
I didn't receive any error messages for a long time (I got one exception if I didn't cancel my process, but it just says that `transcription.properties.error.message` is null).

Also I have a quick question that has nothing to do with the issue, i'm new to Azure Cloud, what is for you, the simplest way to store my python code to launch my solution daily (it lasts around 25minutes a day), would it be a logic app ? an azure function ? or a virtual machine ?
