### ISSUE TITLE
High CPU usage for single ogg audio with gstreamer

### ISSUE THREAD

**Issue by henlin-msft** [Azure-Samples/cognitive-services-speech-sdk#902]
**Describe the bug**
The CPU usage is about 20~30% for 4 core CPU's when using gstreamer for single ogg audio. The issue can be reproduced on both Windows (with .net or Java) and Linux with Java.

**To Reproduce**
Follow the steps to support ogg with SDK

**Expected behavior**
The CPU usage needs to be as low as 5% :)

**Version of the Cognitive Services Speech SDK**
1.12.1

**Platform, Operating System, and Programming Language**
 - OS: Windows, Linux
 - Hardware - x64, x86
 - Programming language: C#, Java
 - Browser: n/a

**Comment by yasar83** [comment]
Hiermit storniere ich eure E-Mails schicken Sie mir bitte keine E-Mails mehr

Mit freundliche Grüße

Am 21.12.2020 um 04:58 schrieb henlin-msft <notifications@github.com>:

﻿

Describe the bug
The CPU usage is about 20~30% for 4 core CPU's when using gstreamer for single ogg audio. The issue can be reproduced on both Windows (with .net or Java) and Linux with Java.

To Reproduce
Steps to reproduce the behavior:
Follow the steps to support ogg with SDK

Expected behavior
The CPU usage needs to be as low as 5% :)

Version of the Cognitive Services Speech SDK
1.12.1

Platform, Operating System, and Programming Language

  *   OS: Windows, Linux
  *   Hardware - x64, x86
  *   Programming language: C#, Java
  *   Browser: n/a

**Comment by henlin-msft** [comment]
libopus could be an option to solve the issue.
https://opus-codec.org/

**Comment by yasar83** [comment]
Noo email noooooo

Mit freundliche Grüße

Am 24.12.2020 um 06:04 schrieb henlin-msft <notifications@github.com>:

﻿

libopus could be an option to solve the issue.
https://opus-codec.org/

**Comment by pankopon** [comment]
Thank you for the improvement suggestion. I have added a work item to our backlog and it will be considered for future releases, we will update here when the release schedule is known.

Closing the issue, please create a new item if you need support on other topics.
