### ISSUE TITLE
Please add cancel(),isListening(),recognizedOneAsync(timeout:MillSeconds) to SpeechRecognition SDK!

### ISSUE THREAD

**Issue by incomingflyingbrick** [Azure-Samples/cognitive-services-speech-sdk#920]
We should have a cancel() function when we don't have to send speech to the server.
We want to be able to check weather the sdk is isListening to Mic input, so i can show it on UI
recognizedOneAsync timeout is 15seconds , I want to change it to 10 seconds or 8 seconds.

**Comment by zxubian** [comment]
Another option would be to allow passing a CancellationToken. Either way, being able to cancel would be nice.

**Comment by trrwilson** [comment]
Thanks for these suggestions!

- cancel() is an interesting one, as there may be a way to achieve this with existing functionality. It depends a bit on which kind of "cancel" you'd like to do:
  -  If you'd like to "stop now" (don't send any more audio but wait for the result for whatever was sent so far), you can call `StopContinuousRecognitionAsync` on the `SpeechRecognizer` (even if you used `RecognizeOnceAsync` -- yes, this is odd) and it will quickly finish
  - If you'd like to "abort" (stop sending audio, don't try to get a result, just stop doing everything!), you can retrieve a connection via `Connection::FromRecognizer` and then call `Close` on that connection. This will raise a Canceled event and immediately terminate everything.
- isListening() is a great idea for ease of use. As a way to achieve this, you can keep track of `SessionStarted` and `SessionStopped` events, as these map to when the SDK is capturing audio: when you get a `SessionStarted`, audio capture has started; when you get a `SessionStopped`, audio capture has ended.
- Can you share more about what you'd like to see with timeouts? A recognition should end before the 15s if a bit of silence (or near-silence) is detected, or if `StopContinuousRecognitionAsync` is called per the above. Can you tell us more about what your project is doing and what's not behaving the way you'd like it to?

Thank you!

**Comment by Vytenis** [comment]
@trrwilson , this cancel() would be also beneficial for us. We have multiple streams sent to transcription in conversation. So cancel() or returntTranscriptSofar() would help on conversations to separate streams with better accuracy. Do you think this can be implemented? Or your approach would be:
- on dominant speaker change for past speaker:
StopContinuosRecognition;
StartContinuosRecognition; // not to loose any bits if he was just interrupted.

What do you think?

**Comment by trrwilson** [comment]
What you outline (Stop immediately followed by Start) will do a pretty good job, but I do see the problem you mention--there will be a (very brief) period of time where audio _isn't_ being listened to between the resolution of the Stop and Start calls. That's almost always OK and even expected (a manual "stop" usually implies a user-involved stop event), but in the case of an arbitrary "stop now" that could be right in the middle of a user speaking, that can be a problem.

There's another issue to consider with a "returnTranscriptSoFar" style of approach, though, and that's that the "recognized" style of final results can be very misleading if they don't have a complete utterance (usually as defined by silence). An example of this would be a user saying (and the system stopping): "I'm going to go pick up the groceries and <getTranscriptNow/> two pizzas."

In the above, if we let the system detect silence at the end (or stop it at the natural place by any other means), it'll do a good job of using the rest of the sentence to infer the right recognition--you'll get a single final result out of recognized with something that looks correct. If we force it to return two distinct results, however, it loses all that sentence context and will probably end up with two results that aren't quite right, e.g.:
* "I'm going to go pick up the groceries in."
* "To pizzas."

Understanding your use case a bit better, I wonder if the "recognizing" events (intermediate results that don't require stopping/starting anything) could serve as the indication you need. These happen quite regularly during an utterance. Have you experimented with those and found a gap in what they do?

**Comment by Vytenis** [comment]
@trrwilson we understand this. But with our heavy testing we experience real life situations when one person is finished, another person is still speaking and up to 12 second (yes, twelve!) transription is not being returned. How ever if during the same time we make a random noise (f.e. apchi or cough) - transcription appears immediately.

I pinged you on LinkedIn as don't have your email or in chat on Microsoft dedicated channel we are in for partners. I'd love to explain in detail privately. We do have NDAs signed :)

**Comment by pankopon** [comment]
To summarize the current discussion, please correct as necessary:

- The desired functionality of cancel() and isListening() can be achieved as per comment https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/920#issuecomment-767768144.

- For adjusting RecognizeOnceAsync timeout:
  - There is InitialSilenceTimeoutMs setting (see https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/502) which can be used to control how much silence the input audio can have from the beginning before RecognizeOnceAsync returns due to no speech in input.
  - For other than that, you could use PushAudioInputStream or PullAudioInputStream to feed the audio to the SDK library and thus manage how much audio goes in before closing the stream. I've also added a work item to our backlog to make the max duration of RecognizeOnceAsync configurable (currently the setting is service internal only), for consideration in future Speech SDK releases.

**Comment by Vytenis** [comment]
@pankopon , am I missing something or InitialSilenceTimeoutMs  is for Java SDK, but not for Javascript / nodejs?

**Comment by pankopon** [comment]
@Vytenis I don't think we have received reports of that kind at least recently. The initial silence timeout is a parameter that's passed directly to the service backend in the cloud where recognition is done.

**Comment by pankopon** [comment]
Closing this item since instructions have been provided to achieve some of the desired functionality by using existing APIs, and there's a work item for additional enhancements (configurable max duration of RecognizeOnceAsync) which will be considered for future Speech SDK releases. We will provide an update here when implementation is done and the release schedule is known. Please open a new issue if you need support on other specific topics.
