### ISSUE TITLE
No matching distribution found on docker build on the new mac book pro with M1 processor

### ISSUE THREAD

**Issue by amitrahav** [Azure-Samples/cognitive-services-speech-sdk#928]
**Describe the bug**
On docker-compose build, with the this docker file:
```Dockerfile
FROM python:3.7

RUN apt-get update \
  && apt-get install -y\
  curl \
  build-essential \
  libssl1.0 \
  libasound2 \
  libsndfile1 

WORKDIR /etc/www/
RUN python -m pip install --upgrade pip
RUN python pip install azure-cognitiveservices-speech
```

I get the folowing error: 
```Bash
ERROR: Could not find a version that satisfies the requirement azure-cognitiveservices-speech
ERROR: No matching distribution found for azure-cognitiveservices-speech
```

**To Reproduce**
1. Use a MacBook Pro (13-inch, M1, 2020)
2. Install a docker client
3. Create a Dockerfile described above
4. Run `docker build .`

**Expected behavior**
Finding and installing the latest version of `cognitive-services-speech-sdk` with pip

**Version of the Cognitive Services Speech SDK**
I would like to use the latest version

**Platform, Operating System, and Programming Language**
 - OS: 
     -  Docker client runs on macOs Big Sur
     -  Docker image based on Debian GNU/Linux 10 (buster)
 - Hardware - Apple M1
 - Programming language: Python3.7 with pip20.3.3, inside the docker build process the out put of `python -c "import struct; print(struct.calcsize('P') * 8)"` is 64.

**Comment by glharper** [comment]
@brandom-msft The last line should be
```
RUN pip install azure-cognitiveservices-speech
```

**Comment by amitrahav** [comment]
Tried this variation first... I got the same error.

**Comment by pankopon** [comment]
The Speech SDK does not currently have a Python module for Linux ARM64 which I believe is the architecture of your Debian docker image since you are building and running it on Apple M1. We do have a backlog item about it which is tentatively scheduled for this spring but not confirmed.

Please see the list of supported Linux distributions, target architectures, and programming languages:
https://docs.microsoft.com/azure/cognitive-services/speech-service/speech-sdk?tabs=linux%2Cubuntu%2Cios-xcode%2Cmac-xcode%2Candroid-studio#get-the-speech-sdk
