### ISSUE TITLE
Missing "Microsoft.CognitiveServices.Speech.core.dll" in Blazor WASM project

### ISSUE THREAD

**Issue by arqe** [Azure-Samples/cognitive-services-speech-sdk#930]
Hi, 

I am trying to use Microsoft.CognitiveServices.Speech SDK in Blazor Web Assembly project (C#) and I cannot pass this issue. 
VS2019 does not seem to include the Microsoft.CognitiveServices.Speech.core.dll to the build output. 

I was not able to workaround by manual copying that library to the output folder (that reportedly worked for desktop targets). 

https://stackoverflow.com/questions/65761453/azure-speech-to-text-c-sdk-in-blazor-webasm-app-bug

Thanks a lot

**Comment by jhakulin** [comment]
@arqe I am not familiar about Blazor and before digging deeper, could you please check if installing latest Microsoft Visual C++ Redistributable helps ?

The Speech SDK on Windows depends on the shared Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019. Download and install it from here.

**Comment by arqe** [comment]
@jhakulin I can confirm that. 
I already reinstalled the C++ Redistributable to version 14.28.29325.2, but the problem persists.

**Comment by trrwilson** [comment]
Unfortunately, the core SDK (that `.core.dll`) is portable C++ code that doesn't yet target WASM. What you see is that blazor can resolve the pure .NET binding DLL (`.csharp.dll`) and make it work, but the magic that makes it possible for blazor to run .NET DLLs in WASM doesn't work for C++. When you copy the x86/x64 `.core.dll`, it still says "not found" because those are targeting the wrong architecture -- native code needs the explicit WASM target to work.

For this to happen, the SDK team needs to do work to add WASM as a compilation target for the core DLL. I'll ensure there's an item on our backlog to track it.

In the meantime, we do have a JS SDK that's well-suited to browser use and should work side-by-side with WASM and other web tech. Would that be able to meet your needs?
https://github.com/Microsoft/cognitive-services-speech-sdk-js

**Comment by arqe** [comment]
@trrwilson 
It makes all clear - I'll start digging into the js-sdk option. Thank you for exhaustive explanation!

**Comment by mkb13** [comment]
I know this is closed due to a workaround but I would love if it it were fixed (It doesn't appear to be yet -- just tried it).
