### ISSUE TITLE
How to use StartContinuousRecognitionAsync for NodeJS?

### ISSUE THREAD

**Issue by ioanatatu** [Azure-Samples/cognitive-services-speech-sdk#931]
Hi,
Is there any example of how to use StartContinuousRecognitionAsync with NodeJS, in combination with fs.createReadStream? The StartContinuousRecognitionAsync is supposed to take a callback, but what parameters does the callback take? An array of files? The documentation does not offer enough details in this respect. I have a bunch of audio files in a directory that I want to read and then have transcribed by the service.

Any suggestion would be much appreciated!

**Comment by glharper** [comment]
@ioanatatu Thanks for logging this issue. Start with [This sample](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/javascript/node/from-file), which uses fs.createReadStream with NodeJS for the recognizeOnceAsync method. Two changes to make to the sample for your use case: 
- Substitute "recognizeOnceAsync" with "startContinuousRecognitionAsync" to process the entire file (instead of the first 5 seconds). 
- Add the following callback to see ongoing text results:
```
  recognizer.recognized = (reco, e) => {
    try {
        const res = e.result;
        console.log(`recognized: ${res.text}`);
    } catch (error) {
        console.log(error);
    }
  };
```
(Because startContinuousRecognitionAsync runs for an arbitrary length, with multiple results from the backend, the actual callback parameter startContinuousRecognitionAsync() will just return when recognition has started without any result info.)

That should get you started, I'll leave processing multiple files in turn to you. You may want to add a callback to recognizer.canceled similar to above to detect when each file has finished transcription. (AFAIK the Speech SDK does not have a speech recognition method taking an array of filenames as a parameter.)

**Comment by trrwilson** [comment]
Please let us know if you hit any issues with this--as a general procedure, I'll tag this issue for closing if there's no new activity. Thanks!

**Comment by acedev0816** [comment]
I also think StartContinuousRecognitionAsync is not working

**Comment by glharper** [comment]
> I also think StartContinuousRecognitionAsync is not working

@acedev0816 Please open a new issue with sample code instead of commenting on an issue closed two years ago. Thanks. Deleting your comment and mine.
