### ISSUE TITLE
speech_recognizer.recognized.connect is not working and printing when doing speech to text from custom source Python

### ISSUE THREAD

**Issue by yashugupta786** [Azure-Samples/cognitive-services-speech-sdk#939]
I am trying to do speech to text from a custom audio here i have taken wav file converted to frame per frame . In real time i will be using meetings audio stream . While doing the speech to text using push audio  stream i want to retrieve the complete text .  
speech_recognizer.recognized.connect(lambda evt: print('RECOGNIZED: {}'.format(evt))) 

not printing anything please find the below complete code 
#------------------------------------------------------------------------------------------------------------------------------------------
'''

import azure.cognitiveservices.speech as speechsdk
import wave
import time
weatherfilename="whatstheweatherlike.wav"
def speech_recognition_with_push_stream():

    # setup the audio stream
    speech_config = speechsdk.SpeechConfig(subscription=key, region=region)
    stream = speechsdk.audio.PushAudioInputStream()
    audio_config = speechsdk.audio.AudioConfig(stream=stream)
    def recognized_cb(evt):
        print("from source",evt.result)
    # instantiate the speech recognizer with push stream input
    speech_recognizer = speechsdk.SpeechRecognizer(speech_config=speech_config, audio_config=audio_config)
    # Connect callbacks to the events fired by the speech recognizer
    speech_recognizer.recognized.connect(recognized_cb)
    speech_recognizer.session_started.connect(lambda evt: print('SESSION STARTED: {}'.format(evt)))
    speech_recognizer.recognizing.connect(lambda evt: print('RECOGNIZING: {}'.format(evt)))
    speech_recognizer.recognized.connect(lambda evt: print('RECOGNIZED: {}'.format(evt)))
    speech_recognizer.session_stopped.connect(lambda evt: print('SESSION STOPPED {}'.format(evt)))
    speech_recognizer.canceled.connect(lambda evt: print('CANCELED {}'.format(evt)))

    # The number of bytes to push per buffer
    n_bytes = 8000
    wav_fh = wave.open(weatherfilename)

    # start continuous speech recognition
    speech_recognizer.start_continuous_recognition()

    # start pushing data until all data has been read from the file
    try:
        while(True):
            frames = wav_fh.readframes(n_bytes // 2)
            print('read {} bytes'.format(len(frames)))
            if not frames:
                break
            stream.write(frames)
            time.sleep(.3)
    finally:
        # stop recognition and clean up
        wav_fh.close()
        stream.close()
        speech_recognizer.stop_continuous_recognition()

speech_recognition_with_push_stream()

'''

Please help me in this. i want to capture the final text and pass to other application for further processing .thanks in advance

**Comment by trrwilson** [comment]
Thank you for contacting us!

It looks like the sample code (https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/python/console/speech_sample.py) has an implicit expectation on app lifetime that causes confusion here.

The block you shared (and the sample) calls `stop_continuous_recognition()` *immediately* after the last stream write. That means that `speech_recognition_with_push_stream()` will usually complete (and, if that's all your app does, exit!) a bit *before* the last recognized event shows up (since that final stream write has to reach the service, be processed, and return a result).

Simple ways of fixing this:
1. Ensure the caller doesn't immediately exit. Adding a `time.sleep(1)` to the end of your code block allows the recognition result to be received before the app exits; here's what my output tail looks like, with a millisecond timestamp added to demonstrate:
```python
[34359] read 8000 bytes
SESSION STARTED: SessionEventArgs(session_id=f326a2687dff4dfb9ea2d7ba5078907b)
[34666] read 8000 bytes
[34968] read 8000 bytes
[35270] read 8000 bytes
[35584] read 8000 bytes
[35816] RECOGNIZING: SpeechRecognitionEventArgs(session_id=f326a2687dff4dfb9ea2d7ba5078907b, result=SpeechRecognitionResult(result_id=fc977d1eb06346d6b09e4e241dc6e521, text="what's", reason=ResultReason.RecognizingSpeech))
[35895] read 8000 bytes
[36020] RECOGNIZING: SpeechRecognitionEventArgs(session_id=f326a2687dff4dfb9ea2d7ba5078907b, result=SpeechRecognitionResult(result_id=ba64fd6a13634c33843fd8860728ee30, text="what's the weather", reason=ResultReason.RecognizingSpeech))
[36205] read 8000 bytes
[36426] RECOGNIZING: SpeechRecognitionEventArgs(session_id=f326a2687dff4dfb9ea2d7ba5078907b, result=SpeechRecognitionResult(result_id=6096b033c9b64b7aa3f0a15dedf59bc3, text="what's the weather like", reason=ResultReason.RecognizingSpeech))
[36519] read 8000 bytes
[36833] read 960 bytes
[37145] read 0 bytes
[37209] Starting sleep (previously exited)
[37211] from source SpeechRecognitionResult(result_id=9e05ac027d8a47228bc524b9e1d7a8eb, text="What's the weather like?", reason=ResultReason.RecognizedSpeech)
[38225] Last line (exiting)
```
(As you can see, there's a bit of time -- it's more than 2ms, so my print methodology is off--between the end of the work function and the result arriving)

2. Put that same delay into the work function. I like this better because it doesn't leave the timing to the caller. For that, adding a sleep into the `finally` block right before `speech_recognizer.stop_continuous_recognition()` is called will do the same thing but not require that the caller wait.

3. To avoid static sleeps, you can also `import threading`, create a `threading.Event()` for the `recognized` callback, set it when the callback is hit, and then wait for before stopping.
```python
    got_recognized_event=threading.Event()
    def recognized_cb(evt):
        print('[{}] from source {}'.format(round(time.time() * 1000) % 100000,evt.result))
        got_recognized_event.set()
...
    finally:
        # stop recognition and clean up
        wav_fh.close()
        stream.close()
        got_recognized_event.wait(1)
        speech_recognizer.stop_continuous_recognition()
```
This will allow things to exit just as soon as the result is received:
```
[48344] read 8000 bytes
[48518] RECOGNIZING: SpeechRecognitionEventArgs(session_id=de53a7094bbb43df884af7f68b37b7d4, result=SpeechRecognitionResult(result_id=9e29a111ced847c59e39fbb6144ebcc9, text="what's the weather like", reason=ResultReason.RecognizingSpeech))
[48658] read 8000 bytes
[48973] read 960 bytes
[49287] read 0 bytes
[49398] from source SpeechRecognitionResult(result_id=fcdfeb71167e414188d0f47ca9cb6321, text="What's the weather like?", reason=ResultReason.RecognizedSpeech)
[49399] Last line (exiting)
```

I'll file a work item on the team to clarify this in the sample, as it's certainly confusing. But I hope the above will get things working for you!

**Comment by yashugupta786** [comment]
Sure i will try this fix.Thanks a lot .Adding delay with threading is nice to have .Thanks for the support.
Also one thing i want to ask if you can help me out . I am getting stream from microsoft teams meeting in audio buffer frames .can you tell me how to process that audio buffer frames with this above code, instead of passing a wav file i wan to pass that audio buffer .It would be helpful if you can share some code snippet .
Thanks in advance @trrwilson

**Comment by trrwilson** [comment]
Could you share any documentation or information on those audio buffer frames coming out of Teams? I'm not familiar with what format those arrive in (and I'd be interested in learning!).

Once any requisite conversions are done, it should just be a matter of writing the bytes from the incoming Teams frames into the push stream the same way that they're written from the file above -- or, alternatively, using the pull stream approach from the sample big sample.

**Comment by yashugupta786** [comment]
Please find this link .the code is in c# .once i will have the 
audio bufferr i will consume  it in python 

https://microsoftgraph.github.io/microsoft-graph-comms-samples/docs/bot_media/index.html
It will be of pcm 16k.If you can see the above documentation you will have a good idea

Also if you can tell me what things needs to be change in the above code do doing the speech to text from the above audio source .If you can share some approach that would be  #helpful 
  Do be have to convert the audio frames to bytes  ?

**Comment by glecaros** [comment]
Hi @yashugupta786,

Were you able to resolve you problem?

**Comment by amitkumarshukla** [comment]
@yashugupta786 We are closing the issue right now. Please feel free to create a new issue if you face one.
