### ISSUE TITLE
Cannot Recognize Speech Invalid WAV header in file, data block was not found

### ISSUE THREAD

**Issue by twizzyyanki** [Azure-Samples/cognitive-services-speech-sdk#962]
I have a wav file and I am trying to use it to text azure speech to text using this url - https://azure.microsoft.com/en-us/services/cognitive-services/speech-to-text/#features. I am getting `Cannot Recognize Speech Invalid WAV header in file, data block was not found` error. I am not sure what is wrong and why I am getting this error. The wav file looks totally fine to me. This is the file I am using to test - http://talonsoftwares.com/upload/2422332.wav

**Comment by pankopon** [comment]
Hi, thanks for reporting the issue - the problem occurs because of a WAV header size limit in the JavaScript SDK. There is now a pull request to raise this limit: https://github.com/microsoft/cognitive-services-speech-sdk-js/pull/328

For comparison, https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/sampledata/audiofiles/aboutSpeechSdk.wav where the header has no metadata:

![image](https://user-images.githubusercontent.com/55108151/108128304-65621f00-7061-11eb-8ff1-54addb5455d9.png)

and your 2422332.wav which contains an INFO chunk in the header which happens to go over the limit:

![image](https://user-images.githubusercontent.com/55108151/108128659-f1744680-7061-11eb-83a2-aba3059d297c.png)

**Comment by BriceChivu** [comment]
Hello,
I faced the same issue and I solved it simply by converting my audio sample rate from 48kHz to 16kHz.
It worked well after that.
